### ISSUE TITLE
Gigzi smart contract improved (ETH)

### ISSUE THREAD

**Issue by Gigzi** [EthereumCommonwealth/Auditing#10]
# Audit request

The smart contract allows the Central Authority (CA) to issue tokens backed by precious metals. There will be 3 types of such regulated tokens: GZS silver, GZG gold, GZP platinum and also one non-regulated token GZB black. Tokens have a changeable tx fee (which is set to 0.2% and may be adjusted during the system functioning for its economy benefit). This tx fee is accumulated on CA account; funds will be used for buying precious metals and issuing corresponding precious metals regulated tokens; also for operational expenses. All users who hold GZB tokens on their accounts will receive payments in GZG from the CA; a size of the payment will be proportional to the amount of GZB tokens on the account. Payments will be initiated by the CA at the end of a billing period, off-chain. The initial distribution of GZB is performed by the endless crowdsale. There are bonuses for the GZB purchase during the crowdsale:
15% for 0-530 ETH
30% for 530 ETH+
45% for 1600 ETH+

GZB allocation:
0.5% CA reserve for precious metal initial purchase
1.5% CA reserve for the team
   8% crowdsale
90% locked in the smart contract to compensate GZB tx fees for users (free GZB transactions) until this amount runs out.

10% of total ETH gathered during the crowdsale is instantly transferred to the partner's wallet.

GZB initial supply is 1 000 000 000 (1 billion) tokens.

# Source code

https://github.com/Gigzi/contracts/tree/master/contracts

It's ERC20 standard. We use OpenZeppelin Framework as a basis and need an audit of a custom logic built on top of this framework. Solidity v 0.4.21.

# Disclosure policy

Please send an email to artyom@gigzi.com

# Platform

ETH platform

**Comment by RideSolo** [comment]
Auditing time: 7 days.

**Comment by gorbunovperm** [comment]
Estimated auditing time is 7 days.

**Comment by alexo18** [comment]
Auditing time: 7 days

**Comment by yuriy77k** [comment]
@alexo18 assigned.

**Comment by yuriy77k** [comment]
@RideSolo @gorbunovperm @alexo18 please, paused auditing this contract and make audit https://github.com/EthereumCommonwealth/Auditing/issues/11
We need complete it in two days.

**Comment by gorbunovperm** [comment]
@yuriy77k My report is finished.

**Comment by yuriy77k** [comment]
# []() security audit report performed by [Callisto Security Audit Department](https://github.com/EthereumCommonwealth/Auditing)

# 1. Conclusion:

The contracts reviewed can be considered safe to be deployed. However a lot of optimization has to be done to minimize gas consumption.

## 2. Low severity issues:

## 2.1. Reserved Account of Fee Collector Address not updated

### Description 

The function `setTxFeeCollector` member of `FeeableToken` re-assign fee collector address, but do not reset the reserved account old address to avoid fee collection, however `addReservedAccount` can be used but at the price of extending `accountsReserved` dynamic array.

### Code snippet

https://github.com/GigziProject/GigziContracts/blob/ffe57bdaf1b0d1fb29d182cd03c1890b3be50ac8/contracts/FeeableToken.sol#L65#L68


## 2.2. Known Issues of ERC20 Standard.

#### Description

ERC20 Tokens have some well-known issues (listed bellow), This is just a reminder for the contract developers.

* Approve + transferFrom mechanism allows double Withdrawal attack (as commented on the contract).

* Lack of transaction handling.

The above mentioned issues are well documented, a basic search can help to get more information.


## 2.3. `processTransfer` always returns `false`

### [Code snippet](https://github.com/Gigzi/contracts/blob/0989f4a550ef8ae7110635784a96144d5578d7d1/contracts/GigBlack.sol#L204)

```solidity
function processTransfer(address _from, address _to, uint256 _value) internal returns (bool) {

    // update rewards before transfer
    updateAccountReward          (_from);
    updateAccountReward          (_to);

    FeeableToken.processTransfer (_from, _to, _value);
}
```

### Description

`processTransfer` function of GigBlack contract calls override and call parent function of FeedableToken contract. Parent function returns `true`, but GigBlack `processTransfer` doesn't have a `return` keyword and by default always return `false`. This can distort the logic of the application.

### Recommendation

Use `return FeeableToken.processTransfer (_from, _to, _value);` for right result.


# 3. Minor observations.

## 3.1. Reserved Account Optimization

### Description

Reseverd accounts are used to avoid paying fees for some addresses. Each time if the contract owner wants to add an address he calls `addReservedAccount` adding a new element to `accountsReserved` dynamic array, this practice adds too much gas consumption when checking if the address transaction fees are applicable (in `isFeeShouldBePaid` function).

### Code Snippet

https://github.com/Gigzi/contracts/blob/0989f4a550ef8ae7110635784a96144d5578d7d1/contracts/FeeableToken.sol#L60#L63

https://github.com/Gigzi/contracts/blob/0989f4a550ef8ae7110635784a96144d5578d7d1/contracts/FeeableToken.sol#L107#L125

### Recommendation

Use a simple mapping where an address will map to a boolean variable. this will considerably optimize transactions gas consumptions.
The functions `addReservedAccount` and `isFeeShouldBePaid` should be reimplemented as recommended.



# Revealing audit reports:

https://gist.github.com/yuriy77k/65cc60dd03e4d8353e3419744876c10d

https://gist.github.com/yuriy77k/22a7cc05f8d221e7109048efe1d37073

https://gist.github.com/yuriy77k/ed53bb4bc8cf32f42b6c2d9c42512f9f

**Comment by yuriy77k** [comment]
## @RideSolo

Notes regarding the https://gist.github.com/RideSolo/b888caf4b92fead9b2b7e1f9db8bbd9c report.

* Not [useless Extra Requirement](https://gist.github.com/yuriy77k/65cc60dd03e4d8353e3419744876c10d#33-useless-extra-requirement) - it will protect from incorrect values of ```feeMultiplier```, ```feeDivider```.

Your report is fine.



## @gorbunovperm

Notes regarding the https://gist.github.com/gorbunovperm/dd058a894876c9f8f4ef8ee31fd3d87b report.

Your report is fine.


## @alexo18

Notes regarding the https://gist.github.com/alexo18/9bfa17eb240886bc83a05677782a3e58 report.

Your report is fine.

**Comment by Gigzi** [comment]
thank you all very much for your time and efforts. to show our appreciation we have added a link to the community on our website www.gigzi.com
