### ISSUE TITLE
TemboCoin

### ISSUE THREAD

**Issue by yuriy77k** [EthereumCommonwealth/Auditing#103]
# Audit request

TemboCoin smart contract is based in the tourism industry, whereby users can pay for services offered by tourism companies in a given country.

# Source code

https://gist.github.com/yuriy77k/47c7f36eecdb3046c82f16f702443fc1

the same as https://etherscan.io/address/0x1de09690e0d3c75c22cd19acc1aebde46bbc7d25#code

# Disclosure policy

leon@tembocoin.io

# Platform

ETH

# Complexity

Low

**Comment by yuriy77k** [comment]
@MrCrambo assigned

**Comment by danbogd** [comment]
Auditing time: ~ 2 days.

**Comment by danbogd** [comment]
My audit report is finished.

**Comment by RideSolo** [comment]
Auditing time: 1 day

**Comment by yuriy77k** [comment]
@RideSolo assigned

**Comment by yuriy77k** [comment]
@MrCrambo @danbogd Notes about your report:

### The function `transferMultiple` is correct:

1. The function may call the only Owner, so he must know what he does and how much Gas it will cost.
2. If a length of `dests` and `values` arrays not equal it does not hurt the contract.
