### ISSUE TITLE
BNC token Audit 

### ISSUE THREAD

**Issue by bioniccoin** [EthereumCommonwealth/Auditing#11]
# Audit request

Bionic is an ethereum token that enables instant payments to anyone, anywhere in the world. Powerd by blockchain technology order to facilitate the financial transactions between electronic companies and simplify any purchase of electronic devices and softwares .

# Source code

Source code: https://github.com/bioniccoin/BNC

# Disclosure policy

Yes you can publish to notify me about it .
Email : dev@bionic-coin.io

# Platform

ETH

**Comment by bioniccoin** [comment]
Yes you can start audit

**Comment by yuriy77k** [comment]
@bioniccoin Our auditors team start audit after finished current one.

**Comment by bioniccoin** [comment]
Thank you

**Comment by MrCrambo** [comment]
Auditing time 2 days

**Comment by yuriy77k** [comment]
@MrCrambo assigned.

**Comment by gorbunovperm** [comment]
Estimated auditing time is 2 days.

**Comment by yuriy77k** [comment]
@gorbunovperm assigned.

**Comment by RideSolo** [comment]
Auditing time: 2 days

**Comment by yuriy77k** [comment]
@RideSolo assigned.

**Comment by alexo18** [comment]
Auditing time : 2 days

**Comment by yuriy77k** [comment]
@alexo18 assigned.

**Comment by gorbunovperm** [comment]
@yuriy77k My report is finished!

**Comment by yuriy77k** [comment]
# [BNC token](https://github.com/bioniccoin/BNC) security audit report performed by [Callisto Security Audit Department](https://github.com/EthereumCommonwealth/Auditing)

# 1. Conclusion:

No critical issue. This contract can be considered safe to be deployed. However, as highlighted users can accidentally send their tokens to 0x0 address.

# 2. Medium severity issues:

## 2.1. Token Transfer to Address 0x0

### Description

Bionic Token do not require the `to` address to be non null before `transfer`. Accidental token loss to address 0x0 can be applicable.

The version of ERC20 used in this contract, use a basic burn mechanism where anyone can send tokens to 0x0 address. However, this mechanism leads to the above mentioned issue.

### Code snippet

https://github.com/bioniccoin/BNC/blob/81ddaaa00ede373c6043cd9e06f9447b8c963959/Contracts/Bionic.sol#L146#L151

### Recommendation

Refer to ERC20 Standard implemented by OpenZepplin, to avoid this issue.


# 3. Low severity issue:

## 3.2. Known Issues of ERC20 Standard

### Description

ERC20 Tokens have some well-known issues (listed bellow), This is just a reminder for the contract developers.

- Approve + transferFrom mechanism allows double Withdrawal attack (as commented on the contract). 
- Lack of transaction handling.

The above mentioned issues are well documented, a basic search can help to get more information.

**Comment by yuriy77k** [comment]
# Revealing audit reports:

https://gist.github.com/yuriy77k/d06733e9196043ff49149938a3e2ee78

https://gist.github.com/yuriy77k/95e0bc2a0874f2bea2dceeda62081bb2

https://gist.github.com/alexo18/d72c25ea66c839b5df46edf914e8be7a

https://gist.github.com/yuriy77k/ba1ae8980622c0e5d7eb13400ac061b3



## @RideSolo

Notes regarding the https://gist.github.com/RideSolo/4863c3ab4668647199ecd283754e40c7 report.

Your report is fine.


## @gorbunovperm

Notes regarding the https://gist.github.com/gorbunovperm/eafd9f897fd76ba8ddf794582a80565c report.

Your report is fine.


## @alexo18

Notes regarding the https://gist.github.com/alexo18/d72c25ea66c839b5df46edf914e8be7a report.



## @MrCrambo 

Notes regarding the https://gist.github.com/MrCrambo/2a2249f8b9e5506aa7dcb1c1978609b1 report.

Your report is fine.
