### ISSUE TITLE
Enect

### ISSUE THREAD

**Issue by yuriy77k** [EthereumCommonwealth/Auditing#121]
# Audit request

Enect   collects and manages energy production/consumption information and aims to   develop the market necessary for healthy distribution and development through   big data analysis.     Measurement of energy production/consumption information is a key method to   achieve enect's goal. It is installed in each business, large commercial   facility, residential facility through enect enbox, and data collected by   energy info mining is kept in a transparent and safe manner by blockchain   technology. The collected data is stored as a blockchain technology that can   be accessed by anyone but cannot be modified by anyone and can only be   modified through a smart contract.     Enect collectively collects, operates and manages the large, unstructured   data collected and, as a result, provides necessary applications in the   current energy market through analysis.          enmarket     Enmarket is an eco-friendly solution distribution platform available to   both enbox users and non-users.     Enmarket proposes optimal products for customers who use enmarket; such as   sales price, sales volume, frequency of use, analysis of sales and etc.,   based on the production energy/energy info obtained through enbox.     Sellers will be able to manage brand, sales, and marketing value through   the enmarket data more clearly after identifying the market by analyzing   data. Management data on additional merchandise planning can be obtained, and   risks can be managed through data on market changes.      Sellers will be able to manage brand, sales, and marketing value through   the enmarket data more clearly after identifying the market by analyzing   data. Management data on additional merchandise planning can be obtained, and   risks can be managed through data on market changes.      Enmarket can be paid using both Cash and encoin; in the form of either   ‘cash AND encoin’ or ‘cash OR encoin ’. enect has a reward system for   ecosystem participants, through which encoin can buy real products and   services from the enmarket.          enreport     Enreport is a data sharing platform that provides value, based on data from   the enect ecosystem participants.     Enreport provides the best information through the enect big data based   analysis tool for energy production and user's environment-friendly   high-efficiency solution; and various types of equipment, consumables and   service necessary for operation management.     The energy info collected by enbox is divided into energy producers and   energy consumers. The collected data will be shared within the enreport   platform, sharing the range and grade of information provided by the energy   owner and the licensee. For example, data acquired through enreport allows   energy info licensees to gain the objectivity to upgrade new products,   facilities, and services to the needs of owners.     All data required by the licensee within the enreport can only be paid with   encoin, and the owner will also be entitled to redeem the encoin.          enmedia     Enmedia is a media channel that provides the most credible and highly   trustworthy information through enect big data based analysis to the enect   ecosystem participating companies/individuals. Based on all data collected   through enbox, enmarket and enreport can be deliver the most objective and   quick information to participants. Once desired information from enreport is   obtained through search, enmedia can basically show refined data and show the   information of the intended seller in the form of advertisement.     Enmedia will develop into a public journal of an eco-friendly ecosystem and   a media channel such as a global eco-friendly company chart and introducing   eco-friendly ecosystem information.     In addition, only encoin payments are accepted within the enmedia.

# Source code

https://gist.github.com/yuriy77k/3a798a1c944f55b7be61dc203e4fd234

deployed at https://etherscan.io/address/0x27ce70a584c085712cd42f20181237178ddc5a45#code

# Disclosure policy

contact@enect.io
Dobitrade

# Platform

ETH

# Complexity

Low

**Comment by MrCrambo** [comment]
Auditing time 1 day

**Comment by pro100skm** [comment]
Auditing time: 1 day

**Comment by gorbunovperm** [comment]
Estimated auditing time is 1 day.

**Comment by yuriy77k** [comment]
@MrCrambo @pro100skm @gorbunovperm assigned

**Comment by gorbunovperm** [comment]
My report is finished.

**Comment by yuriy77k** [comment]
# 1. Summary

[Enect](https://etherscan.io/address/0x27ce70a584c085712cd42f20181237178ddc5a45#code) security audit report performed by [Callisto Security Audit Department](https://github.com/EthereumCommonwealth/Auditing)

# 2. In scope

- [ENECT.sol](https://gist.github.com/yuriy77k/3a798a1c944f55b7be61dc203e4fd234#file-enect-sol)

# 3. Findings

In total, **5 issues** were reported including:

- 2 medium severity issues.

- 3 low severity issues.

No critical security issues were found.

## 3.1. Known vulnerabilities of ERC-20 token

### Severity: low

### Description

* It is possible to double withdrawal attack. More details [here](https://docs.google.com/document/d/1YLPtQxZu1UAvO9cZ1O2RPXBbT0mooh4DYKjA_jp-RLM/edit)
* Lack of transaction handling mechanism issue. [WARNING!](https://gist.github.com/Dexaran/ddb3e89fe64bf2e06ed15fbd5679bd20) This is a very common issue and it already caused millions of dollars losses for lots of token users! More details [here](https://docs.google.com/document/d/1Feh5sP6oQL1-1NHi-X1dbgT3ch2WdhbXRevDN681Jv4/edit)


## 3.2. The `acceptOwnership` function always returns `false`.

### Severity: low

### Description

This function is marked as `returns(bool)`, but doesn't have a `return` statement and always returns `false` by default. This can disrupt the work of a dApp.

### Code snippet

* https://gist.github.com/yuriy77k/3a798a1c944f55b7be61dc203e4fd234#file-enect-sol-L60

## 3.3. The owner can prohibit any user to transfer funds.

### Severity: medium

### Description

The owner or a hacker (if the owner's private key will be compromised) can freeze any user at any time, which will make it impossible to transfer funds. This is dangerous for investors and for exchanges too. 

### Code snippet

* https://gist.github.com/yuriy77k/3a798a1c944f55b7be61dc203e4fd234#file-enect-sol-L277

* https://gist.github.com/yuriy77k/3a798a1c944f55b7be61dc203e4fd234#file-enect-sol-L165

## 3.4. The owner can mint any value of tokens he wants.

### Severity: medium

### Code snippet

* https://gist.github.com/yuriy77k/3a798a1c944f55b7be61dc203e4fd234#file-enect-sol-L345

### Description

The owner or a hacker (if the owner's private key will be compromised) can mint any value of tokens he wants. The token can become worthless very quickly. This is dangerous for investors.

## 3.5. There is no transfer of funds when changing the owner.

### Severity: low

### Description

When a contract is created, the initial supply is on the owner's balance, but when the owner's rights are transferred to the new address, the supply is not transferred. Unallocated tokens will be on the balance of the previous owner.

### Code snippet

* https://gist.github.com/yuriy77k/3a798a1c944f55b7be61dc203e4fd234#file-enect-sol-L60

* https://gist.github.com/yuriy77k/3a798a1c944f55b7be61dc203e4fd234#file-enect-sol-L152

# 4. Conclusion

The contract contain some medium severity issues that need to be fixed.

# 5. Revealing audit reports

https://gist.github.com/yuriy77k/7bab15b17ce0202dd388328a6067e2ca

https://gist.github.com/yuriy77k/53ac3f90c5847a1845d9892467779462

https://gist.github.com/yuriy77k/88c7ba3c27f7041f9a5958068a10e57a

**Comment by yuriy77k** [comment]
@MrCrambo @pro100skm note about your report:

The function `releaseTimeLock` works correctly. [info.releaseTime](https://gist.github.com/yuriy77k/3a798a1c944f55b7be61dc203e4fd234#file-enect-sol-L379) contain a time when first `unlockAmountPerRound` will be released. Therefore it will release amount on 1 `unlockAmountPerRound` more then rounds number in `sinceRound`. After it new [`releaseTime`](https://gist.github.com/yuriy77k/3a798a1c944f55b7be61dc203e4fd234#file-enect-sol-L397) will be set on next round.
