### ISSUE TITLE
Global Funeral

### ISSUE THREAD

**Issue by yuriy77k** [EthereumCommonwealth/Auditing#127]
# Audit request

The smart contract is made to create our crowdsale token (GFCS). The crowdsale token will be swapped 1:1 for our own native currency on July 1, 2019.

# Source code

https://gist.github.com/yuriy77k/7519bccc21647bf57451cadb8bbf7288
deployed at https://etherscan.io/address/0x4f34adfff48ceb4af2f3b2253cdfdcc99c9053f4#code

# Disclosure policy

ceo@globalfuneralcare.org

# Platform

ETH

# Complexity

Low

**Comment by pro100skm** [comment]
Auditing time: 1 day

**Comment by RideSolo** [comment]
auditing time 1 day

**Comment by yuriy77k** [comment]
@RideSolo assigned.

**Comment by danbogd** [comment]
Auditing time: 7 days.

**Comment by yuriy77k** [comment]
@danbogd assigned

**Comment by danbogd** [comment]
My report is finished.
