### ISSUE TITLE
VANM token

### ISSUE THREAD

**Issue by yuriy77k** [EthereumCommonwealth/Auditing#133]
# Audit request

It's main purpose was/is...

• the creation of the VANM token (ERC20)
• handling our token sale in two phases including balance checks, overflow and whitelisting.

# Source code

https://github.com/VANMofficial/Token-Sale/blob/master/VANMToken.sol

# Disclosure policy

daniel.reuter@vanm.io

# Platform

ETH

# Complexity

Low

**Comment by yuriy77k** [comment]
@MrCrambo assigned

**Comment by danbogd** [comment]
Auditing time: ~ 2 days.

**Comment by yuriy77k** [comment]
@danbogd assigned

**Comment by gorbunovperm** [comment]
Estimated auditing time is 2 days.

**Comment by yuriy77k** [comment]
@gorbunovperm assigned

**Comment by gorbunovperm** [comment]
My report is finished.
