### ISSUE TITLE
ERA Token

### ISSUE THREAD

**Issue by yuriy77k** [EthereumCommonwealth/Auditing#134]
# Audit request

The ERA Token Smart contract

Motivation and Use Case

A fixed number of tokens will be created during the token sale, and no more will be generated after that. The functionalities of the token are beyond a speculative asset on an exchange.

We capped the Total Supply at 1,000,000,000.

Utility

Our  Token has various purposes beyond a speculative asset on an exchange, and this includes but is not limited to;

● Exchange Fees
● Transaction fees for remittance services
● Collateral on the lending platform
● Discount on fees
● Listing fees for the exchange
● Future exclusive services

We capped the total supply of our tokens at 1,000,000,000 and no more tokens shall be generated.

The ERA token is deployed on the Ethereum main net as an ERC223 token. The Token is a backward compatible ERC20 compliant Token.

Value Strategy

The value of the strategy of the ERA token is attractive as it features multiple mechanisms to stimulate its growth. ERA tokens can be used to settle any fees on our platform, including but not limited to:

Exchange fees Transaction fees Collateral on the lending platform Discount on fees Listing fees for the exchange Future exclusive services.

# Source code

https://github.com/etharemit/ETHA

# Disclosure policy

contact@etharemit.com

# Platform

ETH

# Complexity

Low

**Comment by MrCrambo** [comment]
Auditing time 1 day

**Comment by yuriy77k** [comment]
@MrCrambo assigned

**Comment by danbogd** [comment]
Auditing time: 1 day.

**Comment by gorbunovperm** [comment]
Estimated auditing time is 2 days.

**Comment by yuriy77k** [comment]
@gorbunovperm assigned.

**Comment by yuriy77k** [comment]
# 1. Summary

[ERA Token](https://github.com/etharemit/ETHA) smart contract security audit report performed by [Callisto Security Audit Department](https://github.com/EthereumCommonwealth/Auditing)

# 2. In scope

- [erc223Ownable.sol](https://github.com/etharemit/ETHA/blob/master/erc223Ownable.sol) github commit hash 6f81fa015f1a9fc6065f9ad1788835d4a3a55852.

# 3. Findings

In total, **1 issues** were reported including:

- 1 medium severity issues.

## 3.1. ERC223 Standard Compliance.

### Severity: medium

### Description

The reviewed token contract is not ERC223 fully compliant.

1. The function `transfer(address _to, uint _value, bytes _data)` call tokenFallback external function on the receiver contract before adding the value to balances[_to]. The original implementation adds the token value to the balance before making the external call (check the link below).
https://github.com/Dexaran/ERC223-token-standard/blob/master/token/ERC223/ERC223_token.sol#L63#L68

2. The function `transfer(address _to, uint256 _value)` didn't call tokenFallback external function on the receiver contract at all.

### Code snippet

https://github.com/etharemit/ETHA/blob/6f81fa015f1a9fc6065f9ad1788835d4a3a55852/erc223Ownable.sol#L198

https://github.com/etharemit/ETHA/blob/6f81fa015f1a9fc6065f9ad1788835d4a3a55852/erc223Ownable.sol#L142

### Recommendation

Use sample from [Dexarans' ERC223 token description](https://github.com/Dexaran/ERC223-token-standard).

# 4. Conclusion

Smart contract has medium severity issues, please fix it before deploying.

# 5. Revealing audit reports

https://gist.github.com/yuriy77k/894003aad43bc45d7a868769189f4f89

https://gist.github.com/yuriy77k/687fc19c9d8c7b251fff5b281559bcd3

https://gist.github.com/yuriy77k/1f183fc700224dbd2041a4c161634bef
