### ISSUE TITLE
ERA Token v2.

### ISSUE THREAD

**Issue by yuriy77k** [EthereumCommonwealth/Auditing#143]
# Audit request

ETHA ETHA introduces the world’s first blockchain-based remittance solution platform that will allow merchants and consumers to utilise their digital assets to send fiat money globally. The remittance solution platform will be the first of its kind to facilitate crypto to fiat transfer. Users will be able to send fiat money utilising digital currencies by allowing the sender the flexibility to select different payout options for the recipient, such as Direct to Bank, Local (Cash) Pick-Up or Mobile Top Up. We aim to support sending money to over 190 countries around the world. Official Links: https://etharemit.org/ https://t.me/etharemit https://twitter.com/etharemit https://www.facebook.com/etharemit/ https://medium.com/etharemit https://www.reddit.com/user/ETHAREMIT The ETHA payment infrastructure works as a decentralised operating system, which integrates decentralised with centralised resources under one ecosystem, enabling fiat transfer with digital currencies. The ERA Token Motivation and Use Case A fixed number of tokens will be created during the token sale, and no more will be generated after that. The functionalities of the token are beyond a speculative asset on an exchange. Utility The ERA token’s primary purpose is to settle fees that occur while using any of our financial services such as remittance service, cross-border financing, decentralized lending and the exchange. Value Strategy The value of the strategy of the ERA token is attractive as it features multiple mechanisms to stimulate its growth. ERA tokens can be used to settle any fees on our platform, including but not limited to: Exchange fees Transaction fees Collateral on the lending platform Discount on fees Listing fees for the exchange Future exclusive services Implementation The ERA token is deployed on the Ethereum main net as an ERC223 token. The tokens are ERC20 compatible. We added it to the Ropsten test network before deploying it to the live network. Besides us checking out the code with regards to the previous audit conducted by Callisto. So based on your report we I did all the changes needed and need an audit please. 

The Token contract provided is an updated version of a previous audit Callisto conducted 
https://github.com/EthereumCommonwealth/Auditing/issues/134

# Source code

https://github.com/etharemit/ETHA/blob/master/erc223audited.sol

# Disclosure policy

 contact@etharemit.com

# Platform

ETH

# Complexity

Low

**Comment by yuriy77k** [comment]
@gorbunovperm @MrCrambo @danbogd assigned.

**Comment by gorbunovperm** [comment]
My report is finished.

**Comment by yuriy77k** [comment]
# 1. Summary

[ERA Token](https://github.com/etharemit/ETHA/blob/master/erc223audited.sol) smart contract security audit report performed by [Callisto Security Audit Department](https://github.com/EthereumCommonwealth/Auditing)

> A fixed number of tokens will be created during the token sale, and no more will be generated after that. The functionalities of the token are beyond a speculative asset on an exchange.

# 2. In scope

Commit hash: `b0dc80c845002d65d6291331049628d96da5e87e`

1. [erc223audited.sol](https://github.com/etharemit/ETHA/blob/b0dc80c845002d65d6291331049628d96da5e87e/erc223audited.sol)

# 3. Findings

In total, **1 issues** were reported including:

- 1 medium severity issues.

No critical security issues were found.

## 3.1. ERC223 standard compliance.

### Severity: medium

### Description

The function `transfer(address _to, uint256 _value)` didn't call `tokenFallback` external function on the receiver contract at all.

### Code snippet

* [erc223audited.sol](https://github.com/etharemit/ETHA/blob/b0dc80c845002d65d6291331049628d96da5e87e/erc223audited.sol#L152)

### Recommendation

Add a `tokenFallback` function call to `transfer(address _to, uint256 _value)` function. (Look at sample from [Dexarans' ERC223 token description](https://github.com/Dexaran/ERC223-token-standard).)

# 4. Conclusion

Smart contract has medium severity issue, please fix it before deploying.

# 5. Revealing audit reports

https://gist.github.com/yuriy77k/326961a7e1e89eec21c37a7b7e4bf37b

https://gist.github.com/yuriy77k/c8643e99c0da2f61472e5e4463921f66

https://gist.github.com/yuriy77k/3f10b682e92783cfb3352a0afccbbf4a
