### ISSUE TITLE
Audit Tradelize

### ISSUE THREAD

**Issue by AmirSlavo** [EthereumCommonwealth/Auditing#16]
# Audit request

Hello! I'm going to invest in this project http://tradelize.com, but I want to be sure of the security of this token. Be sure to publish the result publicly. This is important for all investors.

# Source code

[Source code Link](https://etherscan.io/address/0xa9cb61189803659553b5d025dce93fb43814c917#code)

# Disclosure policy

amiroslavo@mail.ru

# Platform

ETH

**Comment by yuriy77k** [comment]
Our audit service is for a smart contracts developers, not for third party investors.

**Comment by AmirSlavo** [comment]
@yuriy77k   How "reasonable"! It seems to me that in your team only programmers)) I sympathize with the holders of your coin.

**Comment by yuriy77k** [comment]
If you interesting in audit this project http://tradelize.com you can ask their team to make request for our free audit. If it's not a scam they will agree, in other way no audit needed.

**Comment by Methw** [comment]
@AmirSlavo have you contacted the team and get this answer?

**Comment by AmirSlavo** [comment]
@Methw Tell me. Why should I knock on closed doors if I can buy a CLO and conduct an audit here? Why do you refuse most of your potential customers by closing access to your service?

**Comment by Methw** [comment]
@AmirSlavo then, my advice is not following ICO that you not fully trust, especially not trusting the developer.

**Comment by AmirSlavo** [comment]
@Methw I need an audit, but not your advice. I do not know who you are.
When developers start accepting a CLO deposit for speeding up the audit, how will they separate customers? It seems that they should know the logic, by virtue of their profession!
