### ISSUE TITLE
dreampot

### ISSUE THREAD

**Issue by MillianoConti** [EthereumCommonwealth/Auditing#160]
# Audit request

Dream Pot is an online decentralized lottery, based on the blockchain technology. The whole process is managed by a smart contract without anyhuman factor involved.

# Source code

https://github.com/dreampot-team/MainLottery/tree/master/contracts

# Disclosure policy

support@dreampot.io

# Platform

ETH

# Complexity

High

**Comment by MrCrambo** [comment]
Auditing time 5 days

**Comment by yuriy77k** [comment]
@MillianoConti I have no response from support@dreampot.io
Please, check email.

**Comment by yuriy77k** [comment]
Callisto Network provides security audits free of charge for smart-contract developers and development teams. And by our disclosure policy, we need to inform developers about found issues. Therefore we have to contact with them.

As far as we didn't receive confirmation from smart contract developer team, the request has to be closed.
