### ISSUE TITLE
Resource delegator

### ISSUE THREAD

**Issue by Dexaran** [EthereumCommonwealth/Auditing#166]
### WARNING! This is an example audit request. The main purpose of this audit request is to provide an example of the workflow of the security audit department for new entrants to the position of security auditor.

# Audit request

Resource delegator is a simple smart-contract which stakes the desired amount of EOS for caller's CPU or NET for 2 minutes. A user can not request more than 0,1 EOS (for both `NET` and `CPU` in total). The contract is intended to work with a total balance of 0,1 EOS on its balance. Contract must only allow one request at a time, i.e. if a user has requested resources then the contract must not accept other requests unless it has successfully completed the current request. The contract must preserve the name of a user whose request is currently in progress in a special multi-index table.

Account ownership restriction issues must not be taken into account during this security audit.

# Source code

https://github.com/EthereumCommonwealth/EOS-resource-delegator/tree/master/src

# Disclosure policy

Publish everything

# Platform

EOS

**Comment by gorbunovperm** [comment]
Estimated auditing time is 7 days.

**Comment by Dexaran** [comment]
@gorbunovperm assigned.

**Comment by cryptoabhi** [comment]
Estimated time to complete the audit - 4 days.

**Comment by Dexaran** [comment]
@cryptoabhi assigned.

**Comment by cryptoabhi** [comment]
I have completed and submitted the audit report
