### ISSUE TITLE
FCK

### ISSUE THREAD

**Issue by MillianoConti** [EthereumCommonwealth/Auditing#167]
# Audit request

FCK is a decentralized game platform based on the blockchain technology, with fairness, equality, transparency, openness and complete anonymousness.

# Source code

https://github.com/FCKOfficial/FCK-contracts/tree/master/dice

# Disclosure policy

fckteamwork@gmail.com

# Platform

ETH

# Number of lines: 
252

**Comment by gorbunovperm** [comment]
Estimated auditing time is 3 days.

**Comment by yuriy77k** [comment]
@gorbunovperm assigned

**Comment by RideSolo** [comment]
Auditing time: 2 days.

**Comment by yuriy77k** [comment]
@RideSolo assigned

**Comment by MrCrambo** [comment]
Auditing time 2 days

**Comment by yuriy77k** [comment]
@MrCrambo assigned

**Comment by RideSolo** [comment]
Hello @MillianoConti, can we get a link to the project whitepaper. many essential part of the code are described in the whitepaper and it is needed for the audit.

**Comment by dice2-win** [comment]
Please take note of the following facts:
 - The smart contract in question is almost a direct copy of the https://dice2.win smart contract, available [here](https://github.com/dice2-win/contracts), with major changes being:
     1. removing _any_ mentions of original authorship from the comments (while keeping the remaining wording intact)
     2. removing the Merkle proof settlement, which solves rerolls on chain reorganization - a problem which existence is not admitted by FCK team.
 - Removing copyrights is a **direct** violation of the MIT license, under which dice2.win is open sourced
 - The FCK contract mentions some "whitepaper", which doesn't exist, because we were too lazy to finish it :)
 - FCK.com has a history of running unverified smart contracts on the Ethereum mainnet, which, either malevolently or out of incompetence, resulted in a loss of users funds
 - FCK.com has a history of running botted account rings, which are pretty evident on Etherscan, to fake DAU & volume numbers on dApp aggregator sites - by independent accounts, it seems quite probable that up to 90% of FCK traffic is fake
 - It is very likely that the primary goal of FCK ordering this audit is not user security, but lifting its credibility for the unsuspecting visitor, for free. 

 We would be grateful to EthereumCommonwealth team if all of the above facts are mentioned in the audit.

**Comment by RideSolo** [comment]
@dice2-win Thank you for the info, first I can see that your repository is older than FCK.

**Comment by dice2-win** [comment]
> @dice2-win Thank you for the info, first I can see that your repository is older than FCK.
> also how did you know about this audit, did you see my messages in FCK telegram group ?

Unfortunately that's not possible, because our account is permabanned there since group inception for pointing out to the aforementioned facts ;) We just Google routinely for our clones (either in design or contract code), as FCK is not the only one in existence.

**Comment by gorbunovperm** [comment]
My report is finished.

**Comment by RideSolo** [comment]
report submitted.

**Comment by yuriy77k** [comment]
# FCK Security Audit Report

# 1. Summary

[FCK](https://github.com/FCKOfficial/FCK-contracts/) smart contract security audit report performed by [Callisto Security Audit Department](https://github.com/EthereumCommonwealth/Auditing)

# 2. In scope

Commit hash: `a7fd48b135db2f4828cbc8e5e694b4a9627cd323`

1. [fck.com Sol](https://github.com/FCKOfficial/FCK-contracts/blob/a7fd48b135db2f4828cbc8e5e694b4a9627cd323/dice/fck.com%20Sol)

# 3. Findings

In total, **4 issues** were reported including:

- 2 low severity issues.

- 1 notes.

- 1 owner privileges (the ability of an owner to manipulate contract, may be risky for investors).

No critical security issues were found.

## 3.1. Fallback Function

### Severity: low

### Description

The fallback function allows anyone to deposit ether to the contract, only addresses intended to deposit tokens should be allowed to deposit.

### Code snippet

https://github.com/RideSolo/FCK-contracts/blob/master/dice/fck.com%20Sol#L139

## 3.2. Kill Function

### Severity: notes

### Description

Once `kill` function called, all payables function should be blocked including the fallback function.

### Code snippet

https://github.com/RideSolo/FCK-contracts/blob/master/dice/fck.com%20Sol#L191

## 3.3. The croupier delay

### Severity:  owner privileges

### Description

The bet will not be played if the croupier does not call `settleBet` function within an hour(250 blocks) of betting. The croupier is a server-side mechanism. And if there are problems with the server - the work of the dealer will stop. Players can lose their bets.

Also, this restriction can be used by the contract owner maliciously, for example, when the user can win the jackpot or makes a very large bet and it can become a winning one.

### Code snippet

* [BET_EXPIRATION_BLOCKS](https://github.com/FCKOfficial/FCK-contracts/blob/a7fd48b135db2f4828cbc8e5e694b4a9627cd323/dice/fck.com%20Sol#L344)

## 3.4. Zero address checking required

### Severity: low

### Description

In `constructor`, `setCroupier`, `setSecretSigner` and `sendFunds` there are zero address checking required.

### Code snippet

https://github.com/FCKOfficial/FCK-contracts/blob/master/dice/fck.com%20Sol#L113

https://github.com/FCKOfficial/FCK-contracts/blob/master/dice/fck.com%20Sol#L165

https://github.com/FCKOfficial/FCK-contracts/blob/master/dice/fck.com%20Sol#L160

https://github.com/FCKOfficial/FCK-contracts/blob/master/dice/fck.com%20Sol#L469

# 4. Conclusion

The audited smart contract can be deployed. Only low severity issues were found during the audit.

# 5. Revealing audit reports

https://gist.github.com/yuriy77k/316d0183bf8686bb63e56a95da31f1ef

https://gist.github.com/yuriy77k/6ae298c8327d9d3cb284df055956f7b7

https://gist.github.com/yuriy77k/c43197dab70c1856d949cda36398bb8a
