### ISSUE TITLE
Ethereum Limited

### ISSUE THREAD

**Issue by GenadiyKotov** [EthereumCommonwealth/Auditing#17]
# Audit request

Here's the project. Too bright and defiantly decorated. I think it should be checked. https://bitcointalk.org/index.php?topic=4521586.0 If it is bad, then I will post a message in their subject and you, therefore, will help inexperienced investors.

# Source code

https://etherscan.io/address/0x813a823f35132d822708124e01759c565ab4331d#code

# Disclosure policy

kotov.dolbinerealmni@gmail.com

# Platform

ETH

**Comment by yuriy77k** [comment]
Our audit service is for a smart contracts developers, not for third party investors.

**Comment by GenadiyKotov** [comment]
@yuriy77k  I still do not find in the article direct instructions that the audit is conducted only for developers.

**Comment by bokel1** [comment]
@GenadiyKotov You should rather ask the devs of this project about Callisto SC audit and make it public.
