### ISSUE TITLE
Brain Space ICO

### ISSUE THREAD

**Issue by yuriy77k** [EthereumCommonwealth/Auditing#170]
# Audit request

Hello, I am the Chief Technology Officer of the IMPERIVM LLC company. We need an audit of our smart contract token (ERC-20) which is currently actively used. Interested in the price of the audit and the audit period in the first place.
Need audit of smart contract - IMPERIVMCoin and its dependencies.

# Source code

https://github.com/IMPERIVM-TEAM/BrainSpace-ICO-Smart-Contracts

# Disclosure policy

opensource@imperivm.world

# Platform

ETH

# Complexity

Mid-low

**Comment by MrCrambo** [comment]
Auditing time 1 day

**Comment by danbogd** [comment]
Auditing time: ~ 3 days.

**Comment by yuriy77k** [comment]
@MrCrambo @danbogd assigned

**Comment by danbogd** [comment]
My report is finished.

**Comment by RideSolo** [comment]
Auditing time: 2 days

**Comment by yuriy77k** [comment]
@RideSolo assigned

**Comment by yuriy77k** [comment]
The contract contains high severity security issues. The developer informed about it.
