### ISSUE TITLE
Auditchain Token v.2.

### ISSUE THREAD

**Issue by yuriy77k** [EthereumCommonwealth/Auditing#173]
# Audit request

Burnable
Mintable
Pausable
No Cap
Issuing yearly 12,500,000 new tokens to governance contract
With ability to be migrated to new contract in the future
With ability to lock and unlock ERC20 functions of Token based on user address
With ability to refuse to accept tokens sent to this contract by mistake

Token Name

"Auditchain"

Token Ticker

"AUDT"

Number of decimals

18

Initial Supply

250,000,000 + 12,500,000
Example of verified contract can be seen on ropsten testnet

# Source code

https://github.com/Vestcomp/TGE

# Disclosure policy

jm@auditchain.com

bogdanfiedur@gmail.com

# Platform

ETH

# Complexity

Low

**Comment by yuriy77k** [comment]
Have to check fixes of previously found issues.

**Comment by MrCrambo** [comment]
Auditing time 1 day.

**Comment by RideSolo** [comment]
Auditing time: 1 day.

**Comment by gorbunovperm** [comment]
Estimated auditing time is 1 day.

**Comment by gorbunovperm** [comment]
My report is finished.

**Comment by yuriy77k** [comment]
Auditors, please note, the following issues are not present:

## 3.1. Known vulnerabilities of ERC-20 token
### *1. It is possible to double withdrawal attack. More details here.*

Openzepplin contracts provide two additional functions within ERC20 token. 
```
increaseAllowance
decreaseAllowance
```
These two function entirely take care of mentioned attack vector. 
Function approve could be still varunable, but user has choice of using two above functions instead. 
Since auditor proposes to overload approve function with different number of parameters, this is similar to calling different function as the end result and leaving existing approve available and varunable. 
Removing original approve would result in breaking of protocol. 

Both functions increaseAllowance decreaseAllowance accomplish similar tasks and they are already used in various tokens since 2017 and are part of OpenZepplin libraries. 

### 2. Lack of transaction handling mechanism issue. 

The contract has modifier called notSelf, which accomplishes these exact task. 
```
    /// @dev prevent accidental sending of tokens to this token contract
    /// @param _self - address of this contract
    modifier notSelf(address _self) {
        require(_self != address(this), "You are trying to send tokens to token contract");
        _;
    }
```

## 3.2. Missing event call. 
*In the constructor is no events on the transfer of funds.*

[`_mint`](https://github.com/Vestcomp/TGE/blob/1a6ccfb06b540d69101a82fef46b9170aa112f2d/flat/Token.sol#L402) function in ERC20.sol calls Transfer event.

**Comment by yuriy77k** [comment]
@MrCrambo @RideSolo @gorbunovperm assigned

**Comment by yuriy77k** [comment]
# 1. Summary

[Auditchain Token](https://github.com/Vestcomp/TGE) smart contract security audit report performed by [Callisto Security Audit Department](https://github.com/EthereumCommonwealth/Auditing)

https://auditchain.com/

# 2. In scope

Commit hash: `1a6ccfb06b540d69101a82fef46b9170aa112f2d`.

1. [Locked.sol](https://github.com/Vestcomp/TGE/blob/1a6ccfb06b540d69101a82fef46b9170aa112f2d/contracts/Locked.sol)
2. [MigrationAgent.sol](https://github.com/Vestcomp/TGE/blob/1a6ccfb06b540d69101a82fef46b9170aa112f2d/contracts/MigrationAgent.sol)
3. [Migrations.sol](https://github.com/Vestcomp/TGE/blob/1a6ccfb06b540d69101a82fef46b9170aa112f2d/contracts/Migrations.sol)
4. [Token.sol](https://github.com/Vestcomp/TGE/blob/1a6ccfb06b540d69101a82fef46b9170aa112f2d/contracts/Token.sol)

# 3. Findings

In total, **2 issues** were reported including:

- 1 low severity issues.

- 1 minor observation.

No critical security issues were found.

## 3.1. Owners privileges

### Severity: low

### Description

The owners privileges:

* Ability to be migrated to new contract in the future (new contract may be not audited)

* Ability to lock and unlock ERC20 functions of Token based on user address

### Code snippet

https://github.com/Vestcomp/TGE/blob/1a6ccfb06b540d69101a82fef46b9170aa112f2d/contracts/Token.sol#L79

https://github.com/Vestcomp/TGE/blob/1a6ccfb06b540d69101a82fef46b9170aa112f2d/contracts/Token.sol#L104

## 3.2. Date related issues

### Severity: minor observation

### Description

It is about

> Issuing yearly 12,500,000 new tokens to governance contract

1. In this contract, the year is determined by dividing the number of seconds since the beginning of the Unix Epoch by the number of seconds in a leap year. In this case `06.02.2019 11:59pm` is 2018 year by `returnYear()` function. And `07.02.2019 12:00am` is 2019 year.

2. If the contract is deployed on February 6 the owner will receive 12'500'000 tokens. And the next day he can call `mint()` and get another 12'500'000 tokens because the contract will consider that the next year has come.

### Code snippet

https://github.com/Vestcomp/TGE/blob/1a6ccfb06b540d69101a82fef46b9170aa112f2d/contracts/Token.sol#L52

### Recommendation

Just save the timestamp of first payment and add to it year value in seconds to figure out if next payment date is come. And then update the date of the last payment.

# 4. Conclusion

The review of Auditchain Token smart contract did not show any critical issues and is safe for deploy. We pointed out some observations about the owner's rights and calculation of dates.

# 5. Revealing audit reports

https://gist.github.com/yuriy77k/c73a1cdd30f45bd418325b1d08a3c79a

https://gist.github.com/yuriy77k/1cddf1ecdcde98f3a0bb5ba04d9053b2
