### ISSUE TITLE
DevToothCrew

### ISSUE THREAD

**Issue by MillianoConti** [EthereumCommonwealth/Auditing#185]
# Audit request
Unlimited Tower is a new blockchain battle SRPG Dapp that lets you form and upgrade your party consisted of
unique monsters and servants.
https://www.unlimitedtower.com/?utm_source=DappRadar&utm_content=visit-website

# Source code

https://github.com/DevToothCrew/DevTooth_NFT_Tokens

# Disclosure policy

Public report

# Platform

EOS

**Comment by Dexaran** [comment]
This contract is written in EOS 1.3 syntax which is deprecated now.
Let's focus on contracts that are written in syntax which is actual for the current moment.

**Comment by Dexaran** [comment]
This contract is written in EOS 1.3 syntax which is deprecated now.
Let's focus on contracts that are written in syntax which is actual for the current moment.

**Comment by Dexaran** [comment]
@MillianoConti @yuriy77k 

[This](https://github.com/DevToothCrew/DevTooth_NFT_Tokens/blob/master/devtooth_nft.hpp#L11) declaration indicates that the contract is written in old syntax 

```cpp
    class devtooth_nft : public contract {
```

In up to date contracts the declaration of contract class will look as follows:

```cpp
   class [[eosio::contract("devtooth_nft")]] tokens : public contract {
```

Where `devtooth_nft`  is the name of the file that contain the actual code. Let's focus at up to date contracts for now.
