### ISSUE TITLE
hirevibes

### ISSUE THREAD

**Issue by MillianoConti** [EthereumCommonwealth/Auditing#186]
# Audit request
HireVibes connects jobseekers, employers, referrers and recruiters on a new job search platform (Dapp) based on the EOS blockchain.
https://www.hirevibes.io/
# Source code

https://github.com/hirevibes/token

# Disclosure policy

public report

# Platform

EOS

**Comment by Dexaran** [comment]
EOSIO standard token

**Comment by cryptoabhi** [comment]
Estimated audit time 4 days

**Comment by Dexaran** [comment]
@cryptoabhi assigned

**Comment by cryptoabhi** [comment]
Audited and submitted my report. Delayed audit due to the use of deprecated libraries in the contract (which most tools don't support).
