### ISSUE TITLE
ELIXIR-ELIXOR AUDIT

### ISSUE THREAD

**Issue by elizarov7** [EthereumCommonwealth/Auditing#19]
# Audit request

I've long wanted to test this smart contract https://bitcointalk.org/index.php?topic=2195735.0

1. Can the creator create EXOR and ELIX at will?
2. Can the creator pick up EXOR and ELIX from the addresses of the holders at will?
3. Can the creator create new address genesis?

# Source code

[Source code Link ELIXIR](https://etherscan.io/address/0xc8C6A31A4A806d3710A7B38b7B296D2fABCCDBA8#code)
[Source code Link ELIXOR](https://etherscan.io/address/0x898bF39cd67658bd63577fB00A2A3571dAecbC53#code)

# Disclosure policy

nik.elizarov.1998@inbox.ru

# Platform

ETH

**Comment by yuriy77k** [comment]
Our audit service is for a smart contracts developers, not for third party investors.

**Comment by elizarov7** [comment]
@yuriy77k I bought a CLO on a deposit, in order to speed up the audit. So I do not need CLO now and I have to sell them cheaply? I bought a coin a month ago and they were much more expensive, compared to today's price!
Discrimination is. I have to sue you in court.
P.S. I will wait until you determine the jurisdiction of the project.

**Comment by elizarov7** [comment]
https://github.com/elizarov7/poison
