### ISSUE TITLE
Nemolab

### ISSUE THREAD

**Issue by yuriy77k** [EthereumCommonwealth/Auditing#190]
# Audit request

Unfortunately, our website is not supported English yet. we are startup and we are building a new website.
Website: http://nemolab.kr/
To help your understanding, I attached our white paper.

Here's brief information about contract

====================================================

Outline

'Nemodax' is a sort of data market between person to person. and 'Nemo' Coin(Provisional name) is kind of a way to pay.

It's proxy pattern contracts.

It was designed to deal with Ethereum secure issues, service usability issues considered future scalability. 

There will be two contracts on ethereum mainnet. It's ProxyNemodax and TokenExchanger.

We're in the phase of pre-launch, and We haven't ICO or IEO yet.

Inheritance relation

Ownerable <- Pausable <- RunningConctractManager <- TokenERC20 <- TokenExchanger

Ownerable <- Pausable <- RunningContracttManager <- NemodaxStorage <- ProxyNemodax

Function of Contracts

1. ProxyNemodax

  ProxyNemodax is just proxy contract refering to 'implementation' variable to forward requests to TokenExchanger.

  Real data(included assets) is stored in ProxyNemodax variables.

2. TokenExchanger

 We're gonna launch the 'Nemodax' Service before being listed on. So Something must be able to exchange the Nemo coin. 

Owner charges some 'ETH' and 'Nemo' to TokenExchanger and User(or Web Server) requests exchanging via ProxyNemodax contract.

3. TokenERC20

 It's ERC20 contract from open-zeppelin. it is inherited by TokenExchanger. 

 TokenExchanger uses TokenERC20 functions.

# Source code

https://github.com/nemolab-project/nemodax-erc20/blob/master/upgradable_TokenExchanger.sol

# Disclosure policy

hapsody@gmail.com

# Platform

ETH

# Number of lines

270

**Comment by MrCrambo** [comment]
Auditing time 2 days.

**Comment by yuriy77k** [comment]
@MrCrambo assigned

**Comment by hapsody** [comment]
Hello. 
To help the one who audit this code, I link it's white paper here.
[http://www.nemodax.com/doc/NEMODaX_White_Paper_ver.1.0_ENG.pdf](url)

Please feel free to contact me if you have any question.
hapsody@gmail.com
neojune@nemolab.kr

**Comment by gorbunovperm** [comment]
Estimated auditing time is 2 days.

**Comment by danbogd** [comment]
Auditing time 2 days.

**Comment by yuriy77k** [comment]
@gorbunovperm @danbogd assigned

**Comment by yuriy77k** [comment]
@gorbunovperm @danbogd assigned

**Comment by danbogd** [comment]
My report is finished.

**Comment by hapsody** [comment]
Thank you for your effort danbogd. 
Where can I get your report by any chance?

**Comment by danbogd** [comment]
You can get the summary report only from the Head of Security Department - Yuriy Kharytoshyn.

**Comment by hapsody** [comment]
Okay, then I should wait report from Head of Security Department. am I right?

**Comment by gorbunovperm** [comment]
My report is finished.

**Comment by gorbunovperm** [comment]
> Okay, then I should wait report from Head of Security Department. am I right?

Right.

**Comment by yuriy77k** [comment]
# Security Audit Report

# 1. Summary

[Nemolab](https://github.com/nemolab-project/nemodax-erc20/blob/master/upgradable_TokenExchanger.sol) smart contract security audit report performed by [Callisto Security Audit Department](https://github.com/EthereumCommonwealth/Auditing)

# 2. In scope

Commit hash 63dc1650051d1f2e4d4a8a01a05ea3af1b9bebe8.

- [upgradable_TokenExchanger.sol](https://github.com/nemolab-project/nemodax-erc20/blob/master/upgradable_TokenExchanger.sol).

# 3. Findings

In total, **7 issues** were reported including:

- 3 medium severity issues.

- 4 low severity issues.

No critical security issues were found.

## 3.1. Known vulnerabilities of ERC-20 token

### Severity: low

### Description

1. It is possible to double withdrawal attack. More details [here](https://docs.google.com/document/d/1YLPtQxZu1UAvO9cZ1O2RPXBbT0mooh4DYKjA_jp-RLM/edit).

2. Lack of transaction handling mechanism issue. [WARNING!](https://gist.github.com/Dexaran/ddb3e89fe64bf2e06ed15fbd5679bd20)  This is a very common issue and it already caused millions of dollars losses for lots of token users! More details [here](https://docs.google.com/document/d/1Feh5sP6oQL1-1NHi-X1dbgT3ch2WdhbXRevDN681Jv4/edit).

### Recommendation

Add the following code to the `transfer(_to address, ...)` function:

```
require( _to != address(this) );

```
## 3.2. RunningConctractManager is vulnerable to function selector clashing

### Severity: medium

### Description

This implements upgradable contracts based on forwarding messages to an implementation contract using **DELEGATECALL**.This forwarding logic is implemented in the [Proxy’s fallback function](https://github.com/nemolab-project/nemodax-erc20/blob/master/upgradable_TokenExchanger.sol#L632), which is only called if the current message's data doesn't start with one of the Proxy's functions' selectors. This means that if the selector of one of the implementation's functions clashes with one of the Proxy's, the latter will take precedence and the message will not be forwarded. This behavior can possibly break contracts.

### Code snippet

https://github.com/nemolab-project/nemodax-erc20/blob/master/upgradable_TokenExchanger.sol#L632

## 3.3. Owner can freeze any address

### Severity: medium

### Description

`FreezeAccount` function allow the contract owner to freeze any address and disable the transfer of the contained token value of that address.

### Code snippet

https://github.com/nemolab-project/nemodax-erc20/blob/63dc1650051d1f2e4d4a8a01a05ea3af1b9bebe8/upgradable_TokenExchanger.sol#L444

https://github.com/nemolab-project/nemodax-erc20/blob/63dc1650051d1f2e4d4a8a01a05ea3af1b9bebe8/upgradable_TokenExchanger.sol#L451

## 3.4. `initExchanger` function can be called multiple times

### Severity: medium

### Description

The owner can call `initExchanger` function not only once and this will change the total supply and balance of the owner to any value (`initialSupply` parameter).

### Code snippet

https://github.com/nemolab-project/nemodax-erc20/blob/63dc1650051d1f2e4d4a8a01a05ea3af1b9bebe8/upgradable_TokenExchanger.sol#L484

### Recommendation

Check if this function was also called.

## 3.5. No check to the zero address.

### Severity: low

### Description

1. Possibility of setting zero address as `newOwner` at `transferOwnership` function.

2. There is no zero address check at function `upgrade`.

### Code snippet

https://github.com/nemolab-project/nemodax-erc20/blob/63dc1650051d1f2e4d4a8a01a05ea3af1b9bebe8/upgradable_TokenExchanger.sol#L165

https://github.com/nemolab-project/nemodax-erc20/blob/63dc1650051d1f2e4d4a8a01a05ea3af1b9bebe8/upgradable_TokenExchanger.sol#L214

## 3.6. Owner Privileges

### Severity: low

### Description

The contract owner allow himself to:

- set any ExchangeRate;
- destroy tokens;
- withdraw tokens and ether.

The contract is managed manually by the owner which is not good for investors.

## 3.7. The relocating is not secure process for investors.

### Severity: low

### Description

The owners can implement any logic in the new contract. And even if the new contract will be audited, at any time possible to change the address of the new contract again to not audited and insecure.

### Code snippet

https://github.com/nemolab-project/nemodax-erc20/blob/63dc1650051d1f2e4d4a8a01a05ea3af1b9bebe8/upgradable_TokenExchanger.sol#L214

# 4. Conclusion

The audited smart contract must not be deployed. Reported issues must be fixed prior to the usage of this contract.

# 5. Revealing audit reports

https://gist.github.com/yuriy77k/461abda3e82305bc12c8bf2d92fb093e

https://gist.github.com/yuriy77k/b368f7dc356abe99943b5764a8a3801d

https://gist.github.com/yuriy77k/8b5ea8dd76af5a430125c096714f7525

**Comment by hapsody** [comment]
**First, I'm very thank for your effort** 

I read all the report and some of the issues is fixed right away(3.1, 3.3, 3.4, 3.5)
but I wanna ask you if the others will be able to make as an exception.(3.2, 3.6, 3.7)

**3.2 issue(related to RunningContractManager)**
I think I know what exactly point you're worried about.
But In this case, The thing which is possible to clash with is only "upgrade" and "runningAddress" functions in RunningContractManager inherited by ProxyNemodax, am I correct?
And "upgrade" and "runningAddress" functions both will be used only when ProxyNemodax contract is upgraded. so I thought there's no case to make a problem.
If I got a wrong point, please tell me.

**3.6 issue(related to Owner Privileges)**

**- set any ExchangeRate;**
We're gonna launch a service to ordinary users without listing on exchanges or ICO. so we need to provide our coins to users. I'll make this with ETH and This needs exchange rate whatever kind of it is.

**- destroy tokens;**
This will be removed as your recommendations

**- withdraw tokens and ether.**
I thought that it would be fine that owner withdraw tokens and ether from ProxyNemodax.
Charging in proxyNemodax before withdrawing is for a simple currency exchange service(ETH->NemoCoin, NemoCoin->ETH). Technically, it's all owner's assets.

**3.7 issue(The relocating)**
Actually, This is one of my most worried item. 
Changeable contracts have a lot of problem as you said. 
But Ethereum is changing even now, and it isn't  securely perfect. 
So we thought that we could get more advantage from the changeable contracts when we think about future.
As I know There are tokens already being served as a Proxy structure([Civic](https://etherscan.io/address/0xa3db33ccfe990fdf89ff311754391b5c3af4ef04#code), [Decentraland](https://etherscan.io/address/0xf87e31492faf9a91b02ee0deaad50d51d56d5d4d#code
), [Synthetix](https://etherscan.io/address/0xc011a72400e58ecd99ee497cf89e3775d4bd732f#code
), etc) and if we'll change our codes, we must report it to organizations and companies involved in our business including [etherscan](https://etherscan.io/). The codes open to a public and if it'll be changed, public will be able to noticed.

So my point is that can never it deployed with a proxy contract structure?

I'd like you to review the above

**Comment by Dexaran** [comment]
@hapsody 

It should be noted that all the reported findings have "severity". `3.6` and `3.7` items have LOW severity which means that this issues can cause some problems in some specific circumstances in theory, however this is not necessary to fix LOW severity issues if you are sure that they will not affect the auditable system. 

In case of owners privileges, we report any theoretical possibility of breach of the smart-contract. This does not mean that this will happen but this is still theoretically possible.
