### ISSUE TITLE
chainmonsters

### ISSUE THREAD

**Issue by MillianoConti** [EthereumCommonwealth/Auditing#198]
# Audit request

ChainMonsters is a distributed application running on the Ethereum network, using specially-developed smart contracts to enable users to own, transfer, fight, collect and contest uniquely digital monsters, which can then be visualized on a website and in a game that the user can interact with.
https://chainmonsters.io/
# Source code

https://github.com/MWCVision/ChainMonsters-smartcontract

# Disclosure policy

https://discordapp.com/invite/jyD7jRj

# Platform

ETH

# Number of lines: 
1541

**Comment by danbogd** [comment]
Auditing time: 6 days.

**Comment by yuriy77k** [comment]
@danbogd we put on hold this request for a while. Not assigned.
