### ISSUE TITLE
Cryptosaga

### ISSUE THREAD

**Issue by MillianoConti** [EthereumCommonwealth/Auditing#199]
# Audit request
CryptoSaga is a decentralized RPG on the Ethereum blockchain with fully animated Heroes and Mobs.
https://cryptosaga.io/#/

# Source code

https://github.com/cryptosaga/cryptosaga/tree/master/contracts

# Disclosure policy

Public raport

# Platform

Eth

# Number of lines:
2167

**Comment by danbogd** [comment]
Auditing time: 6 days.

**Comment by yuriy77k** [comment]
@danbogd this request is not approved.
