### ISSUE TITLE
ETC TokenMint

### ISSUE THREAD

**Issue by Dexaran** [EthereumCommonwealth/Auditing#2]
# Audit request

TokenMint is a service that offers to launch an ICO and deploy a custom token contract easily. 
Website: https://tokenmint.io/#/

# Source code

https://github.com/ethereumproject/TokenMint/tree/master/contracts

# Disclosure policy

Publish everything.

# Platform

Deployed at Ethereum CLassic.

**Comment by Dexaran** [comment]
### In scope:
Smart-contracts at this repo: https://github.com/ethereumproject/TokenMint/tree/master/contracts

1. https://github.com/ethereumproject/TokenMint/blob/master/contracts/metaTokenmint.sol
2. https://github.com/ethereumproject/TokenMint/blob/master/contracts/registry.sol
3. https://github.com/ethereumproject/TokenMint/blob/master/contracts/deployed/crowdsale.sol
4. https://github.com/ethereumproject/TokenMint/blob/master/contracts/deployed/icoMachine.sol
5. https://github.com/ethereumproject/TokenMint/blob/master/contracts/deployed/manReg.sol

**Comment by yuriy77k** [comment]
Time for audit - 15 days.

**Comment by Dexaran** [comment]
@yuriy77k assigned.

**Comment by MrCrambo** [comment]
Time for audit: 4days.

**Comment by Dexaran** [comment]
@MrCrambo assigned.

**Comment by dieselc** [comment]
Auditing time: 10 days.

**Comment by Dexaran** [comment]
@dieselc assigned.

**Comment by RideSolo** [comment]
Auditing time 5 days.

**Comment by Dexaran** [comment]
@RideSolo assigned.

**Comment by gorbunovperm** [comment]
Estimated auditing time is 7 days.

**Comment by Dexaran** [comment]
@gorbunovperm assigned.

**Comment by gorbunovperm** [comment]
@Dexaran My report is finished.

**Comment by yuriy77k** [comment]
@danbogd assigned

**Comment by danbogd** [comment]
My report is ready.

**Comment by yuriy77k** [comment]
@greywolf12 assigned

**Comment by sarathi16** [comment]
Estimate time: 5days
