### ISSUE TITLE
playerone

### ISSUE THREAD

**Issue by MillianoConti** [EthereumCommonwealth/Auditing#205]
# Audit request

PlayerOne-a decentralized gamer identity protocol.
https://playerone.id/?utm_source=StateOfTheDApps#protocol
# Source code

https://github.com/playerone-id/biginteger-for-eosio

# Disclosure policy

https://t.me/playerone_id

# Platform

EOS

**Comment by Dexaran** [comment]
This request points out to the `BitInteger` library for EOS. This is not directly related to PlayerOne project because this is only a small part of its software. I guess that the smart-contracts of Player One are not publicly available.

However, I found this library useful.

**Comment by Dexaran** [comment]
Incorrect request.
