### ISSUE TITLE
Deconet

### ISSUE THREAD

**Issue by gorbunovperm** [EthereumCommonwealth/Auditing#21]
# Audit request

Deconet call on all bug bounty hunters to help identify bugs in Deconet smart contracts and dApps.

The idea for Deconet was initially published in the [Whitepaper](https://deco.network/whitepaper.pdf). This concept has been realized via our Ethereum smart contracts and dApp system.

# Source code

The numerous smart contracts as found in the smart contract [repo](https://github.com/deconet/DeconetSmartContracts).

# Disclosure policy

Send the results through this form https://docs.google.com/forms/d/e/1FAIpQLSekPO2VJjelx-15uy9tlCI-MGBtPD9RChLcvf2kUtorFuvRNQ/viewform

Public disclosure of a vulnerability makes it ineligible for a bounty.

# Platform

ETH

# More info

- [Bug Bounty page](https://deco.network/bugbounty.html)
- [dApp (prod instance, please do not attack)](https://app.deco.network/)
- [Blog post on how API selling works](https://medium.com/deconet/selling-apis-and-api-calls-on-deco-network-2722b4d0b0be)
- [Blog post on how the different smart contracts work](https://medium.com/deconet/deco-network-alpha-smart-contracts-e6ac31f7ef35)
- [dApp help page](https://app.deco.network/help)
- [A list of known issues and domains that are ineligible for the bounty](https://deco.network/bugbounty/known_issues.html)
- Email for questions: bugbounty@deco.network

**Comment by gorbunovperm** [comment]
Estimated auditing time is 10 days.

**Comment by yuriy77k** [comment]
@gorbunovperm assigned

**Comment by yuriy77k** [comment]
If auditor find security issue and earn reward, he got  90% and 10% for Callisto treasury.

**Comment by RideSolo** [comment]
Auditing time: 10 days.

**Comment by yuriy77k** [comment]
@RideSolo  assigned

**Comment by yuriy77k** [comment]
When you found security issue write directly to contract developer to get bug bounty. 
And inform me about finding.
