### ISSUE TITLE
LoveAirCoffee v2.

### ISSUE THREAD

**Issue by yuriy77k** [EthereumCommonwealth/Auditing#212]
# Audit request

Smart Contract LOVE AIR COFFEE spend many etaps ICO. In the first stage it frozen coins and after stop stage it unfrozen  coins. Smart contract have functions startBuyingTokens for start buying, stopBuyingTokens for stop buying, setPrices for the set new price per one eth. Other functions it a standart ERC20.

Sait :https://tokensale.loveaircoffee.com
Whitepaper: https://tokensale.loveaircoffee.com/docs/Whitepaper_en_1.0.pdf

# Source code

https://github.com/LOVEAirCoffee/tokensale/blob/master/LAC.sol

# Disclosure policy

support@loveaircoffee.com

# Platform

ETH

# Reaudit

https://github.com/EthereumCommonwealth/Auditing/issues/135#issuecomment-456499629

# Number of lines: 
141 * 0.5 (reaudit coeficient) = 71

**Comment by danbogd** [comment]
Auditing time: 2 days.

**Comment by MrCrambo** [comment]
Auditing time 2 days

**Comment by yuriy77k** [comment]
@danbogd @MrCrambo assigned

**Comment by sarathi16** [comment]
Auditing Time: 2days

**Comment by yuriy77k** [comment]
@sarathi16 you have unfinished audits. Please, complete it before taking a new one. 
You are not assigned.

**Comment by yuriy77k** [comment]
@sarathi16 assigned

**Comment by danbogd** [comment]
My report is finished.

**Comment by yuriy77k** [comment]
# Security Audit Report

# 1. Summary

[LoveAirCoffee V2](https://github.com/LOVEAirCoffee/tokensale/blob/bd368f5fe97945b715bfc4f7166f62ec7c48487e/LAC.sol) smart contract security audit report performed by [Callisto Security Audit Department](https://github.com/EthereumCommonwealth/Auditing)

# 2. In scope

Сommit hash bd368f5fe97945b715bfc4f7166f62ec7c48487e.

- [LAC.sol](https://github.com/LOVEAirCoffee/tokensale/blob/master/LAC.sol).

# 3. Findings

In total, **1 issues** were reported including:

- 1 low severity issues.

No critical security issues were found.

## 3.1. Known vulnerabilities of ERC-20 token

### Severity: low

### Description

1. It is possible to double withdrawal attack. More details [here](https://docs.google.com/document/d/1YLPtQxZu1UAvO9cZ1O2RPXBbT0mooh4DYKjA_jp-RLM/edit).

2. Lack of transaction handling mechanism issue. [WARNING!](https://gist.github.com/Dexaran/ddb3e89fe64bf2e06ed15fbd5679bd20)  This is a very common issue and it already caused millions of dollars losses for lots of token users! More details [here](https://docs.google.com/document/d/1Feh5sP6oQL1-1NHi-X1dbgT3ch2WdhbXRevDN681Jv4/edit).

### Recommendation

Add the following code to the `transfer(_to address, ...)` function:

```
require( _to != address(this) );

```

# 4. Conclusion

The audited smart contract can be deployed. Only low severity issues were found during the audit.

# 5. Revealing audit reports

https://gist.github.com/yuriy77k/e7884f21ad9c2dbd7a6955ca42ba150d

https://gist.github.com/yuriy77k/feeedd07231532ff012f5e8019e42883

https://gist.github.com/yuriy77k/c7805b200d68b75f9cc7caef0d1b6164
