### ISSUE TITLE
Development suggestion.

### ISSUE THREAD

**Issue by X-P-P** [EthereumCommonwealth/Auditing#213]
Hi, Callisto team. I am a member of the community.
I have a suggestion.
I think it would be a good idea to create an audit liability fund. Similar treasure and Cold Stacking. If after an audit problems arise, compensate from the fund. If there are no problems and the fund grows, encourage a team of auditors. I think this can be a serious fundamental advantage that no one in the crypto market offers. And it is attractive for serious big projects. In addition, a growing liability fund is a good marketing tool.
I hope I wrote in the right section.
TY

**Comment by KotNaplakal** [comment]
@X-P-P https://github.com/EthereumCommonwealth/Proposals/issues это правильный раздел.

**Comment by Dexaran** [comment]
@X-P-P please follow the discussion here: https://github.com/EthereumCommonwealth/Proposals/issues/66

Thank you for the proposal.
