### ISSUE TITLE
EOS Gift Card

### ISSUE THREAD

**Issue by MillianoConti** [EthereumCommonwealth/Auditing#214]
# Audit request
EOS Gift Card is a service, which allows you to easily create new EOS accounts.
https://eosgiftcard.com/

# Source code

https://github.com/slyon/signup

# Disclosure policy

hello@eosgiftcard.com

# Platform

EOS

**Comment by MrToph** [comment]
Estimated auditing time is 7 days.

**Comment by Dexaran** [comment]
@MrToph assigned

**Comment by MrToph** [comment]
My report is finished

**Comment by cryptoabhi** [comment]
Estimated time 3 days

**Comment by Dexaran** [comment]
@cryptoabhi assigned

**Comment by cryptoabhi** [comment]
My report finished and sent
