### ISSUE TITLE
CryptoHands MLM

### ISSUE THREAD

**Issue by novaseo** [EthereumCommonwealth/Auditing#221]
# Audit request

CryptoHands is one of the first open MLM smart contracts. The smart contract in its main version is the operator of funds and allows you to buy and sell levels in a multi-level MLM structure. Full review https://cryptohands.org

# Source code

https://etherscan.io/address/0xA315bD2e3227C2ab71f1350644B01757EAFf9cb4#code

# Disclosure policy

cryptohands@protonmail.com

# Platform

Ethereum Main Network

**Comment by sarathi16** [comment]
Auditing time : 2days

**Comment by yuriy77k** [comment]
@novaseo we don't audit any kind of MLM or Ponzi scheme.

**Comment by yuriy77k** [comment]
@sarathi16 you have to audit only "approved" audit request.

**Comment by novaseo** [comment]
> @novaseo we don't audit any kind of MLM or Ponzi scheme.

Ok. But it open MLM, not a Ponzi scheme
