### ISSUE TITLE
PandaEarth

### ISSUE THREAD

**Issue by MillianoConti** [EthereumCommonwealth/Auditing#222]
# Audit request
PandaEarth is a social simulation APP built on ERC-721 protocol. In this virtual world, players will be able to get pandas from marketplace, breed pandas or ERC-721 assets exchange.
https://panda.earth/

# Source code

https://github.com/PandaEarth/cryptopandas

# Disclosure policy

https://t.me/pandaearth

# Platform

ETH

# Number of lines: 
1270

**Comment by danbogd** [comment]
Auditing time: ~ 5 days.
