### ISSUE TITLE
EOSNameSwaps

### ISSUE THREAD

**Issue by MillianoConti** [EthereumCommonwealth/Auditing#224]
# Audit request
EOSNameSwaps is a decentralized EOS account exchange.
https://www.eosnameswaps.com/en.html

# Source code
https://github.com/StarryJapanNight/eosnameswaps
https://github.com/StarryJapanNight/eosnameswaps/blob/master/include/eosnameswaps.hpp

# Disclosure policy

https://t.me/eosnameswaps

# Platform

EOS

**Comment by MrToph** [comment]
I'm interested in auditing. Estimated time 7 days.

**Comment by Dexaran** [comment]
@MrToph assigned

**Comment by MrToph** [comment]
submitted
