### ISSUE TITLE
TRONDapphub Dice

### ISSUE THREAD

**Issue by yuriy77k** [EthereumCommonwealth/Auditing#230]
# Audit request

TRONDapphub aims to host 100+ games in 1 Platform by 2020.
Currently, we have 60 games available to deploy by Q4 2019.
• TRONdapphub.io aims to provide both Mobile and Web Gaming experience to its
Users.
• TRONdapphub.io mission is to be the Biggest Dapp by Volume and Usage standpoint on Tron Ecosystem by hosting most Popular Traditional PVP Games like Bowling,
Billiards, Football, and Casino Games like Dice, Texas Holdem, Black Jack, Baccarat, High
Low, Let it Ride, Casino War, Slots, Keno.
• Our goal as a team is to create the fairest provability across all our games.

website: Trondapphub.io

https://trondapphub.io/wp/Whitepaper%20TRONDapphub.pdf

Dice game:: https://trondapphub.io/#/dice

# Source code

Will be provide privately

# Disclosure policy

trondapphub@gmail.com

# Platform

TRX

# Number of lines: 
369

**Comment by MrCrambo** [comment]
Auditing time 2 days

**Comment by yuriy77k** [comment]
@MrCrambo assigned.

**Comment by RideSolo** [comment]
auditing time : 3 days

**Comment by yuriy77k** [comment]
@RideSolo assigned

**Comment by gorbunovperm** [comment]
Estimated auditing time is 3 days.

**Comment by yuriy77k** [comment]
@gorbunovperm assigned

**Comment by gorbunovperm** [comment]
My report is finished.

**Comment by yuriy77k** [comment]
# TRONDapphub Dice Security Audit Report

# 1. Summary

[TRONDapphub Dice](https://trondapphub.io/wp/Whitepaper%20TRONDapphub.pdf) smart contract security audit report performed by [Callisto Security Audit Department](https://github.com/EthereumCommonwealth/Auditing)

# 2. In scope

- The audited code was requested to be private.

# 3. Findings

In total, ** issues** were reported including:

- 2 Critical severity issues.

- 4 high severity issues.

- 3 medium severity issues.

- 6 low severity issues.

- 5 owner privileges (ability of owner to manipulate contract, may be risky for investors).
