### ISSUE TITLE
sport bet

### ISSUE THREAD

**Issue by MillianoConti** [EthereumCommonwealth/Auditing#233]
# Audit request
First decentralized sportsbook on EOS blockchain.
https://sportbet.one/s/3

# Source code

https://github.com/sportbetone/eos-contracts

# Disclosure policy

https://t.me/SportBetOfficial

# Platform

EOS

**Comment by MrToph** [comment]
Seems like the token contract + staking + logic for their private sale only so far, not the actual sportsbook. I'd still be interested in reviewing if approved.

Time 7 days

**Comment by Dexaran** [comment]
@MrToph assigned

**Comment by MrToph** [comment]
Submitted
