### ISSUE TITLE
SURPRISE token (SPS)

### ISSUE THREAD

**Issue by Looder** [EthereumCommonwealth/Auditing#24]
# Audit request

SURPRISE token (SPS) Investigate, modify and deploy successful smart contract options. The receipt of tokens for new smart contracts depends on whether the user has SPS tokens.

(I already sent an audit request through the form on the site. I received a letter today that my request was rejected. 
https://bitcointalk.org/index.php?topic=3380156.msg44715938#msg44715938
Why?)

# Source code

https://github.com/Looder/airdrop/blob/master/sps

# Disclosure policy

looder33@outlook.com

# Platform

ETC/ETH/CLO

**Comment by yuriy77k** [comment]
If you are not developer, you can order audit of this contract for 30 000 CLO

**Comment by Looder** [comment]
@yuriy77k https://bitcointalk.org/index.php?topic=3380156.msg44715938#msg44715938
https://bitcointalk.org/index.php?topic=2966494.0
https://bitcointalk.org/index.php?action=profile;u=1072491
Personal Text: looder33@outlook.com
The site has not yet done.

**Comment by Looder** [comment]
> If you are not developer, you can order audit of this contract for 30 000 CLO
You can audit another's smart contract after making a deposit of 30000 CLO?
Where is the address of the smart contract?

**Comment by RideSolo** [comment]
auditing time: 2 days

**Comment by yuriy77k** [comment]
@RideSolo assigned

**Comment by yuriy77k** [comment]
# Surprise Token Audit Report.

# 1. Summary

This document is a security audit report performed by [RideSolo](https://github.com/RideSolo), where [Surprise Token](https://github.com/Looder/airdrop/) has been reviewed.

# 2. In scope

- [sps.sol](https://github.com/Looder/airdrop/blob/4108a0613091029ba6c159da5ddfbc27d0bcfcf0/sps#L1) github commit hash 4108a0613091029ba6c159da5ddfbc27d0bcfcf0.

# 3. Findings

**3 issues** were reported including:

- 2 medium severity issues.

- 1 low severity issues.

## 3.1. SPS Airdrop

### Severity: medium

### Description

SPS contract airdrop `276` tokens to every single new address that makes a `transfer` or `transferFrom` transaction. 
The operation is done once for each address  without any limit on the total airdropped tokens except the totalsupply of SPS itself. This logic will push users to abuse the contract by creating multiple addresses if the tokens value is higher than the transactions gas consumption.

### Code snippet

https://github.com/RideSolo/airdrop/blob/master/sps#L77#L81

https://github.com/RideSolo/airdrop/blob/master/sps#L98#L102

## 3.2. Contract Constructor

### Severity: medium

### Description

Contract constructor is not defined, which means that no tokens from the total supply is allocated to any address, making `transfer` or `transferFrom` not usable by anyone in conclusion the airdrop logic will not work.

## 3.3. Known Issues of ERC20 Standard

### Severity: low

### Description

SPS token is ERC20 compatible, ERC20 Tokens have some well-known issues (listed bellow), This is just a reminder for the contract developers.

- Approve + transferFrom mechanism allows double Withdrawal attack.
- Lack of transaction handling.

The above mentioned issues are well documented, a basic search can help to get more information.

## 4. Conclusion

This contract is not operable, and cannot be deployed for obvious logical reasons, it does not represent any risk for users since it doesn't work.

**Comment by Looder** [comment]
https://etherscan.io/token/0xd9A72fEc8683db0666769D841d6D127F350B4418#balances

**Comment by Looder** [comment]
> The operation is done once for each address without any limit on the total airdropped tokens except the totalsupply of SPS itself. This logic will push users to abuse the contract by creating multiple addresses if the tokens value is higher than the transactions gas consumption.

This is the essence of a smart contract. This way of mining. 
**The question is, is it possible to create more tokens than stated in the total supply?**

**Comment by yuriy77k** [comment]
> The question is, is it possible to create more tokens than stated in the total supply?
Our security auditor did not find such vulnerability.

**Comment by RideSolo** [comment]
@Looder I have updated my report, the manager will soon update the conclusion on this issue.

**Comment by Looder** [comment]
@yuriy77k @RideSolo 
Anyone can "mining" SPS tokens, by creating new addresses and conducting transactions with received tokens.
Thus, no more than 208,932,000 SPS can be produced.
The tokens received at the address creation are virtual until they are carried out with any transaction.
If you create multiple addresses but do not collect received tokens into one address, you can lose them after other holders receive 208,932,000 confirmed by SPS transactions.
For example:
Miner Frank creates 500,000 addresses and gets 138000000 SPS on them, but does not collect tokens for one address. Miners Bob and Tom create 757,000 addresses with 208,932,000 SPS, but collect tokens on their personal addresses when paying for transactions.
As a result, Bob and Tom remain holders of the token, but Frank's tokens disappear.

**Change the findings of the Surprise Token Audit Report in accordance with the objectives of the smart contract. Thank you!**

**Comment by Looder** [comment]
@RideSolo you need to check these statements:

> Thus, no more than 208,932,000 SPS can be produced.
The tokens received at the address creation are virtual until they are carried out with any transaction.
If you create multiple addresses but do not collect received tokens into one address, you can lose them after other holders receive 208,932,000 confirmed by SPS transactions.

**Comment by RideSolo** [comment]
@Looder 

"Anyone can "mining" SPS tokens, by creating new addresses and conducting transactions with received tokens."  I'm not sure why do you call this mining, it is an airdrop.

"Thus, no more than 208,932,000 SPS can be produced." 
we didn't say that you can produce more.

"The tokens received at the address creation are virtual until they are carried out with any transaction.
If you create multiple addresses but do not collect received tokens into one address, you can lose them after other holders receive 208,932,000 confirmed by SPS transactions."

There is no token received at address creation, users will see the value of `getBalance` that will lead them to think that they have tokens, even when they will know that they need a transaction to confirm their airdroped tokens, a race condition where all the addresses will participate to get their reward before others.

**Comment by Looder** [comment]
@RideSolo You must give an opinion ONLY by code.

**Comment by RideSolo** [comment]
@Looder we do free audit to protect devs and users, therefore I can state a fact that I can see through the smart contract to help investors to not be scammed. ( scam is not about your project just to let you know, users will judge by themselves).

**Comment by Looder** [comment]
@RideSolo I will no longer conduct audits here. I was hoping for a conclusion related to the smart contract code, but not an assessment of the possible options for the perception of the smart contract by the user. I can not refer to such an audit, so as not to mislead the community.

**Comment by RideSolo** [comment]
@Looder your opinion. wish you the best of luck.

**Comment by Looder** [comment]
@yograterol This is not a professional audit. Audit in this form will harm the project.

**Comment by RideSolo** [comment]
@Looder you first post was 18 days ago you didn't talk about mining !!! you have edited it after that I ask you to add more information next time, anyone can see that you edited it 39mn ago since i posted this comment.

**Comment by Looder** [comment]
@RideSolo Let's delete all posts and wait until the @yuriy77k updates the "Surprise Token Audit Report"?

**Comment by RideSolo** [comment]
@Looder no need to delete anything for my side.

**Comment by Looder** [comment]
> @Looder no need to delete anything for my side.

Let's see what the CEO answers.

**Comment by yuriy77k** [comment]
[Audit report updated.](https://github.com/EthereumCommonwealth/Auditing/issues/24#issuecomment-420752856)

**Comment by Looder** [comment]
> The audited contract contains issues with different severity level that have to be fixed before the deployment. This contract can not be used as ERC20 token due to non-compliance with the standard ERC20.

What can this "vulnerability" lead to?

**Comment by yuriy77k** [comment]
> What can this "vulnerability" lead to?

All founded issues and conclusion were described in [audit report](https://gist.github.com/yuriy77k/4ac6b74431e73befb759a3517856ff57).

**Comment by yuriy77k** [comment]
This contract can be used only as game, with no obligation. It can not be used as ERC20 token due to non-compliance with the standard ERC20.

**Comment by Looder** [comment]
@yuriy77k 

> This contract can be used only as game, with no obligation. It can not be used as ERC20 token due to non-compliance with the standard ERC20.

That is, he can not trade on exchanges? What use are you talking about ?!

**Comment by yuriy77k** [comment]
> That is, he can not trade on exchanges?

Yes, SURPRISE token (SPS) can not trade on reliable exchanges.

**Comment by Looder** [comment]
> > That is, he can not trade on exchanges?
@yuriy77k 
> Yes, SURPRISE token (SPS) can not trade on reliable exchanges.

Does this mean that bidders can use this vulnerability to get tokens beyond what they have on the balance sheet?

**Comment by yuriy77k** [comment]
No, but customer could not get their real balance. They can see more tokens on the balance than there is in fact.

**Comment by Looder** [comment]
> No, but customer could not get their real balance. They can see more tokens on the balance than there is in fact. It's a deception of users.

While the holder has not spent at least one transaction with the token, he will see a virtual amount. What is cheating?
Or do you think that the virtual balance display will remain in the future?

**Comment by yuriy77k** [comment]
By ERC20 standard the function getBalance() must return **REAL** token balance. If you want to show users virtual balance, add new function getVirtualBalance().

**Comment by Looder** [comment]
@yuriy77k If the REAL tokens of the holders are safe, then there is no vulnerability. Thank you for your advice.

**Comment by yuriy77k** [comment]
The contract did not show which tokens is on balance (real or virtual) therefore, it is possible that the user will see that the tokens have disappeared from the balance.

**Comment by Looder** [comment]
They can disappear only in the event that no transactions with them were conducted.

**Comment by yuriy77k** [comment]
> They can disappear only in the event that no transactions with them were conducted.

Not only, It can disappear also after airdrop all token supply.

**Comment by Looder** [comment]
> > They can disappear only in the event that no transactions with them were conducted.
> 
> Not only, It can disappear also after airdrop all token supply.

Are you in charge of your words?

**Comment by yuriy77k** [comment]
> Are you in charge of your words?

English is not my native language so maybe `difficulties of translation`. Our official audit report with conclusion is [here](https://gist.github.com/yuriy77k/4ac6b74431e73befb759a3517856ff57).

**Comment by yuriy77k** [comment]
To bring this contract in accordance with the standard ERC20, it is necessary to fixed getBalance() function like this:
```
    function getBalance(address _a) internal constant returns(uint256)
    {
            return balances[_a];
    }
```

**Comment by Looder** [comment]
@yuriy77k Where can I look at the algorithm for determining the balance on which you rely in your conclusions?

**Comment by yuriy77k** [comment]
> @yuriy77k Where can I look at the algorithm for determining the balance on which you rely in your conclusions?

You are developer and can look at the algorithm for determining the balance in your source code, are not?
