### ISSUE TITLE
KyberNetwork

### ISSUE THREAD

**Issue by MillianoConti** [EthereumCommonwealth/Auditing#240]
# Audit request
Kyber is an on-chain liquidity protocol that aggregates liquidity from a wide range of reserves, powering instant and secure token exchange in any decentralized application.
https://kyber.network/

# Source code

https://github.com/KyberNetwork/smart-contracts/tree/master/contracts

# Disclosure policy

support@kyber.network

# Platform

ETH

**Comment by yuriy77k** [comment]
@MillianoConti please, also add all your request to our website: https://callisto.network/smart-contract-audit/  (Audit a Contract)
