### ISSUE TITLE
SelfKey

### ISSUE THREAD

**Issue by MillianoConti** [EthereumCommonwealth/Auditing#274]
# Audit request
SelfKey is a blockchain based digital identity system where its users can truly own, control and manage their digital identity, and instantly and securely buy passports, residency, fintech products, financial services, and sign up for coin exchanges, token sales and much more...
https://selfkey.org/

# Source code

https://github.com/SelfKeyFoundation/selfkey-main-contracts/tree/develop/contracts

## Exclude:
- Migrations.sol
- mock/MockToken.sol

# Disclosure policy

https://t.me/selfkeyfoundation

# Platform

ETH

# Number of lines: 
176

**Comment by MrCrambo** [comment]
Auditing time 1 day

**Comment by yuriy77k** [comment]
@MrCrambo assigned

**Comment by danbogd** [comment]
Auditing time: 2 days.

**Comment by yuriy77k** [comment]
@danbogd assigned

**Comment by danbogd** [comment]
My report is finished.

**Comment by yuriy77k** [comment]
@danbogd assigned

**Comment by RideSolo** [comment]
Auditing time: 1 day.

**Comment by yuriy77k** [comment]
@RideSolo assigned

**Comment by yuriy77k** [comment]
# SelfKey Security Audit Report

# 1. Summary

[SelfKey](https://github.com/SelfKeyFoundation/selfkey-main-contracts/tree/develop/contracts) smart contract security audit report performed by [Callisto Security Audit Department](https://github.com/EthereumCommonwealth/Auditing)

# 2. In scope

Сommit hash f7163d55b2bac2d9b9e575ae35660c453ff32e42.

- [SelfKeyMain.sol](https://github.com/SelfKeyFoundation/selfkey-main-contracts/blob/develop/contracts/SelfKeyMain.sol).
- [PaymentSplitter.sol](https://github.com/SelfKeyFoundation/selfkey-main-contracts/blob/develop/contracts/PaymentSplitter.sol).

# 3. Findings

In total, **1 issues** were reported including:

- 1 low severity issues.

No critical security issues were found.

## 3.1. Known vulnerabilities of ERC-20 token

### Severity: low

### Description

Lack of transaction handling mechanism issue. [WARNING!](https://gist.github.com/Dexaran/ddb3e89fe64bf2e06ed15fbd5679bd20)  This is a very common issue and it already caused millions of dollars losses for lots of token users! More details [here](https://docs.google.com/document/d/1Feh5sP6oQL1-1NHi-X1dbgT3ch2WdhbXRevDN681Jv4/edit).

### Recommendation

Add the following code to the `transfer(_to address, ...)` function:

```
require( _to != address(this) );

```

# 4. Conclusion

The audited smart contract can be deployed. Only low severity issues were found during the audit.

# 5. Revealing audit reports

https://gist.github.com/yuriy77k/f3c5620098801ccb9083a80ef4328143

https://gist.github.com/yuriy77k/185cdb3506cbf02c027ee24cb874ffd6

https://gist.github.com/yuriy77k/889d8183a27b71fea4ef447c6986530e

**Comment by MillianoConti** [comment]
Announced:https://www.reddit.com/r/selfkey/comments/c3ndmi/audit_of_selfkey_token_performed_by_callisto/
