### ISSUE TITLE
Native-gaming

### ISSUE THREAD

**Issue by yuriy77k** [EthereumCommonwealth/Auditing#275]
# Audit request

We're creating an online casino with a decentralized bankroll and staking component, as well as a casino credit line. 

White paper https://www.dropbox.com/s/tmp5sjtv4pn5y25/NATIVE%20GAMING%20WHITE%20PAPER%201.0.pdf?dl=0

# Source code

Will be provide privately

# Disclosure policy

frankkailik@gmail.com

# Platform

ETH

# Number of lines: 

1363

**Comment by danbogd** [comment]
Auditing time: ~ 5 days.

**Comment by Paramon** [comment]
Auditing time: ~ 5 days.

**Comment by yuriy77k** [comment]
@danbogd assigned

**Comment by RideSolo** [comment]
@yuriy77k  I will estimate the audit time after receiving the code. I would like to apply for the audit.

**Comment by yuriy77k** [comment]
@RideSolo assigned

**Comment by codeblcks** [comment]
Estimated time: 4 days

**Comment by yuriy77k** [comment]
@codeblcks Not assigned.

**Comment by gorbunovperm** [comment]
Estimated auditing time is 4 days.

**Comment by yuriy77k** [comment]
@gorbunovperm assigned

**Comment by gorbunovperm** [comment]
My report is finished.

**Comment by CineTek** [comment]
Hey, has anyone reviewed more than just these 5 contracts? If so, let me know ASAP since our intended scope was not limited to these extrapolated contracts alone..

**Comment by RideSolo** [comment]
@CineTek are you part of native-gaming team ? if so how can we audit more than what you provide to us ? we don't have the base contracts. 
I advise you to open a new issue, you can check more with @yuriy77k.

**Comment by yuriy77k** [comment]
@danbogd @RideSolo @gorbunovperm I've sent full source code of contacts in telegram. Please,  finish this audit using new code.

**Comment by gorbunovperm** [comment]
@yuriy77k How many lines of code now?

**Comment by yuriy77k** [comment]
@gorbunovperm I'll calculate it later.

**Comment by yuriy77k** [comment]
Number of lines updated

**Comment by gorbunovperm** [comment]
My report is finished.

**Comment by danbogd** [comment]
My report is finished.

**Comment by yuriy77k** [comment]
# Native Gaming Security Audit Report

# 1. Summary

[Native Gaming](http://NativeGaming.io) smart contract security audit report performed by [Callisto Security Audit Department](https://github.com/EthereumCommonwealth/Auditing)

# 2. In scope

- /ngbankroll_base.sol
- /ngprivatesale_base.sol
- /ngstaking_base.sol
- /ngcreditline_base.sol
- /eth/ngbankroll.sol
- /eth/ngdeploy.sol
- /eth/ngprivatesale.sol
- /eth/ngstaking.sol
- /eth/ngcashier.sol
- /eth/ngcreditline.sol
- /erc_20/ngbankroll_erc20.sol
- /erc_20/ngcashier_erc20.sol
- /erc_20/ngcreditline_erc20.sol
- /erc_20/ngprivatesale_erc20.sol
- /erc_20/ngstaking_erc20.sol
- /dai/ngdeploy_dai.sol

# 3. Findings

In total, **12 issues** were reported including:

- 1 high severity issues.

- 1 medium severity issues.

- 4 low severity issues.

- 1 notes.

- 5 owner privileges (the ability of an owner to manipulate contract, may be risky for investors).
