### ISSUE TITLE
Kriptotrackers ICO

### ISSUE THREAD

**Issue by carlossampol** [EthereumCommonwealth/Auditing#281]
# Audit request
Crowdsale contract based in OpenZeppelin for the Kriptotrackers ICO, here is a ReadMe with the requirements that  should meet https://github.com/kriptotrackers/SolidityCrowdsale/blob/master/README.md
# Source code
https://github.com/kriptotrackers/SolidityCrowdsale/blob/master/contracts/KriptotrackersCrowdsale.sol
# Disclosure policy
xperez@turinginvestmentsgroup.com
# Platform
Ethereum
# Number of lines: 
120

**Comment by MrCrambo** [comment]
Auditing time 1 day

**Comment by RideSolo** [comment]
auditing time 1 day

**Comment by danbogd** [comment]
Auditing time: 1 day.

**Comment by yuriy77k** [comment]
@RideSolo @danbogd assigned

**Comment by yuriy77k** [comment]
@MrCrambo assigned

**Comment by danbogd** [comment]
My report is finished.

**Comment by MrCrambo** [comment]
My report is finished

**Comment by yuriy77k** [comment]
# Kriptotrackers ICO Security Audit Report

# 1. Summary

[Kriptotrackers ICO](https://github.com/kriptotrackers/SolidityCrowdsale/blob/master/contracts/KriptotrackersCrowdsale.sol) smart contract security audit report performed by [Callisto Security Audit Department](https://github.com/EthereumCommonwealth/Auditing)

# 2. In scope

Сommit hash baa8024e253d17da537e1fa2fe9bf071fcaf198e.

- [KriptotrackersCrowdsale.sol](https://github.com/kriptotrackers/SolidityCrowdsale/blob/master/contracts/KriptotrackersCrowdsale.sol).

# 3. Findings

No  security issues were found.

# 4. Conclusion

The audited smart contract can be deployed. No security issues were found during the audit.

# 5. Revealing audit reports

https://gist.github.com/yuriy77k/b055da40f8ef6c1b72de3ea056f93f9e

https://gist.github.com/yuriy77k/bcc4de7de562c4826a11ee837ea93077

https://gist.github.com/yuriy77k/6c1669deca37ef8915a80d8e97fef8ae

**Comment by MillianoConti** [comment]
[Reddit announcement](https://www.reddit.com/r/ethereum/comments/c9s7hh/audit_of_kriptotrackers_ico_performed_by_callisto/)
