### ISSUE TITLE
V-ID

### ISSUE THREAD

**Issue by MillianoConti** [EthereumCommonwealth/Auditing#295]
# Audit request
V-ID is a validation platform that secures any digital file against unlawful manipulation protecting businesses and processes against digital fraud.
https://about.v-id.org/

# Source code

https://github.com/V-ID/V-ID-Token

# Disclosure policy

service@v-id.org

# Platform

Eth.

**Comment by yuriy77k** [comment]
This contract already audited https://github.com/EthereumCommonwealth/Auditing/issues/91

**Comment by MillianoConti** [comment]
> This contract already audited #91


I apologize, I found this project interesting, but I did not check whether they conducted an audit on it.
