### ISSUE TITLE
TokenCard

### ISSUE THREAD

**Issue by MillianoConti** [EthereumCommonwealth/Auditing#301]
# Audit request
TokenCard is an Ethereum-powered solution allowing you to spend your ETH and ERC-20 in real-life, the way you're used to: with a debit card accepted anywhere.
https://tokencard.io/

# Source code

https://github.com/tokencard/contracts/blob/master/contracts/wallet.sol

# Disclosure policy

hello@tokencard.io

# Platform

ETH
# Number of lines: 
443

**Comment by MrCrambo** [comment]
Auditing time 2 days

**Comment by yuriy77k** [comment]
@MrCrambo assigned

**Comment by MrCrambo** [comment]
My report is finished

**Comment by danbogd** [comment]
Auditing time: 3 days.

**Comment by yuriy77k** [comment]
@danbogd assigned

**Comment by RideSolo** [comment]
Auditing time  2 days.

**Comment by RideSolo** [comment]
@yuriy77k wallet.sol contains multiple imports:

import "./licence.sol";
import "./internals/ownable.sol";
import "./internals/controllable.sol";
import "./internals/ensResolvable.sol";
import "./internals/tokenWhitelistable.sol";
import "./externals/SafeMath.sol";
import "./externals/SafeERC20.sol";
import "./externals/ERC165.sol";
and those import contains also import pointing to external folder.
Are they all excluded ? if yes the audit cannot be conducted.

**Comment by RideSolo** [comment]
The audit time will be re-estimated after confirmation of the in-scope sol files.

**Comment by danbogd** [comment]
My report is finished.
