### ISSUE TITLE
elad.network v.2.

### ISSUE THREAD

**Issue by carlossampol** [EthereumCommonwealth/Auditing#314]
# Audit request
Token creation.
 To be used  for IEO and main payment for our platform.
# Source code
https://etherscan.io/address/0x9b81a139e24a33b6bfdac826dafd383d215cf8ea#contracts
# Disclosure policy
dperkins@elad.network
# Platform
Ethereum
# Number of lines: 
240

**Comment by yuriy77k** [comment]
The same source code as was audited https://github.com/EthereumCommonwealth/Auditing/issues/89.
