### ISSUE TITLE
elad.network - duplicate

### ISSUE THREAD

**Issue by carlossampol** [EthereumCommonwealth/Auditing#315]
# Audit request
To distribute the Private Sale of our token.
# Source code
https://etherscan.io/address/0xD7D4E0FdB0a99b7aBbc6B478Acd661595093F8cc
# Disclosure policy
dperkins@elad.network
# Platform
Ethereum

**Comment by yuriy77k** [comment]
the same source code as https://github.com/EthereumCommonwealth/Auditing/issues/314 but deployed on other address

**Comment by yuriy77k** [comment]
the same source code as https://github.com/EthereumCommonwealth/Auditing/issues/314 but deployed on other address
