### ISSUE TITLE
elad.network - duplicate

### ISSUE THREAD

**Issue by carlossampol** [EthereumCommonwealth/Auditing#316]
# Audit request
To distribute the tokens in pre sale
# Source code
https://etherscan.io/address/0x5180fda6BcF43D72167Fe69FCa90671f0C2F4160
# Disclosure policy
dperkins@elad.network
# Platform
Ethereum

**Comment by yuriy77k** [comment]
the same source code as https://github.com/EthereumCommonwealth/Auditing/issues/314 but deployed on other address
