### ISSUE TITLE
ERC223 standard implementation for openzeppelin

### ISSUE THREAD

**Issue by Sparke2** [EthereumCommonwealth/Auditing#317]
# Audit request

This is a reference implementation of ERC223 token and interfaces that will be send in a pull request to the openzeppelin token list: https://github.com/OpenZeppelin/openzeppelin-solidity/tree/master/contracts/token

# Source code

https://github.com/Sparke2/openzeppelin-solidity/tree/master/contracts/token/ERC223

# Disclosure policy

I want you to publish the report as is.

ligreat875@gmail.com

# Platform

Ethereum
# Number of lines: 
58

**Comment by yuriy77k** [comment]
Our disclosure policy requires, that we should report critical issues to smart contract developer before publishing the report. Can you please provide WEB site of  project with email address on it to?

**Comment by Sparke2** [comment]
What project do you mean here?

As it is written in the audit request description this request is is a reference implementation of ERC223 token standard designed to be proposed to openzeppelin.

**Comment by Sparke2** [comment]
Which project website do you want me to provide? ERC223 website? OpenZeppelin?

**Comment by Sparke2** [comment]
@yuriy77k can you give me a link to a document with the disclosure policy described by you? 

I read this rules of auditing: https://github.com/EthereumCommonwealth/Auditing

Let me cite this rules:

>Anyone can submit a request of a security audit for an open-source smart-contract. After the creation of a security audit request, we will contact the developers of the smart contract being audited. Until we receive the response from the developers, the audit request will be assigned a low priority status. Low priority status is unassigned when we receive the confirmation from the developers. Confirmed audit requests are processed ahead of unconfirmed requests.

According to this rule set you approve the audit and assign it a low priority status without any further questions, isn't it?

Are the rules outdated?

**Comment by danbogd** [comment]
Auditing time: 1 day.

**Comment by MrCrambo** [comment]
Auditing time 1 day

**Comment by yuriy77k** [comment]
@danbogd @MrCrambo assigned

**Comment by danbogd** [comment]
My report is finished.

**Comment by MrCrambo** [comment]
My report is finished

**Comment by Dexaran** [comment]
@Sparke2 you need unit tests to submit your version of the standard token to OZ. I recommend that you commit your tests here: https://github.com/Sparke2/openzeppelin-solidity/tree/master/test/token
