### ISSUE TITLE
HXXD

### ISSUE THREAD

**Issue by carlossampol** [EthereumCommonwealth/Auditing#323]
# Audit request
The hxxd.io smart contract provides TRX deposit/withdrawal/transfer functionality for conversion to in-game TRC20 token "HXXD," token burn functionality and contract ownership management for the hxxd.io PvP game.
# Source code
https://github.com/AnotherForcedSignup/HXXD.io/blob/master/smart-contract.sol
# Disclosure policy
hxxd@null.net
# Platform
Tron

**Comment by yuriy77k** [comment]
Source code link does not work.

**Comment by Dexaran** [comment]
Source code is not provided.
