### ISSUE TITLE
 CryptoRome-LandSale

### ISSUE THREAD

**Issue by carlossampol** [EthereumCommonwealth/Auditing#325]
# Audit request
Built on the Ethereum blockchain, everything you purchase is yours - forever. Sell and trade your digital assets to other players for real money.
https://www.caesarstriumph.com/
https://www.reddit.com/r/cryptorome/
Proposal#63
# Source code
https://github.com/GigLabs/CryptoRome-LandSale
# Disclosure policy
https://discordapp.com/invite/RJBRkTx
# Platform
Ethereum
# Number of lines: 
233

**Comment by MrCrambo** [comment]
Auditing time 2 days

**Comment by MrCrambo** [comment]
Auditing time 1 day

**Comment by yuriy77k** [comment]
@MrCrambo assigned

**Comment by MrCrambo** [comment]
My report is finished

**Comment by gorbunovperm** [comment]
Estimated auditing time is 2 days.

**Comment by yuriy77k** [comment]
@gorbunovperm assigned

**Comment by gorbunovperm** [comment]
@yuriy77k Please, unassign me. I switched to LuckyStrike at your request, and now it's time to start a new high-priority audit #329 .

**Comment by yuriy77k** [comment]
@gorbunovperm unsigned.

**Comment by danbogd** [comment]
Auditing time 1 day.

**Comment by danbogd** [comment]
My report is finished.

**Comment by yuriy77k** [comment]
@danbogd assigned.
