### ISSUE TITLE
Native-gaming v.2.

### ISSUE THREAD

**Issue by yuriy77k** [EthereumCommonwealth/Auditing#327]
# Audit request

We're creating an online casino with a decentralized bankroll and staking component, as well as a casino credit line. 

White paper https://www.dropbox.com/s/tmp5sjtv4pn5y25/NATIVE%20GAMING%20WHITE%20PAPER%201.0.pdf?dl=0

# Source code

Will be provide privately

# Disclosure policy

frankkailik@gmail.com

# Platform

ETH

# Number of lines: 

940 (1881*0.5 reaudit coefficient)

**Comment by RideSolo** [comment]
Auditing time: 3 days.

**Comment by danbogd** [comment]
Auditing time: 3 days.

**Comment by yuriy77k** [comment]
@RideSolo @danbogd assigned

**Comment by gorbunovperm** [comment]
Estimated auditing time is 3 days.

**Comment by yuriy77k** [comment]
@gorbunovperm assigned

**Comment by danbogd** [comment]
My report is finished.

**Comment by gorbunovperm** [comment]
My report is finished.

**Comment by yuriy77k** [comment]
# Native Gaming V2 Security Audit Report

# 1. Summary

[Native Gaming V2](https://www.nativegaming.io/) smart contract security audit report performed by [Callisto Security Audit Department](https://github.com/EthereumCommonwealth/Auditing)

# 2. In scope

- all audited contracts were provided privately, please note that in the goal of performing a good audit all ds-contracts have been audited also.

# 3. Findings

In total, **10 issues** were reported including:

- 4 low severity issues.

- 2 notes.

- 4 owner privileges (the ability of an owner to manipulate contract, may be risky for investors).

No critical security issues were found.
