### ISSUE TITLE
SafePost v.2

### ISSUE THREAD

**Issue by carlossampol** [EthereumCommonwealth/Auditing#334]
# Audit request
SafePost is an encrypted messaging platform that keeps your privacy safe. With SafePost, no more SPAM, scammer mails, phishing mails, spyware and other malware, and no more data transfer and storage duration limit!
# Source code
https://www.dropbox.com/sh/ihb7u85pebvsrwk/AAAvvTM3I_m6089zq0dT2la2a?dl=0
# Disclosure policy
info@token-economics.eu
# Platform
Ethereum
# Number of lines: 
51 (103 * 0.5 reaudit coefficient) Previous audit: https://github.com/EthereumCommonwealth/Auditing/issues/319

**Comment by MrCrambo** [comment]
Auditing time 1 day

**Comment by yuriy77k** [comment]
@MrCrambo assigned

**Comment by MrCrambo** [comment]
My report is finished

**Comment by danbogd** [comment]
Auditing time: 2 days.

**Comment by danbogd** [comment]
My report is finished.

**Comment by yuriy77k** [comment]
@danbogd assigned

**Comment by gorbunovperm** [comment]
Estimated auditing time is 1 day.

**Comment by gorbunovperm** [comment]
My report is finished.

**Comment by yuriy77k** [comment]
@gorbunovperm assigned.

**Comment by yuriy77k** [comment]
# SafePost v.2 Security Audit Report

# 1. Summary

[SafePost v.2](https://www.dropbox.com/sh/ihb7u85pebvsrwk/AAAvvTM3I_m6089zq0dT2la2a?dl=0) smart contract security audit report performed by [Callisto Security Audit Department](https://github.com/EthereumCommonwealth/Auditing)

> SafePost is an encrypted messaging platform that keeps your privacy safe. With SafePost, no more SPAM, scammer mails, phishing mails, spyware and other malware, and no more data transfer and storage duration limit!

# 2. In scope

1. https://www.dropbox.com/sh/ihb7u85pebvsrwk/AAAvvTM3I_m6089zq0dT2la2a?dl=0&preview=safepost_solidity.sol
2. https://www.dropbox.com/sh/ihb7u85pebvsrwk/AAAvvTM3I_m6089zq0dT2la2a?dl=0&preview=spaccount_v.3_solidity.sol

# 3. Findings

No security issues were found.

# 4. Conclusion

The audited smart contract is safe and can be deployed.

# 5. Revealing audit reports

https://gist.github.com/yuriy77k/1bbb8598f66b39a3822382bf25aa85d3

https://gist.github.com/yuriy77k/f60d83eb979dfaebb2d50fa960a095d2

https://gist.github.com/yuriy77k/a2a83e16c79f9f7d3aa6503523a985c0

**Comment by Dexaran** [comment]
This issue does not require reddit announcement. This is a re-audit of the already-audited project.
