### ISSUE TITLE
Clickscrow token

### ISSUE THREAD

**Issue by carlossampol** [EthereumCommonwealth/Auditing#339]
# Audit request
At a high level the Clickscrow token (CSW) is designed to serve as a unit of account within the clickscrow ecosystem. Due to the framework under which ERC-20 token operate, the CSW token functions strictly as a utility measure within the Clickscrow ecosystem and by no means a representation of any underlying ownership outside of the ecosystem. 

The tokens Utility can be broken down into 10 separate groups of functions:

1.	Staking within the Ecosystem
2.	Becoming an Arbitrator
3.	Arbitrator-User Incentive
4.	Cross Reputation Vouching
5.	Pooled Asset Distribution
6.	Limited Contract Funcționale
7.	Ecosystemic Priority
8.	Ecosystemic Discounts
9.	Partnership Incentive
10.	Proprietary Technology Access

The Utility of the CSW token in more depth:

1.  Staking within the ecosystem.
 Users will be able to stake tokens by locking them up in a contract within the Clickscrow ecosystem. By staking the CSW tokens, users are committing value to the network that additionally ties them to network activity and drive the systems consensus. Those that stake tokens automatically become low level arbitrators within the ecosystem that act as the dispute resolution layer for the ecosystem. Furthermore, staking tokens entitles the staker to future payouts denominated in CSW tokens.

2. Becoming an Arbitrator 
 Arbitrators within the clickscrow ecosystem serve as the neutral 3rd party which oversees resolution in the event of a dispute. Given that Arbitrators within the ecosystem receive a portion of the contracts deployment price, and are able to incentivize entities to select them for arbitrating; Users are able to create powerful professional reputations and stream of income for themselves by becoming Arbitrators. Because actors are locking up and committing value to the network it is in their own benefits to act honestly; in the event that actors act dishonestly their reputation and their stake is slashed. The slashed stake is then allocated to the Asset pool for distribution amongst other Arbitrators / stakers. Stakers are by no means forced to participate as Arbitrators, in which case they can opt out of the Arbitration status and reap the other benefits within the network.

3. Arbitrator-User Incentive
 Arbitrators within the ecosystem must have some way to present themselves to the users and convince  users to select them. While a great reputation will always be the deciding factor as to which arbitrator a user would likely be selecting; incentivization will serve as another avenue for decision making. Whenever an arbitrator is building up their reputation they will need some way to distinguish themselves and “micro-commit” to acting as a trusted resolving party. So whenever a user navigates through the Arbitrator catalogue and decides whom to trust, they are also exposed to a reverse incentive from part of the Arbitrator for selecting them. 

4. Arbitrator Vouching & Endorsement 
  As users and arbitrators become more well acquainted with one another and the system at large, Arbitrators of a certain grade will be able to open themselves to Vouching. Vouching is a process by which regular Users within the ecosystem lock-up their CSW tokens in the name of an Arbitrator. Doing so results in the Arbitrator Raking much higher and much faster. Moreover, it frees up some of the Arbitrators Locked up funds so that they may use it to enhance their incentive campaigns.

5. Pooled Asset Distribution.
 Within the CSW ecosystem exists an address that captures and pools a portion of all ecosystem activity (denominated in the CSW token). Everytime this pool gets filled, it is immediately distributed evenly amongst the Stakers within the network and the Reserve Fund. Due to the fact that many existing system implement similar structures that are bound by time, Clickscrow has decided that the Asset pool must not be static; thereby, it has implemented limitations on it that are lead by Asset quantity. For example, if the parameter for Pool distribution is 100,000 tokens, there can be no guarantee that it would fill at a predictable given rate. Therefore, The quantity parameter is backed by a time parameter (of approximately 1 week). 

6. Limited Contract Functionale
 Whenever utilizing the more advanced functional of the CSW ecosystem, such as the parameters within the Platinum contract, the interaction must be paid for in the native CSW token. Parameters such as, insurance, custom arbitrator, and so on are denominated in CSW token. Yes, while the payment method can be conducted in just about any currency, that payment will be funneled through the CSW token pool. Thereby, access to any extended utility is accessible through the CSW token, which when paid in anything other than the Token is at higher cost. 

7. Ecosystemic Priority
  Whenever navigating the Clickscrow environment and interacting with it, all transactions done through the CSW token are shuffled to the top of the queue and processed as first priority.  While all transactions that are not paid for in CSW are processed under the average GAS cost, those transactions that are paid for in CSW are processed under the highest maximum GAS cost; thereby prioritizing those contracts and guaranteeing no latency between contract agreement and deployment.  

8. Ecosystemic Discounts.
 The Clickscrow’s tool kits are priced at a base $1 and $30. Whenever deploying a contract, the involved parties have the option for which method of payment they want to use. Given that the CSW token is native to the CSW ecosystem, it should come as no surprise that any payment for service in the CSW token will result in a discounted price. The severity of discount will depend on the reputation of the entity that is involved in the deal. For instance, a user that has conducted 3 transactions and only paid for them in Ethereum would only receive a 5% lowered cost; meanwhile, a user who has 30 transactions and half have been paid for previously in CSW would be receiving a 10% discount. Of course many other metrics will influence the severity of cost savings, but for reasons of brevity, we will use the simplistic example above.

9. Partnership incentives.
Clickscrow intends to be building a wide network of partners through which to grow. Clickscrow will be  distributing it’s token across to those partners, which in turn will be utilizing the token as a form of reward or incentive on their platforms to their own native audiences. Moreover, the CSW token can be integrated and ultimately implemented as a tool within the partnering ecosystems.

10. Proprietary Technology Access
Clickcrow will be rolling out multitudes of adjacent and parallel technologies that will only be available for utilization before launch by CSW token holders. In addition to native technological access, partners involved with the CSW token ecosystem will be expected to implement functionale that is exclusively available through the CSW token.

# Source code
https://etherscan.io/address/0xeb342b37b897c7a2f451f39e0a6725461804b93d#code
# Disclosure policy
ainagul.mendagazieva@gmail.com
# Platform
Ethereum
# Number of lines: 
220

**Comment by danbogd** [comment]
Auditing time: 2 days.

**Comment by yuriy77k** [comment]
@danbogd NOT assigned. You can take "Low priority" request if not exist others requests.

**Comment by MrCrambo** [comment]
Auditing time is 1 day

**Comment by yuriy77k** [comment]
@MrCrambo assigned.

**Comment by MrCrambo** [comment]
My report is finished

**Comment by RideSolo** [comment]
Auditing time: 2 days.

**Comment by gorbunovperm** [comment]
Estimated auditing time is 2 days.

**Comment by yuriy77k** [comment]
@RideSolo @gorbunovperm assigned

**Comment by gorbunovperm** [comment]
My report is finished.

**Comment by yuriy77k** [comment]
# Clickscrow token (CSW) Security Audit Report

# 1. Summary

[Clickscrow token](https://etherscan.io/address/0xeb342b37b897c7a2f451f39e0a6725461804b93d#code) smart contract security audit report performed by [Callisto Security Audit Department](https://github.com/EthereumCommonwealth/Auditing)

> At a high level the Clickscrow token (CSW) is designed to serve as a unit of account within the clickscrow ecosystem. Due to the framework under which ERC-20 token operate, the CSW token functions strictly as a utility measure within the Clickscrow ecosystem and by no means a representation of any underlying ownership outside of the ecosystem.

	Symbol       : CSW
	Name         : Clicks
	Capped supply: 500,000,000
	Decimals     : 18 
	Standard     : ERC20

# 2. In scope

1. [Clickscrow Token](https://etherscan.io/address/0xeb342b37b897c7a2f451f39e0a6725461804b93d#code)

# 3. Findings

In total, **2 issues** were reported including:

- 2 low severity issues.

No critical security issues were found.

## 3.1. Known vulnerabilities of ERC-20 token

### Severity: low

### Description

1. It is possible to double withdrawal attack. More details [here](https://docs.google.com/document/d/1YLPtQxZu1UAvO9cZ1O2RPXBbT0mooh4DYKjA_jp-RLM/edit).

2. Lack of transaction handling mechanism issue. [WARNING!](https://gist.github.com/Dexaran/ddb3e89fe64bf2e06ed15fbd5679bd20)  This is a very common issue and it already caused millions of dollars losses for lots of token users! More details [here](https://docs.google.com/document/d/1Feh5sP6oQL1-1NHi-X1dbgT3ch2WdhbXRevDN681Jv4/edit).

### Recommendation

Add the following code to the `transfer(_to address, ...)` function:

```
require( _to != address(this) );

```

## 3.2. Allowance Decrease

### Severity: low

### Description

The value to be subtracted is decreased using safemath `sub` function meaning that if the value is higher than the remaining allowance the transaction will throw when it could be set to zero instead. multiple scenario can be imagined for the end user.

### Code snippet

```
    function decreaseAllowance(address spender, uint256 subtractedValue) public returns (bool) {
        _approve(msg.sender, spender, _allowed[msg.sender][spender].sub(subtractedValue));
        return true;
    }
```

### Recommendation

Check if the allowance is lower than the value to be subtracted and set the allowance to zero if the condition is met.

# 4. Conclusion

The audited smart contract can be deployed. Only low severity issues were found during the audit.

# 5. Revealing audit reports

https://gist.github.com/yuriy77k/969a1bbfdec932245e8237410953a81a

https://gist.github.com/yuriy77k/f815b599f5e79397f8af470071610138

https://gist.github.com/yuriy77k/780d7c35526b46301118980f62565f16
