### ISSUE TITLE
Multisender.app

### ISSUE THREAD

**Issue by carlossampol** [EthereumCommonwealth/Auditing#342]
# Audit request
Syndicates and Airdroppers, efficiently distribute massive batches of tokens and airdrops in a single click using multisender.app
https://multisender.app/
proposal#63
# Source code
https://github.com/rstormsf/multisender/tree/master/contracts/contracts
# Disclosure policy
https://t.me/MultiSender
# Platform
Ethereum
# Number of lines: 
391

**Comment by danbogd** [comment]
Auditing time: 3 days.

**Comment by danbogd** [comment]
My report is finished.

**Comment by yuriy77k** [comment]
@danbogd assigned

**Comment by moonstash** [comment]
What was the result of this audit? Any chance you'd care to share :)

**Comment by RasstCrypt** [comment]
> # Audit request
> Syndicates and Airdroppers, efficiently distribute massive batches of tokens and airdrops in a single click using multisender.app
> https://multisender.app/
> proposal#63
> # Source code
> https://github.com/rstormsf/multisender/tree/master/contracts/contracts
> # Disclosure policy
> https://t.me/MultiSender
> # Platform
> Ethereum
> # Number of lines: 
> 391

**Comment by hsghn** [comment]
Halo
