### ISSUE TITLE
DEX.top

### ISSUE THREAD

**Issue by MillianoConti** [EthereumCommonwealth/Auditing#346]
# Audit request
Your deposits directly go to the smart contract, and your orders are signed by your private key. The smart contract ensures that your orders are executed or expire correctly and that withdrawals from your balance always go back to your wallet. DEx.top has no custody of or access to your funds, nor your private key. It is just a service of order matching and a source of liquidity.
https://dex.top/

# Source code
https://github.com/dexDev/DEx.top/tree/master/smart-contract

# Disclosure policy

https://0.plus/#/DExtop_Chinese

# Contact information (optional)

bd@dex.ceo,

# Platform

Eth
# Number of lines: 
412

**Comment by danbogd** [comment]
Auditing time: ~ 3 days.

**Comment by danbogd** [comment]
My report is finished.

**Comment by yuriy77k** [comment]
@danbogd assigned.
