### ISSUE TITLE
ERC20Faucet

### ISSUE THREAD

**Issue by MillianoConti** [EthereumCommonwealth/Auditing#347]
# Audit request
As a developer or a user, sometimes there is a need to quickly get ERC20 to hack around. This app allows you to get erc20 token in 1 click
https://erc20faucet.com/

# Source code

https://github.com/peppersec/erc20faucet/tree/master/contracts

# Disclosure policy

https://t.me/erc20Faucet

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

# Platform

Eth

**Comment by yuriy77k** [comment]
Simple token for testing purpose, based on "openzeppelin-solidity" code. 
What we have to search for at this contract? It just for testing.

**Comment by Dexaran** [comment]
@MillianoConti if https://t.me/erc20Faucet is a contact information then it should be suited in the `Contact information` section instead of disclosure policy.

**Comment by Dexaran** [comment]
@MillianoConti I can't access the source code by this link: https://github.com/peppersec/erc20faucet/tree/master/contracts
