### ISSUE TITLE
iframe wallets

### ISSUE THREAD

**Issue by moodysalem** [EthereumCommonwealth/Auditing#351]
# Audit request

This is not a smart contract, but rather, a Web3 provider that allows a DAPP in an iframe to communicate with a provider from the parent window. The goal is for individual DAPPs to include this script in their DAPP to support Ethvault.xyz and other iframe wallets.

# Source code

The provider
https://github.com/ethvault/iframe-provider

A polyfill that automatically installs the provider to `window.web3` and `window.ethereum`
https://github.com/ethvault/iframe-provider-polyfill

# Disclosure policy

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

Project URL: ethvault.xyz
Twitter: @ethvault
Email: moody@ethvault.xyz

# Platform

All modern browsers

**Comment by Dexaran** [comment]
@moodysalem we usually conduct audits of smart-contracts, but not audits of smart-contract interfaces.

We will perform an audit of Ethvault registrar (https://github.com/EthereumCommonwealth/Auditing/issues/350), but I need to notify you that we have a large smart-contract audit in queue and it will take time to proceed with your request.

**Comment by yuriy77k** [comment]
We don't make free audits anymore.
