### ISSUE TITLE
ethplode.org

### ISSUE THREAD

**Issue by carlossampol** [EthereumCommonwealth/Auditing#354]
# Audit request
https://etherscan.io/address/0xe0c6ce3e73029f201e5c0bedb97f67572a93711c

0.5% coin burn every transaction.

https://ethplode.org
# Source code
https://github.com/ETHplode/ETHplode-Source
# Disclosure policy
remzi@ethplode.org
# Platform
Ethereum
# Number of lines: 
110

**Comment by danbogd** [comment]
Auditing time: 1 day.

**Comment by danbogd** [comment]
My report is finished.

**Comment by yuriy77k** [comment]
@danbogd assigned

**Comment by MrCrambo** [comment]
Auditing time is 1 day

**Comment by yuriy77k** [comment]
@MrCrambo assigned.

**Comment by MrCrambo** [comment]
My report is finished

**Comment by RideSolo** [comment]
Auditing time: 1 day

**Comment by yuriy77k** [comment]
@RideSolo assigned

**Comment by yuriy77k** [comment]
The contract contains a high severity security issue. The developer is informed about it.
