### ISSUE TITLE
aftershock.vip

### ISSUE THREAD

**Issue by carlossampol** [EthereumCommonwealth/Auditing#355]
# Audit request
This contract was built as an experimental deflationary staking token on the ETH network.

There is a 6% transfer fee on each transfer. 3% is burned and the other 3% rewarded to SHOCK holders proportionate to their SHOCK holdings.

Users are able to claim their rewards from the smart contract by selecting the payout rewards function.

They are also able to view their current unpaid rewards from the contract.

The fullUnitsStaked_total is the total supply minus the creator, contract and excluded from staking addresses.

Example

SHOCK holder 1 holds 1000

fullUnitsstaked_total = 10000

Then Holder 1 is eliglable for 10% of the 3% SHOCK sent to the contract from that transaction.

So if 1000 SHOCK are transferred, 60 SHOCK are taken as a fee. 30 SHOCK to the burn address and 30 SHOCK to the contract for holders.

Holder 1 is now eligible to claim 10% of the 30 SHOCK sent to the contract in that transaction.
# Source code
https://etherscan.io/address/0x11ded8addda881f700fbda2fe2030656289322a3#code
# Disclosure policy
info@aftershock.vip
# Platform
Ethereum
# Number of lines: 
362

**Comment by danbogd** [comment]
Auditing time: ~ 3 days.

**Comment by yuriy77k** [comment]
@danbogd assigned

**Comment by danbogd** [comment]
My report is finished.

**Comment by Aftershock11** [comment]
> My report is finished.

Please submit the report to info@aftershock.vip. Thank you.

**Comment by MrCrambo** [comment]
Auditing time is 2 days

**Comment by yuriy77k** [comment]
@MrCrambo assigned

**Comment by MrCrambo** [comment]
My report is finised
