### ISSUE TITLE
Talium

### ISSUE THREAD

**Issue by carlossampol** [EthereumCommonwealth/Auditing#357]
# Audit request
I'm trying to build smart contract around ERC1400.
My smart contracts look like the source code provided under (it's based on it, within some changes).

I'm curious how the based code is good or not, since it wasn't audited yet.

Thank you !
# Source code
https://github.com/SecurityTokenStandard/EIP-Spec/tree/master/contracts
# Disclosure policy
brice.faller@talium.fr
# Platform
Ethereum
# Number of lines:
572

**Comment by MrCrambo** [comment]
Auditing time is 2 days

**Comment by yuriy77k** [comment]
@MrCrambo assigned.

**Comment by MrCrambo** [comment]
My report is finished

**Comment by yuriy77k** [comment]
@danbogd assigned

**Comment by yuriy77k** [comment]
We don't make free audits anymore.
