### ISSUE TITLE
BlockTix

### ISSUE THREAD

**Issue by MillianoConti** [EthereumCommonwealth/Auditing#359]
# Audit request
Blocktix provides event promoters with a ticket exchange that enables full control of primary and secondary market ticket distribution.
https://blocktix.io/
# Source code

https://github.com/blocktix/contracts/tree/master/contracts

# Disclosure policy

https://discordapp.com/invite/4A8JW3K

# Contact information (optional)
https://www.reddit.com/r/blocktix/
https://www.facebook.com/blocktix/

# Platform

Eth
# Number of lines: 
252

**Comment by MrCrambo** [comment]
Auditing time is 2 days

**Comment by danbogd** [comment]
Auditing time:  3 days.

**Comment by MrCrambo** [comment]
My report is finished

**Comment by danbogd** [comment]
My report is finished.

**Comment by yuriy77k** [comment]
@MrCrambo @danbogd assigned

**Comment by yuriy77k** [comment]
We don't make free audits anymore.
