### ISSUE TITLE
Callisto Cold Staking [BETA] [Testnet 3.0]

### ISSUE THREAD

**Issue by yograterol** [EthereumCommonwealth/Auditing#36]
# Audit request

Cold Staking smart contract is deployed in Callisto Testnet 3.0. The HF1 will be in November; we need to catch security issues from now.

More info about the smart contract: https://whitepaper.callisto.network

# Source code

https://github.com/EthereumCommonwealth/Cold-staking/tree/compiler_bug

# Disclosure policy

yograterol@callisto.network

# Platform

CLO

**Comment by RideSolo** [comment]
Auditing time: 2 days.

**Comment by gorbunovperm** [comment]
Estimated auditing time is 3 days.

**Comment by yuriy77k** [comment]
# 1. Summary

This document is a security audit report performed by [RideSolo](https://github.com/RideSolo), where [CLO Cold Stacking]() has been reviewed.

# 2. In scope

- [ColdStaking.sol](https://github.com/EthereumCommonwealth/Cold-staking/blob/compiler_bug/ColdStaking.sol) github commit hash dde007940a04c6d05b6d63732f1c61a424ecae71.

# 3. Findings

**2 issues** were reported including:

- 1 high severity issues.

- 1 medium severity issues.

## 3.1. Init Block Reinitialisation

### Severity: High

### Description

Multiple call of `start_staking` will replace the value of `init_block` with the current block number, therefore setting the value returned by`stake_reward` to zero making the staker lose all his previous possible reward.

### Code snippet

https://github.com/EthereumCommonwealth/Cold-staking/blob/dde007940a04c6d05b6d63732f1c61a424ecae71/ColdStaking.sol#L51

https://github.com/EthereumCommonwealth/Cold-staking/blob/dde007940a04c6d05b6d63732f1c61a424ecae71/ColdStaking.sol#L46#L61

https://github.com/EthereumCommonwealth/Cold-staking/blob/dde007940a04c6d05b6d63732f1c61a424ecae71/ColdStaking.sol#L39#L44

## 3.1. Transaction Ordering Dependent Reward  

### Severity: medium

### Description

Following the white paper "ROI: ​Dynamic. Depends on the amount of CLO that is engaged in cold staking​ ​at the moment of reward claiming​." this will create a race condition where the reward will be randomly dependent on stakers claims. This issue can be considered by some staker not fair, especially with the appreance of staking gaps and a non equal distribution of the cold staking treasury over the time.
