### ISSUE TITLE
U-Network

### ISSUE THREAD

**Issue by MillianoConti** [EthereumCommonwealth/Auditing#360]
# Audit request
U Network is a decentralized content asset storage, notarization, distribution, publishing and valuation network based on the blockchain.
https://u.network/
# Source code

https://github.com/U-Network/UNetwork/tree/master/smartContract

# Disclosure policy

https://discordapp.com/invite/su928KQ

# Contact information (optional)

https://t.me/UNetwork
https://www.reddit.com/r/UNetwork/

# Platform

Eth
# Number of lines: 
343

**Comment by MrCrambo** [comment]
Auditing time is 2 days

**Comment by yuriy77k** [comment]
We don't make free audits anymore.
