### ISSUE TITLE
HEX.win

### ISSUE THREAD

**Issue by carlossampol** [EthereumCommonwealth/Auditing#365]
# Audit request
HEX.win Dense summary:  First Blockchain CD. Be early (20%), Referer(20%), or Referred(10%). Stake longer or larger (up to 310% shares). For first 50 weeks: Free, if you hold BTC at snapshot; Unclaimed coins paid to stakers week 50; The % claimed coins and addresses both increase pay by the % ; Copy of unclaimed HEX available daily: Send ETH to contract, your % ETH by end of day = your % HEX. Origin gets copy of bonuses. Base claims, interest, and adoption amplifier aren't bonuses therefore it gets no copy from them. Free claims are autostaked 90% min 50 weeks.

Verbose contract description:  https://docs.google.com/document/d/1P0ZDaBQx4ghkdX5IUwZb1n8ThvYf7i22MSt9Gm00JRU/ 

Tests passed: Slither, MythX, Securify

# Source code
https://github.com/yuriy77k/contract-staging 
(copied from https://gitlab.com/bitcoinhex/contract-staging )
# Disclosure policy
RichardHeartAuthor@gmail.com
# Platform
Ethereum
# Number of lines: 
1420

**Comment by MrCrambo** [comment]
Auditing time is 4 days

**Comment by yuriy77k** [comment]
@MrCrambo assigned

**Comment by danbogd** [comment]
Auditing time is 3 days.

**Comment by yuriy77k** [comment]
@danbogd assigned.

**Comment by MrCrambo** [comment]
My report is finished

**Comment by RideSolo** [comment]
Auditing time 4 days.

**Comment by yuriy77k** [comment]
@RideSolo assigned

**Comment by danbogd** [comment]
My report is finished.

**Comment by RideSolo** [comment]
@yuriy77k Audit paused.

**Comment by Dexaran** [comment]
What is the current status of this audit request? @yuriy77k @RideSolo

**Comment by yuriy77k** [comment]
@Dexaran the audit paused. As far as we do not pay for audit from the Treasury, we may close it.
