### ISSUE TITLE
eth777.io

### ISSUE THREAD

**Issue by carlossampol** [EthereumCommonwealth/Auditing#367]
# Audit request
Hello, I found this smart contract offering generous returns. Would you perform an audit of this? So we can be safe. Thank you.

https://www.eth777.io/
# Source code
https://www.eth777.io/
# Disclosure policy
henri99@gmail.com 
# Platform
Callisto Network

**Comment by yuriy77k** [comment]
We did not provide a security audit for any kind of Ponzi schema.
