### ISSUE TITLE
Inxight

### ISSUE THREAD

**Issue by MillianoConti** [EthereumCommonwealth/Auditing#369]
# Audit request
The InXight app, developed and powered by Scanetchain, can digitally recognize any object, brand, and image using AR technology both offline and online, without any additional equipment. 
http://www.inxight.io/

# Source code

https://github.com/Scanetchain/Scanetchain-ERC20-Token/tree/master/Contracts

# Disclosure policy

https://t.me/scanetchain

# Contact information (optional)

https://twitter.com/Scanetchain_SWC
https://www.facebook.com/Scanetchain.io

# Platform

Eth

**Comment by yuriy77k** [comment]
@MillianoConti both contracts create the "Scanetchain" (SWC) token. Which one do we audit?

**Comment by yuriy77k** [comment]
Duplicate https://github.com/EthereumCommonwealth/Auditing/issues/377
