### ISSUE TITLE
UCOIN

### ISSUE THREAD

**Issue by carlossampol** [EthereumCommonwealth/Auditing#371]
# Audit request
This smart-contract ti to deploy our UCOIN, a digital currency one-stop ecosystem based on the Ethereum
blockchain technology  that provides its token holders and crypto/fiat users a diversified digital and global
financial service network for their daily life transaction. UCoin financial platform is powered by DOSH and built on decentralized blockchain technology and utilizes microservice architecture to ensure limitless scalability. For more details: https://ucoincurrency.io/
# Source code
https://github.com/ucoincurrency/UCOIN/blob/master/UCOIN_Smart_Contract.sol
# Disclosure policy
juan.velez@ucoincorp.com
# Number of lines: 
127
# Platform
Ethereum

**Comment by MrCrambo** [comment]
Auditing time is 1 day

**Comment by yuriy77k** [comment]
@MrCrambo assigned

**Comment by MrCrambo** [comment]
My report is finished

**Comment by danbogd** [comment]
Auditing time is 1 day.

**Comment by yuriy77k** [comment]
@danbogd assigned

**Comment by danbogd** [comment]
My report is finished.

**Comment by RideSolo** [comment]
audit time: 1 day

**Comment by yuriy77k** [comment]
@RideSolo assigned

**Comment by yuriy77k** [comment]
The contract contains a high severity security issue. The developer is informed about it.
