### ISSUE TITLE
LunchMoneyToken

### ISSUE THREAD

**Issue by MillianoConti** [EthereumCommonwealth/Auditing#374]
# Audit request
Restaurant P.I. aims to improve the customer experience at restaurants and eateries world wide by auditing customer reviews and offering motivators. By screening for phony and low-quality reviews ,Restaurant P.I. is setting the bar high for review and service ratings. All users who submit feeback via the platform must also provide proof of visit by uploading a picture of their reciept. Users will recieve Lunch Money (LMY), after their feedback has been audited and appoved by administrators. Users can hold, trade or swap their earned crypto rewards with Bitcoin, Ethereum and other crypto via the platform’s instant exchange.

https://www.lunchmoney.io/

# Source code

https://github.com/LunchMoneyToken/LunchMoney

# Disclosure policy

support@lunchmoney.io

# Contact information (optional)
https://twitter.com/LunchToken
https://www.facebook.com/LunchMoneyToken/
https://www.reddit.com/r/lunchmoney_io/
https://t.me/lunchmoneytoken

# Platform

Eth
# Number of lines: 
121

**Comment by yuriy77k** [comment]
We don't make free audits anymore.
