### ISSUE TITLE
Stox

### ISSUE THREAD

**Issue by MillianoConti** [EthereumCommonwealth/Auditing#375]
# Audit request
Stox is the Ethereum-Based Blockchain Prediction Markets Platform
Build new markets, make predictions, trade with peers and make profit on one decentralised platform.
https://www.stox.com/

# Source code

https://github.com/stx-technologies/stox-token/blob/master/contracts/StoxSmartTokenSale.sol

# Disclosure policy

Standard disclosure policy

# Contact information (optional)
https://t.me/joinchat/DByWw0Pnq9BAy4FqPv_Lyg
https://twitter.com/stx_coin
https://www.reddit.com/r/STOX/
https://www.facebook.com/STXCoin/

# Platform

Eth

**Comment by yuriy77k** [comment]
The provided contract was used for crowd sale STOX tokens. The sales finished a long time ago, therefore no need to audit that contract.
