### ISSUE TITLE
Decentralized News Network

### ISSUE THREAD

**Issue by MillianoConti** [EthereumCommonwealth/Auditing#381]
# Audit request
DNN, or Decentralized News Network, is a news platform, combining news creation with decentralized networks to deliver factual content, curated by the community.
https://dnn.media/

# Source code

https://github.com/dnnmedia/dnn_tde_contracts/tree/master/contracts

# Disclosure policy

Standard disclosure policy

# Contact information (optional)
https://www.reddit.com/r/DNNMedia/
https://t.me/DNNMedia
https://twitter.com/DNN_Blockchain
https://www.facebook.com/DNNBlockchain

# Platform

Eth

**Comment by yuriy77k** [comment]
We don't make free audits anymore.
