### ISSUE TITLE
Armacoin GZM

### ISSUE THREAD

**Issue by MillianoConti** [EthereumCommonwealth/Auditing#382]
# Audit request
Armacoin GZM coin is specially designed for advertising companies, various media, various greetings registered on the basis of blockchain.
https://armacoin.info/

# Source code

https://github.com/dimabarsu/GZM-Armacoin

# Disclosure policy

Standard disclosure policy

# Contact information (optional)
https://twitter.com/ArmacoinG
https://www.facebook.com/armacoin.gzm
https://t.me/ArmacoinGZM

# Platform

Eth

**Comment by yuriy77k** [comment]
No contact information.
