### ISSUE TITLE
Governance & Cold Staking v2

### ISSUE THREAD

**Issue by Dexaran** [EthereumCommonwealth/Auditing#388]
# Audit request

- Cold Staking contract v2 - core contract of Callisto Network

- Governance System contract - core contract of Callisto Network

The governance system smart-contract is an implementation of the [decentralized governance system proposal](https://github.com/EthereumCommonwealth/Roadmap/issues/53). It is intended to enable Callisto community members to (1) submit proposals and (2) vote proposals. Voting requires a community member to be Cold Staker at the same moment. Cold Staking v2 will now support functions to interact with the governance system when the Staker is updating his(her) deposit.

You can read this explanational articles for better understanding of the governance system and Cold Staking contracts:

- [Governance and Cold Staking update](https://medium.com/@dexaran820/callisto-treasury-governance-system-and-cold-staking-update-2dc1b13f5ad5)

- [Voting/Submitting proposals through contract](https://medium.com/@dexaran820/callisto-governance-system-contract-guide-8887b2425f8b)

# Source code

- Governance: https://github.com/EthereumCommonwealth/Governance-System/blob/master/TreasuryGovernance.sol

- Cold Staking v2: https://github.com/EthereumCommonwealth/Governance-System/blob/master/staking_contract/ColdStaking_v2.sol

# Disclosure policy

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Platform

CLO

# Number of lines: 
634

**Comment by RideSolo** [comment]
Auditing time: 2 days.

**Comment by gorbunovperm** [comment]
Estimated auditing time is 4 days.

**Comment by RideSolo** [comment]
@Dexaran I have created a pull request on Governance-System to apply various fixes on the staking contract since I wasn't aware of the audit previously.
https://github.com/EthereumCommonwealth/Governance-System/pull/2

**Comment by MrCrambo** [comment]
Estimated auditing time is 4 days.

**Comment by yuriy77k** [comment]
@MrCrambo assigned
