### ISSUE TITLE
NUO NETWORK: a debt marketplace that connects lenders and borrowers from around the world using smart contracts

### ISSUE THREAD

**Issue by Cryptogeek20** [EthereumCommonwealth/Auditing#393]
# Audit request

Nuo Network, a debt marketplace that connects lenders and borrowers from around the world using smart contracts.

Backed by ConsenSys Ventures, Nuo Network aims to enable global cross border lending with it's decentralised debt products. Currently, it provides a way for lenders to pool their tokens and earn interest on their token reserves proportionally. This reserve pooling ensures instant disbursal for crypto collateral backed loans. It also offers margin trading with 3x leverage and provides instant liquidity to go long or short on Bitcoin, Ether and select ERC20 tokens through decentralized exchanges like Kyber and Uniswap.

Nuo Network enables global lending and borrowing using smart contracts and their contracts are open source and available on Github and verifiable on Etherscan.‍

More on the Nuo Network
Nuo Network heavily leverages web3 infrastructure and projects including: Uniswap, Metamask, Maker, 0x, Kyber, Open Zeppelin, Gnosis, Truffle, and Infura.

Nuo Network also places heavy emphasis on building a seamless user experience. In order to deliver a web2-like experience to their web3 application, Nuo uses tools such as MetaMask, which allows users to access web3 through their browser, and meta transactions, which abstracts gas fees and other elements of the blockchain.

# Source code

https://github.com/NuoNetwork/nuo-audited-contracts
# Disclosure policy

Public, since they avoid to publish the audit report
... provide your conditions for publishing the report or leave only standard disclosure policy link ...

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).
[nuo-audited-contracts-master.zip](https://github.com/EthereumCommonwealth/Auditing/files/3638846/nuo-audited-contracts-master.zip)

.

# Platform

It is live on Ether

**Comment by yuriy77k** [comment]
Please, write your email for contact.

**Comment by Cryptogeek20** [comment]
photolula1@gmail.com

**Comment by Cryptogeek20** [comment]
> Please, write your email for contact.
photolula1@gmail.com
