### ISSUE TITLE
ERC20 and Crowdsale

### ISSUE THREAD

**Issue by yuriy77k** [EthereumCommonwealth/Auditing#4]
# Audit request

ERC20andCrowdsale alow to create ERC20 token and sale it at five stages with a different rate of exchange at each stage.

# Source code

https://github.com/SamueleA/ERC20andCrowdsale

# Disclosure policy

Publish everything.

# Platform

ETC / ETH

**Comment by MrCrambo** [comment]
Auditint time: 7 days

**Comment by RideSolo** [comment]
Auditing time: 4 days

**Comment by yuriy77k** [comment]
@RideSolo assigned.

**Comment by gorbunovperm** [comment]
@yuriy77k Is this request approved? The corresponding label is missing.

**Comment by yuriy77k** [comment]
@gorbunovperm yes, it's approved.

**Comment by gorbunovperm** [comment]
Estimated auditing time is 7 days.

**Comment by yuriy77k** [comment]
@gorbunovperm assigned.

**Comment by MrCrambo** [comment]
@yuriy77k report done.

**Comment by alexo18** [comment]
Auditing time: 5 days

**Comment by yuriy77k** [comment]
@MrCrambo assigned.

**Comment by yuriy77k** [comment]
@alex18 assigned.

**Comment by Dexaran** [comment]
Are the reports finished?
If yes, then @yuriy77k should publish reports and submit a conclusion.

**Comment by yuriy77k** [comment]
@Dexaran i'll wait for last raport fot conclusion.
