### ISSUE TITLE
DACom PROTOCOL

### ISSUE THREAD

**Issue by yuriy77k** [EthereumCommonwealth/Auditing#42]
# Audit request

The goal - to win money. You can enter with any amount and on the next day get more or less. If you win, the starting amount can be multiplied by many times. And if it is a loss, the value of it is always fixed

# Source code

https://github.com/TravelChain/protocol
**No source code**

# Disclosure policy

dacom.dark.sun@gmail.com

# Platform

EOS

# Complexity

Low

**Comment by cryptorazy** [comment]
Auditing time: 3 days.

**Comment by yuriy77k** [comment]
@cryptorazy assigned

**Comment by yuriy77k** [comment]
no source code
