### ISSUE TITLE
QKC POSW staking contract

### ISSUE THREAD

**Issue by bukum86** [EthereumCommonwealth/Auditing#421]
# Audit request

ETH combatible smart contract for staking pool on QKC blockchain. Stakers should be able to deposit and withdraw coins to staking contract and gain certen benefits for their stakes. 

# Source code

https://github.com/QuarkChain/quarkchain-contracts/blob/master/contracts/StakingPool.sol

# Disclosure policy

Please notify me privately if any issues are found.

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

Bukum86@gmail.com

https://quarkchain.io/

# Platform

QKC

**Comment by yuriy77k** [comment]
@bukum86, unfortunately, we don't provide free audit any more. 
We can order the audit of your smart contract for 577 USD fee. 
The payment may be in CLO, ETH, ETC (by current exchange rate).

**Comment by bukum86** [comment]
Hello, thank you for your info. After paying above mentioned fee it means that contract will be audited under high priority as well?

**Comment by yuriy77k** [comment]
Yes, contract will  be audited under high priority.
