### ISSUE TITLE
TheWALL v2

### ISSUE THREAD

**Issue by yuriy77k** [EthereumCommonwealth/Auditing#424]
# Audit request

**Please, read my comments https://github.com/isvirin/TheWall/blob/master/notes_about_audit_for_163e39b888c2364c708139d0916db6e63c4acc59.md first.**

The Million Dollar Homepage on a blockchain. 
We have finished testing our contracts prepared them to audit. We had to separate it into 5 contracts because of blocksize limitations. 
There are
* thewall.sol
* thewallbeneficiaries.sol
* thewallcore.sol
* thewallusers.sol
* thewallcoupons.sol
 
Deploy procedure:
depoloy TheWallCoupons
deploy TheWallCore(TheWallCoupons)
TheWallCoupons->addWhitelistAdmin(TheWallCore)
deploy TheWall(TheWallCore)
TheWallCore->addWhitelistAdmin(TheWall)
deploy TheWallBeneficiaries
TheWallCore->setFundsReceived(TheWallBeneficiaries)

Project homepage - https://thewall.global

# Source code
https://github.com/isvirin/TheWall
# Disclosure policy
please notify us privately if critical vulnerabilities are found. email: i.svirin@nordavind.ru
# Platform
Ethereum
## Contact
i.svirin@nordavind.ru
## Budget
[3.05 Ether](https://etherscan.io/tx/0xfffd5025f3b6fa7dee4e59d5391c9c47acaa95c9e0ff98aef4ac7342d49cc53c)
Previous audit https://github.com/EthereumCommonwealth/Auditing/issues/416#issuecomment-574624421
Please, read [notes about audit](https://github.com/isvirin/TheWall/blob/master/notes_about_audit_for_163e39b888c2364c708139d0916db6e63c4acc59.md)

**Comment by MrCrambo** [comment]
Auditing time 4 days starting from tomorrow.

**Comment by yuriy77k** [comment]
@MrCrambo assigned

**Comment by gorbunovperm** [comment]
Estimated auditing time is 4 days.

**Comment by yuriy77k** [comment]
@gorbunovperm assigned

**Comment by RideSolo** [comment]
Estimated audit time: 4 days

**Comment by yuriy77k** [comment]
@RideSolo assigned

**Comment by danbogd** [comment]
Auditing time is 4 days.

**Comment by yuriy77k** [comment]
@danbogd assigned

**Comment by danbogd** [comment]
My report is finished.

**Comment by gorbunovperm** [comment]
My report is finished.

**Comment by yuriy77k** [comment]
# TheWALL v2 Security Audit Report

# 1. Summary

[TheWALL v2](https://thewall.global/) smart contract security audit report performed by [Callisto Security Audit Department](https://github.com/EthereumCommonwealth/Auditing)

# 2. In scope

Commit hash 8bd03c94dfc8ad9e1429b48da6cf3b51a7e59f19.

- [thewall.sol](https://github.com/isvirin/TheWall/blob/8bd03c94dfc8ad9e1429b48da6cf3b51a7e59f19/thewall.sol).
- [thewallbeneficiaries.sol](https://github.com/isvirin/TheWall/blob/8bd03c94dfc8ad9e1429b48da6cf3b51a7e59f19/thewallbeneficiaries.sol).
- [thewallcore.sol](https://github.com/isvirin/TheWall/blob/8bd03c94dfc8ad9e1429b48da6cf3b51a7e59f19/thewallcore.sol).
- [thewallcoupons.sol](https://github.com/isvirin/TheWall/blob/8bd03c94dfc8ad9e1429b48da6cf3b51a7e59f19/thewallcoupons.sol).
- [thewallusers.sol](https://github.com/isvirin/TheWall/blob/8bd03c94dfc8ad9e1429b48da6cf3b51a7e59f19/thewallusers.sol).

# 3. Findings

In total, **5 issues** were reported including:


- 1 medium severity issues.

- 2 low severity issues.

- 2 owner privileges (the ability of an owner to manipulate contract, may be risky for investors).

No critical security issues were found.

## 3.1 Cluster Size

### Severity: medium

### Description

The issue described [here](https://gist.github.com/RideSolo/6803297f5bd12bca834269c2dea3e88f#31-cluster-size) is still applicable, if a user wants to remove an area from the cluster that is located in the end of the cluster array, then it will be impossible since the array size might be too large.

The loop does not require the user to go through the full array, but like this the user will be forced to remove areas in the beginning of the cluster (even if he wants to keep them) just to remove an area in the latest positions, then add them back later on.

### Code snippet

https://github.com/ridesoloAudit/TheWall/blob/8bd03c94dfc8ad9e1429b48da6cf3b51a7e59f19/thewallcore.sol#L422

## 3.2 Premium Computing

### Severity: low

### Description

The frequency at with the [commitSecret](https://github.com/ridesoloAudit/TheWall/blob/8bd03c94dfc8ad9e1429b48da6cf3b51a7e59f19/thewallcore.sol#L145) and [updateSecret](https://github.com/ridesoloAudit/TheWall/blob/8bd03c94dfc8ad9e1429b48da6cf3b51a7e59f19/thewallcore.sol#L153) is called is important to the users. If a user that created new area want to rent or sell it and the owner didn't call `commitSecret` for his hash then [isPremium](https://github.com/ridesoloAudit/TheWall/blob/8bd03c94dfc8ad9e1429b48da6cf3b51a7e59f19/thewallcore.sol#L347) will return false, resulting in a loss of 30% (fee charged) even if his nonce and secret will give him a premium area. If the secret is committed later, a possible new owner will have access to the premium privilege.

### Recommendation

- If commit secret periodically, then put the schedule on the website to inform users when they may get Premium.
- Lock the sell and rent functionalities and unlock them after the secret commit.
- Automate the process using an oracle callback such as oracalize or chainlink.

## 3.3 Zero Address Check

### Severity: low

### Description

- Check coupons contract address to be different than zero inside the [constructor](https://github.com/isvirin/TheWall/blob/8bd03c94dfc8ad9e1429b48da6cf3b51a7e59f19/thewallusers.sol#L54) of `TheWallUsers`.
- Check the updated coupons contract address to be different than zero [here](https://github.com/RideSolo/TheWall/blob/163e39b888c2364c708139d0916db6e63c4acc59/thewallusers.sol#L59#L62).

## 3.4. Owner privileges

### Severity: owner privileges

### Description

The owner has rights that can harm users:

1. Area price change.
2. Make wall size unlimited greater.

### Code snippet

* [1](https://github.com/isvirin/TheWall/blob/8bd03c94dfc8ad9e1429b48da6cf3b51a7e59f19/thewallcore.sol#L134)
* [2](https://github.com/isvirin/TheWall/blob/8bd03c94dfc8ad9e1429b48da6cf3b51a7e59f19/thewallcore.sol#L127-L128)


# Conclusion

There are no critical issues. The highlighted issues have to be fixed.

# 5. Revealing audit reports

https://gist.github.com/RideSolo/4eaceb82481bef06f1b48a2a6d2cf3e0

https://gist.github.com/gorbunovperm/7859498d0f78b0df0966961f63e91232

https://gist.github.com/MrCrambo/f207b7ff56d7a6b0e988003b3dec4c52

https://gist.github.com/danbogd/6ea8a1e09b556554b72f5c5a67603088
