### ISSUE TITLE
TheWALL v3

### ISSUE THREAD

**Issue by yuriy77k** [EthereumCommonwealth/Auditing#425]
# Audit request

There were changed two files. The last commits: https://github.com/isvirin/TheWall/commit/4d7b98e06def9a605aba06663d5c90d5a5e55c54

The Million Dollar Homepage on a blockchain. 
We have finished testing our contracts prepared them to audit. We had to separate it into 5 contracts because of blocksize limitations. 
There are
* thewall.sol
* thewallbeneficiaries.sol
* thewallcore.sol
* thewallusers.sol
* thewallcoupons.sol
 
Deploy procedure:
depoloy TheWallCoupons
deploy TheWallCore(TheWallCoupons)
TheWallCoupons->addWhitelistAdmin(TheWallCore)
deploy TheWall(TheWallCore)
TheWallCore->addWhitelistAdmin(TheWall)
deploy TheWallBeneficiaries
TheWallCore->setFundsReceived(TheWallBeneficiaries)

Project homepage - https://thewall.global

# Source code
https://github.com/isvirin/TheWall
# Disclosure policy
please notify us privately if critical vulnerabilities are found. email: i.svirin@nordavind.ru
# Platform
Ethereum
## Contact
i.svirin@nordavind.ru
## Budget
[2.0 Ether](https://etherscan.io/tx/0x8ef466174ce311bfbbfad2df6e2ad933a4f34e8c83c1926df8a79d6a7b4f1141)
Previous audit https://github.com/EthereumCommonwealth/Auditing/issues/424#issuecomment-578523941

**Comment by danbogd** [comment]
Auditing time: ~5 days.

**Comment by yuriy77k** [comment]
@danbogd assigned

**Comment by MrCrambo** [comment]
Auditing time is 4 days.

**Comment by yuriy77k** [comment]
@MrCrambo assigned

**Comment by gorbunovperm** [comment]
Estimated auditing time is 5 days.

**Comment by yuriy77k** [comment]
@gorbunovperm assigned

**Comment by RideSolo** [comment]
auditing time: 5 days

**Comment by yuriy77k** [comment]
@RideSolo assigned

**Comment by gorbunovperm** [comment]
My report is finished.

**Comment by danbogd** [comment]
My report is finished.

**Comment by yuriy77k** [comment]
# TheWALL v3 Security Audit Report

# 1. Summary

[TheWALL v3](https://thewall.global/) smart contract security audit report performed by [Callisto Security Audit Department](https://github.com/EthereumCommonwealth/Auditing)

# 2. In scope

Commit hash 4d7b98e06def9a605aba06663d5c90d5a5e55c54.

- [thewall.sol](https://github.com/isvirin/TheWall/blob/4d7b98e06def9a605aba06663d5c90d5a5e55c54/thewall.sol).
- [thewallbeneficiaries.sol](https://github.com/isvirin/TheWall/blob/4d7b98e06def9a605aba06663d5c90d5a5e55c54/thewallbeneficiaries.sol).
- [thewallcore.sol](https://github.com/isvirin/TheWall/blob/4d7b98e06def9a605aba06663d5c90d5a5e55c54/thewallcore.sol).
- [thewallcoupons.sol](https://github.com/isvirin/TheWall/blob/4d7b98e06def9a605aba06663d5c90d5a5e55c54/thewallcoupons.sol).
- [thewallusers.sol](https://github.com/isvirin/TheWall/blob/4d7b98e06def9a605aba06663d5c90d5a5e55c54/thewallusers.sol).

# 3. Findings

In total, **2 issues** were reported including:

- 2 owner privileges.

No critical security issues were found.

## 3.1. Premium Computing

### Severity: owner privileges

### Description

The owner can `commitSecret` with various frequency or don't commit at all.
The frequency at with the [`commitSecret`](https://github.com/ridesoloAudit/TheWall/blob/4d7b98e06def9a605aba06663d5c90d5a5e55c54/thewallcore.sol#L146) and [`updateSecret`](https://github.com/ridesoloAudit/TheWall/blob/4d7b98e06def9a605aba06663d5c90d5a5e55c54/thewallcore.sol#L154) is called is important to the users. If a user that created a new area wants to rent or sell it and the owner didn't call commitSecret for his hash then `isPremium` will return false, resulting in a loss of 30% (fee charged) even if his nonce and secret will give him a premium area. If the secret is committed later, a new owner may have access to the premium privilege.


## 3.2. Area price

### Severity: owner privileges

### Description

Owner can [change](https://github.com/isvirin/TheWall/blob/4d7b98e06def9a605aba06663d5c90d5a5e55c54/thewallcore.sol#L133) area price.

# 4. Conclusion

The audited smart contract can be deployed. Investors and users should be informed of owner privileges.


# 5. Revealing audit reports

https://gist.github.com/RideSolo/38e59572c49225cddeddeae8c3fc82b5

https://gist.github.com/gorbunovperm/e56d8adfa6bbba0562d78ea7fcd1625c

https://gist.github.com/MrCrambo/20960d441ffdc3bb650cee8264e0ec9e

https://gist.github.com/danbogd/f0801e6c2e3154cbea547425dfa59ac6

**Comment by yuriy77k** [comment]
@RideSolo note about the issue [3.1. Premium Computing](https://gist.github.com/RideSolo/38e59572c49225cddeddeae8c3fc82b5#31-premium-computing).
This is like a bonus lottery which the owner may run or not. It's not a functionality that should be used all the time. This is owner privileges to run lottery free premium or not.
