### ISSUE TITLE
callisto

### ISSUE THREAD

**Issue by dostonbek29** [EthereumCommonwealth/Auditing#430]
# Audit request

... Briefly describe your smart-contract and its main purposes here ...

# Source code

... Give a link to the source code of contracts ...

# Disclosure policy

... Do you want us to publish the report as it is or to notify you privately in case of finding critical mistakes? ...

... provide your conditions for publishing the report or leave only standard disclosure policy link ...

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

... Provide information to contact you or the smart contract-developer in case high severity issues will be found ...

... Provide information about the media resources of the project you want us to audit (website/ twitter account/ reddit/ telegram channel/ etc.) ...

# Platform

... In which network will your contract be deployed? (EOS/TRX/ETC/ETH/CLO/UBQ/something else ) ...

**Comment by Dexaran** [comment]
This request looks invalid.
Please submit a new issue with proper description of the request if necessary or contact dexaran@callisto.network for any explanations.
