### ISSUE TITLE
port a minable token already launched or a new one from ethereum to eos vm

### ISSUE THREAD

**Issue by cryptodigi** [EthereumCommonwealth/Auditing#431]
# Audit request

my smart contract is a burning token derived from the minable token on eth called 0xbtc

# Source code

https://etherscan.io/address/0x4d23f568fe20c1fc2f52fa98a6fa53dfe6d5f7af#code

# Disclosure policy

... Do you want us to publish the report as it is or to notify you privately in case of finding critical mistakes? ...

... provide your conditions for publishing the report or leave only standard disclosure policy link ...

please notify privately to me, we will launch the token later, no website or social already operative

# Contact information (optional)

danieleuggetti@gmail.com

... Provide information about the media resources of the project you want us to audit (website/ twitter account/ reddit/ telegram channel/ etc.) ...

as the token is minable and launche i will be ready with all the community network

# Platform

... In which network will your contract be deployed? (EOS/TRX/ETC/ETH/CLO/UBQ/something else ) ...

contract is already deployed on ethereum but will never be of interest since eth fees are not suited for a minable token, each block sends a reward you, or the pool, pay the fee for... a reliable long term solution cannot stop for high fee cost

**Comment by yuriy77k** [comment]
Currently, we did not provide a free audit. The audit of your contracts will cost 718 USD.
