### ISSUE TITLE
JustHodlIt contract

### ISSUE THREAD

**Issue by justholditmen** [EthereumCommonwealth/Auditing#432]
# Audit request

... The holding game with easy rules

# Source code

https://github.com/justholditmen/contract/blob/master/contract.sol

# Disclosure policy

... Do you want us to publish the report as it is or to notify you privately in case of finding critical mistakes? ...
Yes

... provide your conditions for publishing the report or leave only standard disclosure policy link ...
[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)
Email: justhodlit.men@gmail.com
Site: https://justhodlit.men

# Platform
ETH, CLO (In future)

**Comment by yuriy77k** [comment]
Currently, we did not provide a free audit. The audit of your contracts will cost 667 USD.
