### ISSUE TITLE
OM Lira Smart Contract Auditing

### ISSUE THREAD

**Issue by omprojesi** [EthereumCommonwealth/Auditing#434]
# Audit request

OM Lira is a basic ERC-20 and ERC-1363 compatible token that aims to raise crypto awareness in Republic of Turkey. Currently OM Lira is deployed on Ethereum network but the transfers are disabled and no tokens distributed. We would like our code to be audited, and in case of any critical bugs or vulnerabilities we would want to take action.

# Source code

https://github.com/omprojesi/omlira
https://etherscan.io/address/0x224db5e6180761df4c3d8936585f6b8b83879770#code

# Disclosure policy

Standart disclosure 
https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md

# Contact information (optional)

Telegram: @nithronium
E-mail: yonetim@omlira.com

We would like to get our smart contract audited.

# Platform

Ethereum

**Comment by yuriy77k** [comment]
Currently, we did not provide a free audit. The audit of your contracts will cost 1058 USD.

**Comment by nithronium** [comment]
Already had a security audit out of this platform. Issue could be closed as it had no replies for long time and I had to look for someone else.
