### ISSUE TITLE
ZAC Finance Audit Request

### ISSUE THREAD

**Issue by ZAC-FINANCE** [EthereumCommonwealth/Auditing#435]
# Audit request

ZACFinance Token is a ERC20 Based Token with a purpose to revolutionize the crypto world with it's powerful features and a roadmap. ZAC Finance Token is deployed on ETH Network using Remix and we would like our code to be audited, and in case of any critical bugs or vulnerabilities we would want to take action.

# Source code

Source Code: https://github.com/ZAC-FINANCE/ZACFinance/blob/master/Contract/ZACFinanceToken.sol
Token on Etherscan: https://etherscan.io/token/0x98a90499b62Ae48E151a66B0F647570b5a473B1c

# Disclosure policy

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

Telegram: @lolmoh1010
email : dev@zac.finance
ZAC Finance Group: https://t.me/ZACFinanceP

# Platform

It is Deployed on Ethereum Main Net.

**Comment by MrCrambo** [comment]
Auditing time 3 days.

**Comment by yuriy77k** [comment]
Currently, we did not provide a free audit. The audit of your contracts will cost 574 USD.
