### ISSUE TITLE
ETGF stake

### ISSUE THREAD

**Issue by EthereumGoldETG** [EthereumCommonwealth/Auditing#437]
# Audit request

... Staking by holding ETGF and get back 7% monthly rewards

# Source code

...https://github.com/EthereumGoldETG/ETG-Finance/tree/master/E-stake%20Contracts  ...

# Disclosure policy

... No we are here to check the contract before the launch of it , if it is clear publish it , if not tell us the errors or missing lines to correct it  ...

... If the contract ready to use and safe publish it   ...

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

... Provide information to contact you or the smart contract-developer in case high severity issues will be found ...

... Provide information about the media resources of the project you want us to audit (website/ twitter account/ reddit/ telegram channel/ etc.) ...

# Platform

... In which network will your contract be deployed? ETH ...

**Comment by yuriy77k** [comment]
Currently, we did not provide a free audit. The audit of your contracts will cost 634 USD.
