### ISSUE TITLE
Audit request for Poolz

### ISSUE THREAD

**Issue by Lomet** [EthereumCommonwealth/Auditing#441]
# Audit request
https://docs.google.com/document/d/1e_PkWKKinGHtFxJs9KNqSqNoNt-Hti9o4NKM_pZuhMI/edit#heading=h.ax1bj62de5ki

# Source code
https://github.com/The-Poolz/Poolz-Back

# Disclosure policy
[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)
Email: salty87@gmail.com 
Discord: Lomet#9883

- Website: https://poolzdefi.com/
- medium blog: https://medium.com/@Poolz
- Twitter: https://twitter.com/Poolz__
- Discord: https://discord.gg/grVfg4B
- Telegram group: https://t.me/PoolzOfficialCommunity
- Announcements over Telegram: https://t.me/Poolz_Announcements
- Github: https://github.com/The-Poolz

# Platform
ETH

**Comment by yuriy77k** [comment]
Currently, we did not provide a free audit. The audit of your contracts will cost 1204 USD.
