### ISSUE TITLE
Hi I want to make a formal request to have our project audited www.generation.finance 

### ISSUE THREAD

**Issue by generationvine** [EthereumCommonwealth/Auditing#442]
# Audit request

... the contract an ERC-20 contracts fork of Yearn.finance but we need our token sale contract and staking audited before we list on Uniswap

# Source code

... https://github.com/YGEM-finance/staking-sale-contracts

YGEM Smart Contract 
https://etherscan.io/address/0x9c790a79916296cba9d7e602933df09e0c4d6a29 

Presale Smart Contract 
https://etherscan.io/address/0x4a9b13890b7cccb1fa7c70c32294dad82acc0805

# Disclosure policy

... Do you want us to publish the report as it is or to notify you privately in case of finding critical mistakes? ... Yes we will.

... provide your conditions for publishing the report or leave only standard disclosure policy link ...  standard disclosure, please 

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information @GenerationXwingNeverDM1ST ) (Telegram)

... Provide information to contact you or the smart contract-developer in case high severity issues will be found ...

Telegram for the developer - ( @Avowe on telegram name ) Rostislav Gogolauri

... Provide information about the media resources of the project you want us to audit (website www.generation.finance 
token name is YGEM token address is 
# Platform

... In which network will your contract be deployed? (ETH)

I want to get this addressed ASAP so we can list on Uniswap with confidence next week 

Thank you for your attention

**Comment by yuriy77k** [comment]
Currently, we did not provide a free audit. The audit of your contracts will cost 706 USD.
