### ISSUE TITLE
Tax Heaven Contract

### ISSUE THREAD

**Issue by taxheaven** [EthereumCommonwealth/Auditing#446]
# Audit request

Lending protocol that can be effectively utilized for realizing crypto gains without triggering taxable event.
This protocol allows users to lend/borrow the same token(ETH or ERC20) by paying 0.5% fee in the token and receive our native token.
The native token can be rewarded only when the user deposit a whitelisted token.
The users staking on the staking contract can receive the accumulated 0.5% fee.
The whitelist can be updated through on-chain governance contract.

# Source code

[TaxHeavenContract](https://github.com/TaxHeaven-loan/TaxHeavenContract)

# Disclosure policy

We need you to notify privately as the contract is already deployed on the mainnet.

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

telegram: @tax_heaven
email: taxheaven-protocol@protonmail.com

# Platform

Ethereum mainnet & Binance Smart Chain mainnet

**Comment by yuriy77k** [comment]
The audit cost is $1535  for normal priority.
