### ISSUE TITLE
Withdraw staking 

### ISSUE THREAD

**Issue by ssistarx** [EthereumCommonwealth/Auditing#447]
Hi, I am unable to withdraw CLOs from staking. The transaction fails every time, made at the expiration of 27 days. I don't understand what the problem is.it request

... Briefly describe your smart-contract and its main purposes here ...

# Source code

... Give a link to the source code of contracts ...

# Disclosure policy

... Do you want us to publish the report as it is or to notify you privately in case of finding critical mistakes? ...

... provide your conditions for publishing the report or leave only standard disclosure policy link ...

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

... Provide information to contact you or the smart contract-developer in case high severity issues will be found ...

... Provide information about the media resources of the project you want us to audit (website/ twitter account/ reddit/ telegram channel/ etc.) ...

# Platform

... In which network will your contract be deployed? (EOS/TRX/ETC/ETH/CLO/UBQ/something else ) ...

**Comment by yuriy77k** [comment]
Let me know the transaction ID

**Comment by ssistarx** [comment]
maybe I was wrong, first the withdrawal from the staking must be done then the claim of the rewards

**Comment by yuriy77k** [comment]
When you Claim - you get just rewards (the deposit left on staking).
When you Withdraw - you get a deposited amount + rewards. So no need to call Claim after Withdraw

**Comment by ssistarx** [comment]
Ok, thank you,!
