### ISSUE TITLE
FREXA Contract Audit of Non-Upgradeable Code

### ISSUE THREAD

**Issue by SoulOfJacobeh** [EthereumCommonwealth/Auditing#449]
# Audit request

Our smart contract allows for creating multiple custom ERC-1404 (whitelist-only) token series to fractionalize real estate, compliantly. We have a custom proxy and diamond contract -esque implementation with a management contract that controls issuance and actions of sub-asset proxies.
The majority of our code is upgradeable. We are continuing to work on these sections and may request an audit of these in the future. For now, we would like the non-upgradeable portions to be audited (as listed below).

# Source code

Not yet published to network, please contact me (Jacob) to be added to the repo as a viewer or however that works (alternatively, we could upload them as an archive?):
https://github.com/FREXA-Inc/frexa-contracts/tree/master/contracts
Audit only: 
FREXAManager.sol (DiamondBase.sol)
FREXAMultisigWallet.sol (ECDSAMultisigWallet.sol)
FREXAManagedProxy.sol

# Disclosure policy

... Do you want us to publish the report as it is or to notify you privately in case of finding critical mistakes? ...
Please notify both Jacob and Nick of mistakes/errors/etc.

... provide your conditions for publishing the report or leave only standard disclosure policy link ...
Public disclosure seems unnecessary given the limited scope of the overall code being audited. Please advise Jacob if disclosure is necessary; standard disclose policy is acceptable in this case.
https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md

# Contact information (optional)

Jacob Lux - Technical Consultant
Email: alternate20970@gmail.com, cc jacob@frexa.io
Discord: Soul of Jacobeh#1268

Nick Barry - Contract Developer
Discord: ItsNickBarry#9003

Web2 platform under development. May have a separate audit for this.

# Platform

ETH Mainnet

**Comment by yuriy77k** [comment]
Provided link https://github.com/FREXA-Inc/frexa-contracts/tree/master/contracts does not have any source code. Please fix it

**Comment by SoulOfJacobeh** [comment]
There's code in there, we just have to authorize access to it. If you could provide me with an email to make a member of the link's organization, I will have our dev grant access. Thanks!

**Comment by yuriy77k** [comment]
my email: yuri@callisto.network

**Comment by SoulOfJacobeh** [comment]
I have invited you as a member to the repository to view it. Again please only audit the following: 
FREXAManager.sol (DiamondBase.sol)
FREXAMultisigWallet.sol (ECDSAMultisigWallet.sol)
FREXAManagedProxy.sol

**Comment by yuriy77k** [comment]
Please, write the links for DiamondBase.sol and ECDSAMultisigWallet.sol

**Comment by ItsNickBarry** [comment]
Those contracts can be found in this repository, as specified in the `package.json`: https://github.com/solidstate-network/solidstate-contracts

**Comment by yuriy77k** [comment]
There is import of DiamondBaseStorage.sol and ECDSAMultisigWalletStorage.sol. I reccommend to audit those files too.
You may exclude from audit openzeppelin files to decrease audit cost.
