### ISSUE TITLE
Smart Contract Audit For Shield Protocol 

### ISSUE THREAD

**Issue by rahulsharma0856** [EthereumCommonwealth/Auditing#451]
# Audit request

Our smart contract is simple solidity based program for binance smart chain. It is standard contract in which no mint/burn functions has been used for security reasons. 

# Source code

https://github.com/shield2protocol/smart-contract/blob/main/BinanceSmartChain_SHIELD.sol

# Disclosure policy

Our team already checked the security things within contract as we are cyber security service provider too. We published our solidity smart contract publicly. We need smart contract report just for future references. If still there are some critical things, we will like it privately. Otherwise, your team can release it publicly. 

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

Contact Person: LinkedIn: @rahulsharma0856 , Telegram: @rahulsharma0856     

Project Information: Website: ( www.shieldprotocol.org ), Twitter:  ( https://twitter.com/shield2protocol ) , Telegram: ( https://t.me/shield2protocol ), Medium: ( https://shield2protocol.medium.com ) 

# Platform

**BSC ( Already Deployed )**

**Comment by rahulsharma0856** [comment]
@Dexaran @yuriy77k

**Comment by yuriy77k** [comment]
@rahulsharma0856 the audit will cost 582 USD. Let me know if you accept it.

**Comment by rahulsharma0856** [comment]
Sure. How, we can proceed?

**Comment by yuriy77k** [comment]
@rahulsharma0856 please, send 582 USDT to our treasuty address 0x74682Fc32007aF0b6118F259cBe7bCCC21641600

**Comment by rahulsharma0856** [comment]
@yuriy77k 
Are you sure, this is the safest usdt address for transfer? Because etherscan showing its status, phishing scam address?

**Comment by yuriy77k** [comment]
@rahulsharma0856 we checked it but some troll sent a report to ether scan and ether scan didn’t change it. This address is safe, but if you want you can send USDT to this 0x4667d0c30E6f58ef935ddAb560d41E030E4d2AeB.

**Comment by rahulsharma0856** [comment]
@yuriy77k Got it. Payment done from our side. Here is the transaction Id:  ( 0x56363227dc2712c486c4205ae707c39d5b0f9b5d79045bec76ac6bdfdf45460d )

**Comment by yuriy77k** [comment]
@rahulsharma0856 received. The audit will be completed in 4 days

**Comment by danbogd** [comment]
Auditing time: 3 days.

**Comment by yuriy77k** [comment]
> 
> 
> Auditing time: 3 days.

assigned

**Comment by MrCrambo** [comment]
Auditing time: 3 days.

**Comment by rahulsharma0856** [comment]
Okay.

**Comment by yuriy77k** [comment]
> 
> 
> Auditing time: 3 days.

assigned

**Comment by danbogd** [comment]
My report is finished.

**Comment by MrCrambo** [comment]
My report is finished

**Comment by rahulsharma0856** [comment]
@yuriy77k You can share all reports result/conclusion into Our Official email support@shieldprotocol.org

**Comment by yuriy77k** [comment]
# Shield Protocol Security Audit Report

# 1. Summary

[Shield Protocol](https://github.com/shield2protocol/smart-contract/blob/main/BinanceSmartChain_SHIELD.sol) smart contract security audit report performed by [Callisto Security Audit Department](https://github.com/EthereumCommonwealth/Auditing)

# 2. In scope
Commit hash f5c1a5d77c158f84889b65a4070f7b80c3cf6898
[BinanceSmartChain_SHIELD.sol](https://github.com/shield2protocol/smart-contract/blob/f5c1a5d77c158f84889b65a4070f7b80c3cf6898/BinanceSmartChain_SHIELD.sol)

# 3. Findings

In total, **3 issues** were reported including:

- 1 low severity issues.

- 2 notes.

No critical security issues were found.

## 3.1. Known vulnerabilities of ERC-20 token

### Severity: low

### Description

1. Lack of transaction handling mechanism issue. [WARNING!](https://gist.github.com/Dexaran/ddb3e89fe64bf2e06ed15fbd5679bd20)  This is a very common issue and it already caused millions of dollars losses for lots of token users! More details [here](https://docs.google.com/document/d/1Feh5sP6oQL1-1NHi-X1dbgT3ch2WdhbXRevDN681Jv4/edit).

### Recommendation

Add the following code to the `transfer(_to address, ...)` function:

```
require( _to != address(this) );

```

## 3.2. Unnecessary getter functions

### Severity: note

### Description

The variables [_decimals, _symbol, _name](https://github.com/shield2protocol/smart-contract/blob/f5c1a5d77c158f84889b65a4070f7b80c3cf6898/BinanceSmartChain_SHIELD.sol#L311-L313) declared as `public` so compiler create getter function for them. But for those variables already there are getter function [decimals(), symbol(), name()](https://github.com/shield2protocol/smart-contract/blob/f5c1a5d77c158f84889b65a4070f7b80c3cf6898/BinanceSmartChain_SHIELD.sol#L331-L345).
This issue caused higher gas consumption during deployment, but does not impact on contract works.

### Recommendation

Variable `_decimals`, `_symbol`, `_name` have to be declared as `private`.

## 3.3. Wrong returns type

### Severity: note

### Description

The function [decimals()](https://github.com/shield2protocol/smart-contract/blob/f5c1a5d77c158f84889b65a4070f7b80c3cf6898/BinanceSmartChain_SHIELD.sol#L331) returns type `uint256` but variable [_decimals](https://github.com/shield2protocol/smart-contract/blob/f5c1a5d77c158f84889b65a4070f7b80c3cf6898/BinanceSmartChain_SHIELD.sol#L311) has type `uint8`.

### Recommendation

The function `decimals()` has to returns `uint8`.

# 4. Conclusion

The audited smart contract can be deployed. Only low severity issus was found during the audit. 
The pointed notes don't impact on contract works but show the how it has to be by **good practice**.

# 5. Revealing audit reports

https://gist.github.com/danbogd/c3d990fc32ccd1623e2a9898fd636904

https://gist.github.com/MrCrambo/830356e6648f5b7f5f192f4820d625a9

**Comment by rahulsharma0856** [comment]
@yuriy77k Please change the text "3.1. Known vulnerabilities of ERC-20 token" TO "3.1. Known vulnerabilities of BEP-20 token".

We already mentioned bep20 interface within smart contract. Cross check the things and replace needful text.

**Comment by yuriy77k** [comment]
@rahulsharma0856 here is direct link https://gist.github.com/yuriy77k/f5a0a9d1e0ffd36de1fa5f0c344694a2

**Comment by rahulsharma0856** [comment]
@yuriy77k Thanks.

**Comment by rahulsharma0856** [comment]
@yuriy77k If possible, Please remove ETH Pre-Keyword as per screenshot highlighted below: 


![Capture](https://user-images.githubusercontent.com/66682591/107267538-09016d00-6a6d-11eb-9bb6-a7b5575b03d7.PNG)

**Comment by yuriy77k** [comment]
@rahulsharma0856 updated 
https://gist.github.com/yuriy77k/97e5b0fcee4a3764db6fa1c102256641

**Comment by rahulsharma0856** [comment]
@yuriy77k Thanks

**Comment by rahulsharma0856** [comment]
Hello @yuriy77k , We ( SHIELD PROTOCOL ) wants to audit our dapp smart contract that will be used within our mobile apps.

**Repository link of dapp smart contract file is ( https://github.com/shield2protocol/dapp-contract/blob/main/shieldhash.sol )**

**Comment by yuriy77k** [comment]
@rahulsharma0856 
The audit fee is 515 USDT

You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 3 days after payment.

**Comment by rahulsharma0856** [comment]
@yuriy77k 
Transaction id (BEP-20): https://bscscan.com/tx/0x4ae7c3dc2034842d2a98eeb78065c16459d5839c58a62d5d7690d75b5b772c03

**Comment by yuriy77k** [comment]
@rahulsharma0856 thank you, received

**Comment by rahulsharma0856** [comment]
@yuriy77k Keep audit results private. After all findings and fixing all, We will set it to public at the right time.

**Comment by yuriy77k** [comment]
# ShieldHash Security Audit Report

# 1. Summary

[ShieldHash](https://github.com/shield2protocol/dapp-contract/blob/main/shieldhash.sol) smart contract security audit report performed by [Callisto Security Audit Department](https://github.com/EthereumCommonwealth/Auditing)

Project Information: 

- Website: https://www.shieldprotocol.org
- Twitter: https://twitter.com/shield2protocol
- Telegram: https://t.me/shield2protocol
- Medium: https://shield2protocol.medium.com


# 2. In scope
Commit hash a23fe0fa22d6420f6395785d10b426d42caf484a
[shieldhash.sol](https://github.com/shield2protocol/dapp-contract/blob/a23fe0fa22d6420f6395785d10b426d42caf484a/shieldhash.sol)

# 3. Findings

In total, **1 issues** were reported including:

- 1 notes.

No critical security issues were found.

## 3.1. Using `string` type

### Severity: note

### Description

The type [hashinfo](https://github.com/shield2protocol/dapp-contract/blob/a23fe0fa22d6420f6395785d10b426d42caf484a/shieldhash.sol#L5) declared as `string`, but this type intends to use with text messages. If you need to store bytes data with arbitrary length better to use `bytes` type. In case if the `hashinfo` holds Keccak-256 or SHA-256 hash (or any other hash with length 256 bits) the more organic will be to use `bytes32` type (it will save gas on storage usage).


# 4. Conclusion

The audited smart contract can be deployed. No security issues were found during the audit.

**Comment by yuriy77k** [comment]
@rahulsharma0856 gist with report: https://gist.github.com/yuriy77k/899ae2ef142332bade4498b22b84ff47

**Comment by yuriy77k** [comment]
Blog post:
https://callisto.network/shield-hash-security-audit/

Twitter:
https://twitter.com/Callisto_Audits/status/1397053915900829699

Twitter FR:
https://twitter.com/CallistoNetFr/status/1397053905515732994

Twitter RU:
https://twitter.com/CallistoNetRu/status/1397053895810105344

**Comment by rahulsharma0856** [comment]
Need new audit for Token 'Shield Warriors'. Repository link of smart contract file is here i.e. ( https://github.com/shield2protocol/smart-contract/blob/main/BinanceSmartChain_WARRIOR.sol ).

**Comment by rahulsharma0856** [comment]
@yuriy77k  Are you guys available for audit?

**Comment by yuriy77k** [comment]
@rahulsharma0856 sorry, did not see the message in the closed issue.
Yes, we can audit it. 
The audit fee is 753 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 4 days after payment.

**Comment by rahulsharma0856** [comment]
@yuriy77k Transaction Id: https://bscscan.com/tx/0x52b67010a169912eb670dbce1c22c976db9d1d9a48317d398550215c20758e14

**Comment by yuriy77k** [comment]
@rahulsharma0856 thank you

**Comment by yuriy77k** [comment]
# Shield Warriors token Security Audit Report

# 1. Summary

[Shield Warriors token](https://github.com/shield2protocol/smart-contract/blob/main/BinanceSmartChain_WARRIOR.sol) smart contract security audit report performed by [Callisto Security Audit Department](https://github.com/EthereumCommonwealth/Auditing)

- Website: https://www.shieldprotocol.org
- Twitter: https://twitter.com/shield2protocol
- Telegram: https://t.me/shield2protocol
- Medium: https://shield2protocol.medium.com

# 2. In scope

Commit `d6cc465ce307d77c6c08502a2bb378d666519230`

- [BinanceSmartChain_WARRIOR.sol](https://github.com/shield2protocol/smart-contract/blob/d6cc465ce307d77c6c08502a2bb378d666519230/BinanceSmartChain_WARRIOR.sol)

# 3. Findings

In total, **1 note** were reported including:

- 0 high severity issues.

- 0 medium severity issues.

- 0 low severity issues.

- 1 notes.

- 0 owner privileges.

No critical security issues were found.

## 3.1. Best practice for ERC-20 and BEP-20 tokens

### Severity: note

### Description

ERC20 (BEP20) is a widely used standard across the Ethereum ecosystem. It is reasonable to assume that ERC20 tokens could be "accidentally" deposited to this contract even though it is not intentional.

Every user on the entire Ethereum ecosystem can send ERC20 tokens to this contract and he will have no ability to extract it back unless there is a special "ERC20-rescue" function implemented in your contract. It is advised to implement this function.

*Example: here is [BAT contract address](https://etherscan.io/address/0x0d8775f648430679a709e98d2b0cb6250d2887ef). As you can see the contract itself holds $497,000 worth of different ERC20 tokens - all these tokens are permanently "stuck" inside the contract and therefore uselessly lost.*

### Recommendation

A simple "ERC20-rescue" function can solve the problem.

```js
function rescueERC20(address _token, uint256 _amount) external onlyOwner {
    IBEP20(_token).transfer(owner(), _amount);
  }
```

# 4. Conclusion

The audited smart contract can be deployed. No security issues were found during the audit.

**Comment by yuriy77k** [comment]
Report on gist: https://gist.github.com/yuriy77k/5411b302c60752f93eb5dc486d8ed984

**Comment by yuriy77k** [comment]
@rahulsharma0856 are these links correct?

**Comment by rahulsharma0856** [comment]
@yuriy77k According to report, We added new function into existing smart contract. Here is the link for reference ( https://github.com/shield2protocol/smart-contract/blob/main/BinanceSmartChain_WARRIOR.sol ). Please update the report and gist accordingly. 

Yes. Above links are correct for Shield Warriors Token.

**Comment by yuriy77k** [comment]
@rahulsharma0856 updated

**Comment by yuriy77k** [comment]
@rahulsharma0856 thank you

**Comment by rahulsharma0856** [comment]
Okay. Thanks @yuriy77k

**Comment by rahulsharma0856** [comment]
Hello @yuriy77k ,
We ( Shield Protocol - @shield2protocol ), is upgrading smart contract with new functionality for our pegged tokens and bridge process. Please audit our new smart contract source file i.e. ( https://github.com/shield2protocol/smart-contract/blob/main/BNBChain_SHIELDPROTOCOL.sol ). Also, share the audit fee for the same.  
Also, open this git issue for approval. 
 
Thanks.
