### ISSUE TITLE
Hello i am Patrick Maasdam from the Netherlands

### ISSUE THREAD

**Issue by ptcpat** [EthereumCommonwealth/Auditing#453]
# Audit request

Hourglass smart contract
To give Divs in TRX to holders of WSB
I have been given the oppertunity to lead the community i need to know if it is safe

# Source code

... Give a link to the source code of contracts ...
https://tronscan.org/#/contract/TLqf75M5h7cnViDLJYdTfczjemvopMhRua/code
# Disclosure policy

... Do you want us to publish the report as it is or to notify you privately in case of finding critical mistakes? ...
If it is possible to me in private as i would like to get it fixed if possible
I have been told it has no mistakes but i do not know how to verify
... provide your conditions for publishing the report or leave only standard disclosure policy link ...
ptcpat2019@gmail.com   +31633518590
# Contact information (optional)
ptcpat2019@gmail.com
... Provide information to contact you or the smart contract-developer in case high severity issues will be found ...
+31633518590
... Provide information about the media resources of the project you want us to audit (website/ twitter account/ reddit/ telegram channel/ etc.) ...

# Platform
Tron blockchain
... In which network will your contract be deployed? (EOS/TRX/ETC/ETH/CLO/UBQ/something else ) ...
TRX

Thanks a lot in advance!!

**Comment by yuriy77k** [comment]
Tha audit fee for this contract is 733 USDT.
