### ISSUE TITLE
Future Salaries contracts

### ISSUE THREAD

**Issue by vporton** [EthereumCommonwealth/Auditing#455]
# Audit request

- `SalaryWithDAO.sol`
- `DefaultDAOInterface.sol`

It is to pay huge fair salaries to such people and organizations as scientists, free software developers, open-source publishers, etc.

The economical model follows [this article](https://raw.githubusercontent.com/vporton/gitcoin-web/future/app/assets/docs/science-salaries.pdf).

# Source code

- https://github.com/vporton/future-contracts/blob/master/contracts/SalaryWithDAO.sol
- https://github.com/vporton/future-contracts/blob/master/contracts/DefaultDAOInterface.sol

# Disclosure policy

Do you want us to publish the report as it is or to notify you privately in case of finding critical mistakes?

I want you to publish openly.

Disclose everything, publish (after I deploy) at least on your site, EtherScan, and BscScan (+ a copy for me).

# Contact information (optional)

porton.victor@gmail.com

- https://reward.portonvictor.org
- https://vporton.github.io/future-salary/#/

# Platform

ETH (I plan to use both mainnet and BSC)

# Other

I want also a basic analysis of my economical model (at least a signed statement that it isn't nonsense/madness).

I want your recommendation for how many years exactly to lock money.

Is it possible to provide also an expert review of my contracts' API? (Is anything missing?)

**Comment by vporton** [comment]
I forgot to say that my contracts are not yet fully tested. Is testing service included in your price? Will you give a discount if I test myself?

Should I write tests before I pay you for the audit? Simultaneously with the audit?

**Comment by yuriy77k** [comment]
We does not provide testing service. If we found some issues and you would like to audit it after fixing we'll make discount on reaudit 50%.

**Comment by vporton** [comment]
It's Ok.

But I don't want to pay 150% of the price. So could you assign the price now, but I would pay after me finishing testing?

Certainly, checking referred files is also necessary.

**Comment by yuriy77k** [comment]
Better to calculate price when you'll finish testing.

**Comment by yuriy77k** [comment]
@vporton  all files in https://github.com/vporton/future-contracts/tree/master/contracts is conncted so has to be audited.
Moreover, you are using files from `abdk-libraries-solidity` and `@openzeppelin` if you trust them and to reduce audit cost you may exclude them from audit.
