### ISSUE TITLE
Ethereum solidity contract security audit request

### ISSUE THREAD

**Issue by ghost** [EthereumCommonwealth/Auditing#456]
# Audit request

Fork of SushiSwap Staking Pool https://etherscan.io/address/0xc2edad668740f1aa35e4d8f227fb8e17dca888cd#code contract

# Source code

https://github.com/wallstreetswap/contracts/blob/f78da4680e1cd0f55180002228f7f55c21bb89e5/pool.sol

(666 lines)

# Disclosure policy

... Do you want us to publish the report as it is or to notify you privately in case of finding critical mistakes? ...

As is ( Emergency contract: Telegram https://t.me/wssfinance

... provide your conditions for publishing the report or leave only standard disclosure policy link ...

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

... Provide information to contact you or the smart contract-developer in case high severity issues will be found ...

Telegram https://t.me/wssfinance

... Provide information about the media resources of the project you want us to audit (website/ twitter account/ reddit/ telegram channel/ etc.) ...

Twitter: https://twitter.com/wallstreetswap

Telegram: https://t.me/wallstreetswap

# Platform

... In which network will your contract be deployed? (EOS/TRX/ETC/ETH/CLO/UBQ/something else ) ...

BSC ( ETH )

**Comment by yuriy77k** [comment]
Tha audit will cost 789 USDT. You may transfer it as ERC20 (EHT) or TRC20 (Tron).

**Comment by wallstreetswap** [comment]
@yuriy77k Please pass the wallet address and I will complete the payment, thank you.

**Comment by yuriy77k** [comment]
the wallet address for ERC20 USDT is 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
