### ISSUE TITLE
Beluga Protocol

### ISSUE THREAD

**Issue by chainvisions** [EthereumCommonwealth/Auditing#461]
# Audit request

Our contracts are vaults, they take deposits and optimize yields on them.

# Source code

https://github.com/belugaprotocol/beluga-protocol

# Disclosure policy

I am fine with the report being published as is unless there is a highly severe bug in the code, then please privately message me.

The report can be publish as long as there is no high severity bugs in the contracts.

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

You can contact me on Telegram (@chainvisions).

Here are our social links as well.

Telegram: https://t.me/belugaprotocol
Twitter: https://twitter.com/belugaprotocol
Medium: https://belugaprotocol.medium.com

# Platform

Binance Smart Chain

**Comment by yuriy77k** [comment]
The audit fee is 2737 USDT. The wallet address for ERC20 USDT is 0xb9662e592f2f0412be62f0833ca463a9b1aabebb

**Comment by chainvisions** [comment]
Is it possible for I to pay in BEP20 USDT instead? I do not want to deal with high gas fees on ETH.

**Comment by yuriy77k** [comment]
The BEP20 USDT wallet is the same: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb

**Comment by chainvisions** [comment]
USDT sent via BSC.
https://bscscan.com/tx/0xb3dad74a5af9b7fff32729d53af3fbadbf8187f13902850f1dd92f201fa3a778

**Comment by yuriy77k** [comment]
@chainvisions payment received. The estimated Audit time 10 days.

**Comment by gorbunovperm** [comment]
Estimated auditing time is 10 days.

**Comment by yuriy77k** [comment]
@gorbunovperm assigned

**Comment by gorbunovperm** [comment]
@chainvisions `NoMintRewardPool` ([link](https://github.com/gorbunovperm/beluga-protocol/blob/84c33c8ca90f4a6d3ed2115bd7b2d90bf595abc9/contracts/Autostake.sol#L15)) is not defined.

Perhaps we are talking about a `StakingRewards` contract from RewardsPool.sol ([link](https://github.com/belugaprotocol/beluga-protocol/blob/master/contracts/RewardPool.sol#L645))?

**Comment by chainvisions** [comment]
@gorbunovperm Nice catch, yes, it is referring to a `StakingRewards` contract.

**Comment by yuriy77k** [comment]
# Beluga Protocol Security Audit Report

# 1. Summary

[Beluga Protocol](https://github.com/belugaprotocol/beluga-protocol) smart contract security audit report performed by [Callisto Security Audit Department](https://github.com/EthereumCommonwealth/Auditing)

# 2. In scope

Smart contracts commit [84c33c8ca90f4a6d3ed2115bd7b2d90bf595abc9](https://github.com/belugaprotocol/beluga-protocol/tree/84c33c8ca90f4a6d3ed2115bd7b2d90bf595abc9/contracts)


# 3. Findings

In total, **3 issues** were reported including:

- 0 high severity issues.

- 0 medium severity issues.

- 2 low severity issues.

- 1 notes.

- 0 owner privileges.

No critical security issues were found.

## 3.1. `NoMintRewardPool` is not defined

### Severity: note

### Description

`NoMintRewardPool` contract is not defined. Perhaps we are talking about a `StakingRewards` contract from RewardsPool.sol

### Code Snippet

* [Autostake.sol, NoMintRewardPool](https://github.com/belugaprotocol/beluga-protocol/blob/84c33c8ca90f4a6d3ed2115bd7b2d90bf595abc9/contracts/Autostake.sol#L15)
* [RewardsPool.sol, StakingRewards](https://github.com/belugaprotocol/beluga-protocol/blob/84c33c8ca90f4a6d3ed2115bd7b2d90bf595abc9/contracts/RewardPool.sol#L6450)

## 3.2. Restriction to use Reward Pool by others smart contracts

### Severity: low

### Description

`RewardPool.sol` uses the construction `tx.origin` to allow only the initiators of the transaction to collect the reward. This can lead to the blocking of many users who use smart contracts for convenience and security. For example, users using multisig contracts will not be able to use this contract.

More info about `tx.origin` vulnerabilities: https://github.com/ethereum/solidity/issues/683

### Code snippet
* [RewardPool.sol, tx.origin](https://github.com/belugaprotocol/beluga-protocol/blob/84c33c8ca90f4a6d3ed2115bd7b2d90bf595abc9/contracts/RewardPool.sol#L645)

* [Autostake.sol, tx.origin](https://github.com/belugaprotocol/beluga-protocol/blob/ee6926ec4081a739d2f906c407d3be44982342e6/contracts/Autostake.sol#L57)

* [Vault.sol, tx.origin](https://github.com/belugaprotocol/beluga-protocol/blob/68e19a1d94abb59f02a79abd954391c7aca6da44/contracts/Vault.sol#L103)

* [VestedRewardPool.sol, tx.origin](https://github.com/belugaprotocol/beluga-protocol/blob/84c33c8ca90f4a6d3ed2115bd7b2d90bf595abc9/contracts/VestedRewardPool.sol#L731)

## 3.3. Known vulnerabilities of ERC-20 token

### Severity: low

### Description

1. It is possible to double withdrawal attacks. More details [here](https://docs.google.com/document/d/1YLPtQxZu1UAvO9cZ1O2RPXBbT0mooh4DYKjA_jp-RLM/edit).

2. Lack of transaction handling mechanism issue. [WARNING!](https://gist.github.com/Dexaran/ddb3e89fe64bf2e06ed15fbd5679bd20)  This is a very common issue and it already caused millions of dollars losses for lots of token users! More details [here](https://docs.google.com/document/d/1Feh5sP6oQL1-1NHi-X1dbgT3ch2WdhbXRevDN681Jv4/edit).

### Recommendation

Add the following code to the `transfer(_to address, ...)` function:

```
require( _to != address(this) );

```

# 4. Conclusion

The audited smart contract can be deployed. Only low severity issues were found during the audit.

# 5. Revealing audit reports

https://gist.github.com/gorbunovperm/594b495b281e6c85211943dfd46f14dc

## 5.1 Notes about [gorbunovperm](https://gist.github.com/gorbunovperm/594b495b281e6c85211943dfd46f14dc) report.

The [issue 3.2.](https://gist.github.com/gorbunovperm/594b495b281e6c85211943dfd46f14dc#32-txorigin-is-vulnerable) does not hurt users and can't cause any losses for users or contract. It's an owner's right [to restrict other contracts from interacting with the farms](https://github.com/belugaprotocol/beluga-protocol/blob/84c33c8ca90f4a6d3ed2115bd7b2d90bf595abc9/contracts/VestedRewardPool.sol#L727-L730).

The severity was changed to `low`.

**Comment by yuriy77k** [comment]
The ling to gist: https://gist.github.com/yuriy77k/2c9bdaaaac8d21df9d7770de1c23e64b
