### ISSUE TITLE
Contract audit - 600$ bonus on fast completion ~2 days

### ISSUE THREAD

**Issue by Big-Sock** [EthereumCommonwealth/Auditing#463]
# Audit request

-users request a price quote from the server. this quote is signed by the auth wallet and then sent to the user. the user submits this quote within the acceptableTolerance time limit. then the contract distributes the tokens and emits and event to the server to execute the trade

# Source code

-https://github.com/Spock-Swap/contracts

# Disclosure policy

-please notify me privately

-standard disclosure policy link

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

-telegram @bigsock

-telegram https://t.me/joinchat/ERrEdfzxaQfxgG14
-twitter https://twitter.com/StonkSwap

# Platform

-ETH

**Comment by yuriy77k** [comment]
The audit fee is 936 USDT. 
You may send USDT ERC20 to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT TRC20 to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

If we complete audit less then 2 days you may send a bonus.
