### ISSUE TITLE
Contract Audit Request ~

### ISSUE THREAD

**Issue by Triex** [EthereumCommonwealth/Auditing#465]
# Audit request

A solidity contract for a frictionless token, based off of / a fork of the RFI code.

# Source code

Can I send this privately / share repo?

# Disclosure policy

Do not publish publicly without my permission

# Contact information (optional)

alex@ imakewebsites.co

Other resources to come, but not necessary for this audit

# Platform

Binance Smart Chain / BEP20

**Comment by yuriy77k** [comment]
@Triex please send source code of contract to yuri@callisto.network

**Comment by yuriy77k** [comment]
The source code was not received.
