### ISSUE TITLE
#Audit request

### ISSUE THREAD

**Issue by mrkawdy** [EthereumCommonwealth/Auditing#467]
# Audit request

Community-run redistribution and deflationary token. 1.5% burn and 1.5% redistribution to all holders each transaction. We're looking to see if the code can be updated/changed by the owner and if so what they can do. We want to know if they can mint more tokens and/or if the token is fixed supply, prevent transactions from going through, etc. I didn't create the code and can't edit it. I want to know if this is a true community-based token or if the person who originally created the token can edit it/do malicious things.

# Source code

https://etherscan.io/address/0x5cc737a37a02a1b34ba8edf899aa6441765232a0#code

# Disclosure policy

Notify me privately if any critical errors or info.

# Contact information (optional)

t.me/mrkawdy
https://twitter.com/MrKawdy

Project details (taking over for a dev who left so this info will change in the near future):

Website - xyx.finance - being changed to xyxfoundation.org
Twitter - https://twitter.com/XYXTOKEN - being changed to https://twitter.com/xyxfoundation
CoinGecko - https://www.coingecko.com/en/coins/burn-yield-burn
Telegram - https://t.me/xyxfinance - being changed to https://t.me/officialxyx

# Platform

Ethereum (ETH)

**Comment by yuriy77k** [comment]
The audit fee is 682 USDT.
You may send USDT ERC20 or BEP20 to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT TRC20 to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB
It will be complete in 3 days after payment.

**Comment by mrkawdy** [comment]
Hey there, we already got an audit done. We do not need it anymore. Thanks for taking the time to comment
