### ISSUE TITLE
Smart Contract Audit For Crypto Cafe

### ISSUE THREAD

**Issue by itscryptochef** [EthereumCommonwealth/Auditing#468]
# Audit request

Our smart contract is simple solidity program for binance smart chain.

# Source code

https://github.com/crypto2cafe/smart-contract/blob/main/BinanceSmartChain_CRYPTOCAFE.sol

# Disclosure policy

You can share problems publicly. We will fix it before releasing into BSC Mainnet.

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

Email:  cryptochef@cryptocafe.ai

Project Information: Website: ( www.cryptocafe.ai ), Twitter: ( https://twitter.com/crypto2cafe ) 

# Platform

BEP20 ( BSC - Binance Smart Chain )

**Comment by yuriy77k** [comment]
The audit fee is 582 USDT.
You may send USDT ERC20 or BEP20 to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT TRC20 to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB
It will be complete in 2 days after payment.

**Comment by itscryptochef** [comment]
Payment done from our side. Transaction id is:  0x084793aa93abe048c189df27ddf921e11286d7fc0e635ae5aa59801abf2c1108 . You can start the process from your side. Moreover, We assigned and invited read access to @yuriy77k . If need to add more team members, Please let us know, So we can assign read access accordingly.

**Comment by yuriy77k** [comment]
@itscryptochef thank you. Audit will be complete in 2 days

**Comment by itscryptochef** [comment]
Sure.

**Comment by MrCrambo** [comment]
Auditing time is 1 day.

**Comment by yuriy77k** [comment]
@itscryptochef please give read access to @MrCrambo

**Comment by itscryptochef** [comment]
@yuriy77k Done.

**Comment by yuriy77k** [comment]
@MrCrambo approved

**Comment by yuriy77k** [comment]
# Crypto Cafe Security Audit Report

# 1. Summary

[Crypto Cafe](https://www.cryptocafe.ai/) smart contract security audit report performed by [Callisto Security Audit Department](https://github.com/EthereumCommonwealth/Auditing)

The audited contract is a BEP20 token "CAFE" with a total supply 7,500,000 tokens. The entire total supply pre-mints to contract owner.

# 2. In scope

Commit be8b2664bf2a31cb72c4333874a43e41cf010ad7

[BinanceSmartChain_CRYPTOCAFE.sol](https://github.com/crypto2cafe/smart-contract/blob/be8b2664bf2a31cb72c4333874a43e41cf010ad7/BinanceSmartChain_CRYPTOCAFE.sol)

# 3. Findings

In total, **0 issues** were reported including:

No security issues were found.

# 4. Conclusion

The audited smart contract can be deployed. No security issues were found.


# 5. Revealing audit reports

https://gist.github.com/MrCrambo/5c4e4037b52e74deff0b87d9a668defe

**Comment by itscryptochef** [comment]
@yuriy77k When we will get final audit report with proper link for our users ?

**Comment by yuriy77k** [comment]
@itscryptochef here is Gist link: https://gist.github.com/yuriy77k/7bfa4b11a1b8a17d5e87b40cc74170b7
We will publish the report on our web site in a few days and I'll provide a link too.

**Comment by itscryptochef** [comment]
Okay. Thanks.

**Comment by yuriy77k** [comment]
@itscryptochef Could you please provide us with a logo and maybe some graphic elements?

**Comment by itscryptochef** [comment]
@yuriy77k Sure. We will share it asap, because our backend team already working on it and I will share after getting things from them.

**Comment by yuriy77k** [comment]
@itscryptochef will be better to make your repository pubilc (to allow everyone to read contract code). Because in the report we provide link to audited code and it will looks suspicous when the link does not work.

We will publish report on our web site after getting your logo and  some graphic elements.

**Comment by itscryptochef** [comment]
@yuriy77k I understand. We are releasing our contract into BSC Mainnet. After release, Immediately, We will set its visibility to public. Let you know , after green flag from our backend team.

**Comment by itscryptochef** [comment]
@yuriy77k We set repository into public. Just released our smart contract into BSC Mainnet. Smart Contract address is:  [https://bscscan.com/token/0x32b0f395d8263ddb2f7d727fc5df72e8b7a3b007](https://bscscan.com/token/0x32b0f395d8263ddb2f7d727fc5df72e8b7a3b007).  We will share logo and other graphic details asap.

**Comment by itscryptochef** [comment]
@yuriy77k @MrCrambo **Website:** [https://cryptocafe.ai](https://cryptocafe.ai) ,  **Twitter:** [https://twitter.com/crypto2cafe](https://twitter.com/crypto2cafe), **Github:** [https://github.com/crypto2cafe/smart-contract/](https://github.com/crypto2cafe/smart-contract).

**Logo Url:**  [https://cryptocafe.ai/resources/cryptocafe.png](https://cryptocafe.ai/resources/cryptocafe.png)

**Comment by yuriy77k** [comment]
@itscryptochef

**Comment by itscryptochef** [comment]
@yuriy77k Ok. Thanks.
