### ISSUE TITLE
NFT contract

### ISSUE THREAD

**Issue by blocsport1** [EthereumCommonwealth/Auditing#474]
# Audit request

NFT contract

# Source code

2000 lines

# Disclosure policy

no

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

Please send me the quote

# Platform

ETH

**Comment by yuriy77k** [comment]
the audit fee will be 1900 USDT
