### ISSUE TITLE
Request for audit

### ISSUE THREAD

**Issue by official-mitchell** [EthereumCommonwealth/Auditing#476]
# Audit request

I'm requesting a quote for Ethereum DeFi smart contract audits, a certificate of compliance, and a full report for Dexible (https://dexible.io). These contracts are based around execution of our platform only, not token contracts. Ideally, an audit would include static code, code quality, known vulnerability, and functionality analyses. Our code base and contract code are getting updated with v2, but we'd like to get a quote as soon as possible.

# Source code

Dexible v1 contracts getting improved with documentation and simplified logic. Core execution will remain the same. Link to contracts can be sent.

# Disclosure policy

... Do you want us to publish the report as it is or to notify you privately in case of finding critical mistakes? ...
Publish.

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

Email: mitchell@buidlhub.com | Tg: @officialmitchell

Telegram: https://t.me/dexible
Twitter: https://twitter.com/DexibleApp
Website: https://dexible.io/

# Platform

ETH

**Comment by yuriy77k** [comment]
We can make a security audit of the smart contracts only. To get a quote, please. provide a link to the smart contracts codebase.
