### ISSUE TITLE
DaftCoin - Token - BEP20

### ISSUE THREAD

**Issue by daftpump** [EthereumCommonwealth/Auditing#477]
# Audit request

Smart Contract of a BEP20 token.

# Source code

https://github.com/daftcoin/contracts/blob/main/contracts/DaftCoin.sol

# Disclosure policy

publish the report if it is successfull or to notify we privately in case of finding critical mistakes.

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

dev@daftco.in

Website: https://daftco.in/

# Platform

Binance Smart Chain

**Comment by yuriy77k** [comment]
The audit fee is 820 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 5 days after payment.

**Comment by daftpump** [comment]
@yuriy77k send 820 with USDT (ERC20) to 0xb9662e592f2f0412be62f0833ca463a9b1aabebb

**Comment by MrCrambo** [comment]
Auditing time is 3 days.

**Comment by yuriy77k** [comment]
@MrCrambo assigned

**Comment by Dexaran** [comment]
@yuriy77k I will take part in this audit too.

Audiring time: 1 day, my report will be completed tomorrow.

**Comment by yuriy77k** [comment]
@Dexaran assigned

**Comment by daftpump** [comment]
@Dexaran when we have the report by mail ? Thanks for your great work

**Comment by yuriy77k** [comment]
@daftpump the report was send to email
