### ISSUE TITLE
Smart contract audit needed asap

### ISSUE THREAD

**Issue by ryanmmmmm** [EthereumCommonwealth/Auditing#478]
# Audit request

we forked the compound.finance smart contracts at the hash of their audits and build our own UI.

# Source code

will give it private right now!

# Disclosure policy

... Do you want us to publish the report as it is or to notify you privately in case of finding critical mistakes? ...

u can publish 

... provide your conditions for publishing the report or leave only standard disclosure policy link ...

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

... Provide information to contact you or the smart contract-developer in case high severity issues will be found ...

ryan medlin ryanmedlin@unfederalreserve.com

... Provide information about the media resources of the project you want us to audit (website/ twitter account/ reddit/ telegram channel/ etc.) ...

# Platform

... In which network will your contract be deployed? (EOS/TRX/ETC/ETH/CLO/UBQ/something else ) ...

ETH

**Comment by yuriy77k** [comment]
>
> we forked the compound.finance smart contracts at the hash of their audits and build our own UI.

If you did not change the codebase of the audited compound.finance smart contracts you may use their audit report.
We may audit only smart contracts and don't audit the UI.

**Comment by Dexaran** [comment]
@ryanmmmmm compund has a number of security audits already: https://compound.finance/docs/security

We can conduct a security audit, but you will have to pay for it if you want us to complete this task. We can only audit smart-contracts but not the UI.
