### ISSUE TITLE
ERC721 + Auction logic (bonus for fast delivery)

### ISSUE THREAD

**Issue by mikevercoelen** [EthereumCommonwealth/Auditing#479]
# Audit request

It's an ERC721 with logic to auction tokens

# Source code

Please contact directly. Contract is pretty lightweight, based on OpenZeppelin v4's ERC721 with auction logic added. 

319 Lines of code

# Disclosure policy

Private reporting please.

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

Email: hello@triptcip.com

# Platform

ETH

**Comment by yuriy77k** [comment]
@mikevercoelen I've sent you email

**Comment by yuriy77k** [comment]
620 USDT was paid. The estimated audit time - 5 days.

**Comment by danbogd** [comment]
Estimated auditing time is 5 days.

**Comment by Dexaran** [comment]
Any update on this request?
