### ISSUE TITLE
rt

### ISSUE THREAD

**Issue by erwan-rouzel** [EthereumCommonwealth/Auditing#480]
# Audit request

We have two Smart Contracts for our Pre-ICO and ICO (we already finalized our Private Sale).
They are simple and standards Smart Contracts for a token sale.

# Source code

https://github.com/b-cube-ai/b-cube-ico/blob/feat/public-sale/contracts/BCubePublicSale.sol
https://github.com/b-cube-ai/b-cube-ico/blob/feat/public-sale/contracts/PublicSaleTreasury.sol

# Disclosure policy

We want you first to send the report privately. In case if there is any issue then we will fix them so that you can make a final report which is clean. We will make this final version public.

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

You can reach out to us from the ICO website:
https://ico.b-cube.ai

We will provide more contact details and information about our Blockchain Developer also after starting the audit.
No media ressources have to be audited, only the Smart Contracts.

# Platform

Ethereum

**Comment by yuriy77k** [comment]
The audit fee is 669 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 5 days after payment.

**Comment by erwan-rouzel** [comment]
Hi,

Thanks for your proposal.
However, we decided to go ahead with another proposal.

Best regards,

Erwan Rouzel

___

Co-Founder & CTO

[image: Cutting-edge AI-driven Crypto Trading Bots]

Email : ***@***.***

Tel. : +33‭ 6 85 43 56 33

LinkedIn :
<https://sgnldr.online/click?redirect=https%3A%2F%2Fwww.linkedin.com%2Fin%2Ferouzel%2F&dID=1617425501067&linkName=>
https://www.linkedin.com/in/erouzel/
<https://sgnldr.online/click?redirect=https%3A%2F%2Fwww.linkedin.com%2Fin%2Ferouzel%2F&dID=1617425501067&linkName=https://www.linkedin.com/in/erouzel/>

Acintya Global Holdings SAS

7 rue Le Bouvier, 92340 Bourg-la-Reine, FRANCE

Registration Number (SIRET): 830 862 637 00014
