### ISSUE TITLE
Daofair farm contract

### ISSUE THREAD

**Issue by daofair** [EthereumCommonwealth/Auditing#482]
# Audit request

Smart Contract of a BEP20 token farm

# Source code

https://github.com/daofair/Contract/blob/main/farm.sol

# Disclosure policy

publish the report if it is successfull or to notify we privately in case of finding critical mistakes.

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

team@daofair.com  //  https://t.me/Ichijohaku

# Platform

Binance Smart Chain

**Comment by yuriy77k** [comment]
The audit fee is 868 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 7 days after payment.
