### ISSUE TITLE
Safe Star protocol smart contract audit

### ISSUE THREAD

**Issue by safestarme** [EthereumCommonwealth/Auditing#484]
# Audit request

Our protocol smart contract is frictionless yield and liquidity generator.

# Source code

https://github.com/safestarme/safe-star-contract/blob/main/SafeStar.sol
https://bscscan.com/address/0x3c00f8fcc8791fa78daa4a480095ec7d475781e2

# Disclosure policy

no disclosure policy, happy to provide audit results publicly 

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

hello@safestar.me
http://safestar.me/
https://twitter.com/safestar_
https://t.me/SafeStar_Group

# Platform

BSC
https://bscscan.com/address/0x3c00f8fcc8791fa78daa4a480095ec7d475781e2

**Comment by yuriy77k** [comment]
The audit fee is 991 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 9 days after payment.
