### ISSUE TITLE
Audit request token BFO

### ISSUE THREAD

**Issue by hoanganhxt** [EthereumCommonwealth/Auditing#485]
[TOKEN.txt](https://github.com/EthereumCommonwealth/Auditing/files/6292225/TOKEN.txt)
# Audit request

BUFFALO CENTAL (BFO) is a platform currency representing value and wealth in the decentralized economy used for the exchange of values between BUFFALO CENTAL companies, employees, customers, and other third-party entities. BUFFALO CENTAL is a cryptocurrency-based payments alternative that is fast, convenient and secure.

# Source code

https://bscscan.com/address/0x18ff0c6f901b7fb8d6b96ee38eac8027a2acaae8

# Disclosure policy

Please notify me if there are important security issues

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)
Email: admin@buffalocental.work

https://buffalocental.work

https://twitter.com/buffalocental

# Platform

BSC BEP20

**Comment by yuriy77k** [comment]
@hoanganhxt 
The audit fee is 592 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 3 days after payment.
