### ISSUE TITLE
Phu Quoc Doge(PQD)

### ISSUE THREAD

**Issue by duythien** [EthereumCommonwealth/Auditing#487]
# Audit request

Phu Quoc Doge is no longer just a dog social network, it is the best social network for pets, and build on blockchain networks.

# Source code

https://github.com/lackky/token

# Disclosure policy

You can public the report

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

You can send the email to the team at hello@phuquocdoge.com

The website https://phuquocdoge.com/

# Platform

Build on BSC platform

**Comment by yuriy77k** [comment]
@duythien The audit fee is 764 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 5 days after payment.
