### ISSUE TITLE
Smart Code Audit Request

### ISSUE THREAD

**Issue by ghost** [EthereumCommonwealth/Auditing#497]

**Comment by yuriy77k** [comment]
@HUPLIFE The audit fee is 958 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 14 days after payment.

**Comment by HUPLIFE** [comment]
Do you have a contract we could sign and then I would send it over?

Thanks,

Harrison Jordan
Harrison Jordan Law Professional Corporation

Cannabis Lawyer & Consultant
J.D. // Osgoode Hall Law School
Direct: +1-647-371-0032
Https://harrisonjordanlaw.com

This email is solely for the intended recipient and contains confidential and privileged information. If you are not the intended recipient, you are prohibited from distributing or copying this email or any attachments, nor should you take any action in reliance on their contents. If you have received this email in error, please notify the sender immediately and delete the original message and all copies. Thank you for your cooperation.

Book a consultation with me now here: https://tidycal.com/hsj-law


PS… Like proof? Here are the trees we planted last month!

**Comment by HUPLIFE** [comment]
Hello - Do you have a contract I can sign for this? We will not go ahead until an agreement is signed.

**Comment by HUPLIFE** [comment]
Do you have a contract or something similar we could sign and then I would send it over? Or even a simple purchase order saying how long it will take and your terms? We are interested in the Audit service for sure. We already have TWO other auditors of the code including CERTIK but we are all about community confidence.


Thanks,

Harrison Jordan
Harrison Jordan Law Professional Corporation

Cannabis Lawyer & Consultant
J.D. // Osgoode Hall Law School
Direct: +1-647-371-0032
Https://harrisonjordanlaw.com

This email is solely for the intended recipient and contains confidential and privileged information. If you are not the intended recipient, you are prohibited from distributing or copying this email or any attachments, nor should you take any action in reliance on their contents. If you have received this email in error, please notify the sender immediately and delete the original message and all copies. Thank you for your cooperation.

Book a consultation with me now here: https://tidycal.com/hsj-law


PS… Like proof? Here are the trees we planted last month!

**Comment by yuriy77k** [comment]
@HUPLIFE Sorry, we  have not any contract to sign
