### ISSUE TITLE
Request Smart Contract Audit For $USKITA

### ISSUE THREAD

**Issue by realchasecurtis** [EthereumCommonwealth/Auditing#502]
# Audit request

Trading $USKITA // American Akita

# Source code

https://etherscan.io/address/0xc18e7a03f8986798323658dd8645f93aa79ac5c9#code

# Disclosure policy

Notify privately

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

realchasecurtis@gmail.com

# Platform

ETH

**Comment by yuriy77k** [comment]
@realchasecurtis The audit fee is 671 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 5 days after payment.
