### ISSUE TITLE
Simple private notary smart contract

### ISSUE THREAD

**Issue by thibautvdu** [EthereumCommonwealth/Auditing#503]
# Audit request
Extremely simple, private notary smart contract to certify the ownership, integrity and precedence of a file by storing its sha256 hash, the block timestamp and by forbidding any other address than the owner to create a certificate.

We mainly expect from this audit a confirmation that this simple contract fills its purpose : prove the existence and ownership of a file at a given time, avoid any duplicates, edition or deletion (create-only).

# Source code
https://github.com/thibautvdu/immiris-v2-smart-contracts/blob/dfe20b9729beef720f5cc4909469f5f2c191c672/contracts/ImmirisNotary.sol

# Disclosure policy
[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)
Website: [Immiris](https://immiris.com)
Contact: contact@immiris.com

# Platform
ETH

**Comment by yuriy77k** [comment]
@thibautvdu The audit fee is 512 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 3 days after payment.

**Comment by thibautvdu** [comment]
@yuriy77k Thanks for your fast reply. Payment has been processed today.

**Comment by yuriy77k** [comment]
# Simple private notary Security Audit Report

# 1. Summary

[Simple private notary](https://github.com/thibautvdu/immiris-v2-smart-contracts/blob/dfe20b9729beef720f5cc4909469f5f2c191c672/contracts/ImmirisNotary.sol) smart contract security audit report performed by [Callisto Security Audit Department](https://github.com/EthereumCommonwealth/Auditing)

- https://immiris.com/


# 2. In scope

Commit `dfe20b9729beef720f5cc4909469f5f2c191c672`

- [ImmirisNotary.sol](https://github.com/thibautvdu/immiris-v2-smart-contracts/blob/dfe20b9729beef720f5cc4909469f5f2c191c672/contracts/ImmirisNotary.sol)

# 3. Findings

In total, **0 issues** were reported including:

- 0 high severity issues.

- 0 medium severity issues.

- 0 low severity issues.

- 0 notes.


# 4. Conclusion

The audited smart contract can be deployed. No security issues were found during the audit.

**Comment by yuriy77k** [comment]
https://gist.github.com/yuriy77k/fd7dc9e7ecb82fe98713c4e952826eea
