### ISSUE TITLE
Slothi-Token

### ISSUE THREAD

**Issue by Slothi-Token** [EthereumCommonwealth/Auditing#504]
# Audit request

the smart contract is a deflationary token
it's a community token
13% Fee = 7% holder / 3% burn / 3% lp

# Source code

https://github.com/Slothi-Token/Slothi.sol/blob/main/slothi.sol

# Disclosure policy

notify you privately

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

Slothi-Token@protonmail.com

# Platform
BSC

**Comment by yuriy77k** [comment]
@Slothi-Token  The audit fee is 1004 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 15 days after payment.
