### ISSUE TITLE
Vulkania VLK token - Binance Smart Chain

### ISSUE THREAD

**Issue by vulkaniadev** [EthereumCommonwealth/Auditing#505]
# Audit request

We want to audit the smart contract of VLK (Vulkania), a BEP20 Token (Binance Smart Chain)

# Source code

https://github.com/Vulkania/contracts/blob/main/contracts/Vulkania.sol

# Disclosure policy

publish the report if it is successfull or to notify we privately in case of finding critical mistakes.

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

Contact email : contact@vulkania.io 
Website : https://vulkania.io

# Platform

BSC (Binance Smart Chain) - BEP20 token

**Comment by yuriy77k** [comment]
@vulkaniadev The audit fee is 820 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 15 days after payment.

**Comment by vulkaniadev** [comment]
Payment sent.

**Comment by yuriy77k** [comment]
@danbogd assigned

**Comment by danbogd** [comment]
My report is finished.

**Comment by vulkaniadev** [comment]
@danbogd could you please send us the report via email?
