### ISSUE TITLE
Lunar Shuttle LUSH - Binance Smart Chain Token

### ISSUE THREAD

**Issue by lunarshuttlebsc** [EthereumCommonwealth/Auditing#506]
# Audit request

$LUSH is a token on the BSC network that has a 9% fee on each transaction. 1% of the fee goes to the Binance Charity Address (click Show ERC20 BNB donation address) , 2% is burned and 6% is divided to all the holders. Fees will be set after listing on Pancake Swap

# Source code

https://www.bscscan.com/address/0xfe0466568466d2837761206b0136ecc0970df2b8#code

# Disclosure policy

... Do you want us to publish the report as it is or to notify you privately in case of finding critical mistakes? ...
Please notify me privately before if there are any issues so I can fix them. We plan to lock liquidity and renounce ownership.

... provide your conditions for publishing the report or leave only standard disclosure policy link ...

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

... Provide information to contact you or the smart contract-developer in case high severity issues will be found ...
Telegram Dev: @aswad1337

... Provide information about the media resources of the project you want us to audit (website/ twitter account/ reddit/ telegram channel/ etc.) ...

# Platform
It is deployed on BSC
... In which network will your contract be deployed? (EOS/TRX/ETC/ETH/CLO/UBQ/something else ) ...

**Comment by yuriy77k** [comment]
@lunarshuttlebsc  The audit fee is 740 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 7 days after payment.
