### ISSUE TITLE
GOODSHIP Audit request

### ISSUE THREAD

**Issue by goodshipdev** [EthereumCommonwealth/Auditing#509]
# Audit request

Goodship is a new crypto token designed to alleviate poverty while providing investors with incredible returns. It is frictionless, yield-generating, deflationary, whale-proof, and rug pull-proof.
The protocol was launched on the Binance Smart Chain (BSC) on May 8th, 2021 through a fair launch. Ownership of the contract has been renounced by the developers.
Goodship was created with an initial token supply of 700,000,000,000 (700 billion).
No tokens were burned upon Goodship's launch. Other crypto tokens have started with an initial supply of 1 trillion and burned 30% of the tokens, leaving 700 billion. Goodship achieves the same result without the step of burning tokens at launch.
Goodship is a fork of Safemoon that improves upon the original contract in several ways.
The Goodship contract employs a static rewards system with the following attributes:
* On every transaction, there is a 10% tax automatically taken by the contract.
* One-half (5%) of the transaction tax is automatically distributed to all holders of the Goodship token.
* The other half (5%) of the transaction tax is automatically added to the locked liquidity pool inside the PancakeSwap decentralized exchange (DX) to power future trades.

# Source code
https://github.com/goodshipdev/Goodship/tree/main

# Disclosure policy

Notify privately if a critical issue found.

... provide your conditions for publishing the report or leave only standard disclosure policy link ...

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)
dev@goodshiptoken.com
https://twitter.com/goodship3
https://t.me/joinchat/RU3z9hzqT6JlZWNk
https://discord.gg/5AP6qq54U2
https://www.reddit.com/r/Goodship/

# Platform

Binance Smart Chain

**Comment by yuriy77k** [comment]
@goodshipdev The audit fee is 1000 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 7 days after payment.
