### ISSUE TITLE
Greenacks

### ISSUE THREAD

**Issue by kipdgreen** [EthereumCommonwealth/Auditing#510]
# Audit request

... Briefly describe your smart-contract and its main purposes here ...

# Source code

https://etherscan.io/address/0xd41e7c87dd4137ee18d47c419170f833796f7c6a#code#L1

... Give a link to the source code of contracts ...

https://etherscan.io/address/0xd41e7c87dd4137ee18d47c419170f833796f7c6a#code#L1

# Disclosure policy

... Do you want us to publish the report as it is or to notify you privately in case of finding critical mistakes? ...

... provide your conditions for publishing the report or leave only standard disclosure policy link ...

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

... Provide information to contact you or the smart contract-developer in case high severity issues will be found ...

... Provide information about the media resources of the project you want us to audit (website/ twitter account/ reddit/ telegram channel/ etc.) ...

# Platform

... In which network will your contract be deployed? (EOS/TRX/ETC/ETH/CLO/UBQ/something else ) ...

ETH

**Comment by kipdgreen** [comment]
I’m not for sure what I’m doing a while back started this project I’m lost

**Comment by yuriy77k** [comment]
@kipdgreen The audit fee is 605 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 3 days after payment.

**Comment by kipdgreen** [comment]
Yuily come in now quit it
