### ISSUE TITLE
1 Million Dollar Coin 

### ISSUE THREAD

**Issue by 1milliondollarcoin** [EthereumCommonwealth/Auditing#511]
# Audit request

if the security is okay...

# Source code

https://bscscan.com/token/0xda8259040ed9c7d90e12b3b322bfe10b2eac5430

# Disclosure policy

We prefer to be notified privately via:
Telegram @StevenWaken
Email info@1milliondollarcoin.com

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)
https://www.1milliondollarcoin.com/
https://twitter.com/1mdollarcoin
https://t.me/onemilliondollarcoinannouncement

# Platform

binance smart chain

**Comment by yuriy77k** [comment]
@1milliondollarcoin The audit fee is 616 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 3 days after payment.
