### ISSUE TITLE
Coinixa Finance Audit Request

### ISSUE THREAD

**Issue by coinixa** [EthereumCommonwealth/Auditing#512]
# Audit request

... Briefly describe your smart-contract and its main purposes here ... Coinixa Finance is the world's first Deflationary Token
an Autonomous Yield and Liquidity Generation
Protocol which is based on Binance Smart Chain

# Source code: https://bscscan.com/address/0xacc081a4bfbb13a7558561017bece754546eed59#code

... Give a link to the source code of contracts ... https://bscscan.com/address/0xacc081a4bfbb13a7558561017bece754546eed59#code

# Disclosure policy

... Do you want us to publish the report as it is or to notify you privately in case of finding critical mistakes? ... PUBLISH REPORT PRIVATELY

... provide your conditions for publishing the report or leave only standard disclosure policy link ...

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

... Provide information to contact you or the smart contract-developer in case high severity issues will be found ... support@coinixa.finance

... Provide information about the media resources of the project you want us to audit (website/ twitter account/ reddit/ telegram channel/ etc.) ...

# Platform Audit Coinixa Finance

... In which network will your contract be deployed? (EOS/TRX/ETC/ETH/CLO/UBQ/something else ) ... BEP 20 BSC

**Comment by yuriy77k** [comment]
@coinixa The audit fee is 704 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 5 days after payment.

**Comment by coinixa** [comment]
Thanks. Already audited.
