### ISSUE TITLE
OCAT Token Contract Audit

### ISSUE THREAD

**Issue by ghost** [EthereumCommonwealth/Auditing#514]
# Audit request

It's a simple bep20 token template contract

# Source code

https://bscscan.com/address/0x7128e52ca302c5f5beeb801b6ad373fdebe3dc5e#code

# Disclosure policy

https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md

# Contact information (optional)

# Platform

Binance Smart Chain

**Comment by yuriy77k** [comment]
@icecab The audit fee is 592 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 3 days after payment.
