### ISSUE TITLE
Request audit check for TNT token, thank you very much.

### ISSUE THREAD

**Issue by TokenTrend** [EthereumCommonwealth/Auditing#516]
# Audit request

The smart-contract is used to define a new cryptocurrency and provide the basic function like token transfer, mint, airdrop, etc.

# Source code

https://github.com/org-TokenTrend/governance-sol/blob/main/contract/ERC20/TNT.sol
https://github.com/org-TokenTrend/governance-sol/blob/main/contract/ERC20/airdrop.sol

# Disclosure policy

If it's possible, if a serious error is found, it would be better to notify us privately. If there is no error, please publish a report directly.

The standard disclosure policy is ok for us.

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

Email: tokentrendtnt@gmail.com

Nothing for our media resources need to audit.

# Platform

HECO

**Comment by yuriy77k** [comment]
@TokenTrend The audit fee is 993 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 7 days after payment.
