### ISSUE TITLE
Monkey Token

### ISSUE THREAD

**Issue by monkeytoken-bsc** [EthereumCommonwealth/Auditing#518]
# Audit request

... Briefly describe your smart-contract and its main purposes here ...
The Monkey Protocol is a deflationary decentralized Meme Tokens created to safeguard primate life in the world and turned into a huge ecosystem
Monkey is a most revolutionary decentralized token of the BSC ecosystem with unique features that rewards holders for only having the token supported. The project is fully supported and community-based

# Source code
https://github.com/monkeytoken-bsc/MonkeyToken/blob/main/MonkeyToken.sol
... Give a link to the source code of contracts ...
https://github.com/monkeytoken-bsc/MonkeyToken/blob/main/MonkeyToken.sol
# Disclosure policy

... Do you want us to publish the report as it is or to notify you privately in case of finding critical mistakes? ...

... provide your conditions for publishing the report or leave only standard disclosure policy link ...

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)
Official website :earth_africa::
EMAIL: contact@monkeytoken.net

... Provide information to contact you or the smart contract-developer in case high severity issues will be found ...
EMAIL: admin@monkeytoken.net
... Provide information about the media resources of the project you want us to audit (website/ twitter account/ reddit/ telegram channel/ etc.) ...
 www.monkeytoken.net
Twitter: https://twitter.com/MonkeyToken2
Facebook: https://www.facebook.com/MonkeyToken
Reddit:
https://www.reddit.com/r/MonkeyToken/new/

# Platform
BSC
... In which network will your contract be deployed? (EOS/TRX/ETC/ETH/CLO/UBQ/something else ) ...

**Comment by yuriy77k** [comment]
@monkeytoken-bsc The audit fee is 1008 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 7 days after payment.
