### ISSUE TITLE
need to get my smart contract audited at intial stage 

### ISSUE THREAD

**Issue by sarrv** [EthereumCommonwealth/Auditing#523]
# Audit request

..we are launching a truen burn deflationary charity token with the use case of tokens in exchange of trading bot services...

# Source code

https://testnet.bscscan.com/address/0xa9643c27e4319b4ee0d81cb87b9fec2d00136c06#code

# Disclosure policy

publish as it is as there is no hidden function as per us.

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

... Provide information to contact you or the smart contract-developer in case high severity issues will be found ...

... Provide information about the media resources of the project you want us to audit (website/ twitter account/ reddit/ telegram channel/ etc.) ...

# Platform

... the contract would be on binance smart chain. (BSC)

**Comment by yuriy77k** [comment]
@sarrv The audit fee is 780 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 7 days after payment.

**Comment by sarrv** [comment]
Dont have funds at the moment. I didnt know that it was paid service. 

Sorry.
Thanks for reverting
