### ISSUE TITLE
bimp.finance audit

### ISSUE THREAD

**Issue by laronlineworld** [EthereumCommonwealth/Auditing#527]
# Audit request

... Briefly describe your smart-contract and its main purposes here ...
Bimp has the latest smart contract technology for BNB auto-yield and anti-whale mechanisms.

# Source code

... Give a link to the source code of contracts ...
https://github.com/laronlineworld/bimp.finance/blob/main/bimpfinance.sol

# Disclosure policy

... Do you want us to publish the report as it is or to notify you privately in case of finding critical mistakes? ...
Yes

... provide your conditions for publishing the report or leave only standard disclosure policy link ...
Publish on twitter, github and reddit

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

... Provide information to contact you or the smart contract-developer in case high severity issues will be found ...

spm.laramos@gmail.com

... Provide information about the media resources of the project you want us to audit (website/ twitter account/ reddit/ telegram channel/ etc.) ...
Telegram
https://t.me/bimpxdefy
Twitter
https://mobile.twitter.com/BIMP_Official

# Platform

... In which network will your contract be deployed? (EOS/TRX/ETC/ETH/CLO/UBQ/something else ) ...
Binance smart chain
[bimpfinance.txt](https://github.com/EthereumCommonwealth/Auditing/files/6699459/bimpfinance.txt)

**Comment by yuriy77k** [comment]
@laronlineworld The audit fee is 1267 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 15 days after payment.
