### ISSUE TITLE
BADBOY TOKEN

### ISSUE THREAD

**Issue by badboytoken** [EthereumCommonwealth/Auditing#528]
# Audit request

Hello Callisto, we need a contract audit, it's for the utility token from BADBOY TOKEN, it's also verified in the Binance Smart Chain.

# Source code
https://bscscan.com/address/0xa84f07a8643a81ceb5f0b8b61048515f09ccb523

# Disclosure policy

... Do you want us to publish the report as it is or to notify you privately in case of finding critical mistakes?  Notify me 

... provide your conditions for publishing the report or leave only standard disclosure policy link ...

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

... admin@badboy.network

... Provide information about the media resources of the project you want us to audit (website/ twitter account/ reddit/ telegram channel/ etc.) ...

# Platform

... In which network will your contract be deployed? BSC

**Comment by yuriy77k** [comment]
@badboytoken The audit fee is 827 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 7 days after payment.
