### ISSUE TITLE
J

### ISSUE THREAD

**Issue by michelra** [EthereumCommonwealth/Auditing#529]
#440 

#441 

Our supply shows it keeps increasing on ethsplorer, when we are at 1Q cap. Not sure if it’s a bug or contract error? 

We need to have a security audit on a contract for a newly launched (by FairLaunchCalls) crypto coin PUSSC / contract is:

Dextools chart / link to PUSSC on uniswap -     https://www.dextools.io/app/uniswap/pair-explorer/0x5277c3195801fd4acc92ebfd939024f08cfb697a

Contract: 0xf184cdf2f96e21f4907b069ab85fb23f4b65ce7b

Dev Tax Wallet                                      https://etherscan.io/address/0x4091e425d0cc258d8071a80362a99d9edb7e88d9

Burn Wallet (Dead Address)               https://etherscan.io/address/0x000000000000000000000000000000000000dead

100 year supply lock on the contract 

https://app.unicrypt.network/amm/uni-v2/pair/0x5277c3195801fd4acc92ebfd939024f08cfb697a

Please let me know whatever additional information is needed.

Thank you.

# Source code

https://etherscan.io/token/0xf184cdf2f96e21f4907b069ab85fb23f4b65ce7b#readContract

# Disclosure policy

Privately if there is an error in the contract. If there is a bug, then it may be public

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

cryptopussc@gmail.com

https://t.me/PussyCredit

# Platform

... In which network will your contract be deployed? 

It’s currently on Etherscan. Can be viewed in ethplorer, where we have supply issue. Page one says the wallets have more than what the supply is. We are trying to get listed on exchanges; but need to make sure it functioning correct 

(EOS/TRX/ETC/ETH/CLO/UBQ/something else ) ...

**Comment by yuriy77k** [comment]
@michelra The audit fee is 916 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 10 days after payment.
