### ISSUE TITLE
LadyShiba

### ISSUE THREAD

**Issue by drakew365** [EthereumCommonwealth/Auditing#531]
# Audit request

... Briefly describe your smart-contract and its main purposes here ...

# Source code

... Give a link to the source code of contracts ...

https://bscscan.com/address/0xa7d8524aaF1Adf07E509b5AD6f5D76E2091FC9b6#code

# Disclosure policy

... Do you want us to publish the report as it is or to notify you privately in case of finding critical mistakes? ... Yes

... provide your conditions for publishing the report or leave only standard disclosure policy link ... Standard

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

... Provide information to contact you or the smart contract-developer in case high severity issues will be found ...

... Provide information about the media resources of the project you want us to audit (website/ twitter account/ reddit/ telegram channel/ etc.) ...

# Platform

... In which network will your contract be deployed? (EOS/TRX/ETC/ETH/CLO/UBQ/something else ) ... BSC

**Comment by yuriy77k** [comment]
@drakew365 The audit fee is 911 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 10 days after payment.
