### ISSUE TITLE
OlympicStaking smart contract audit

### ISSUE THREAD

**Issue by ray1999880301** [EthereumCommonwealth/Auditing#537]
# Audit request

Our project is to offer the staking pool for Olympics, users can stake on their country or favorite athlete, play like the sports lottery but transparent and fair.

# Source code

https://bscscan.com/address/0xc57d024565624b77f5100b35ddd49fd924cbd696#code

# Disclosure policy

... Do you want us to publish the report as it is or to notify you privately in case of finding critical mistakes? ...
notify us if some mistakes

... provide your conditions for publishing the report or leave only standard disclosure policy link ...

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

... Provide information to contact you or the smart contract-developer in case high severity issues will be found ...
email: conndappteam@gmail.com

... Provide information about the media resources of the project you want us to audit (website/ twitter account/ reddit/ telegram channel/ etc.) ...
https://twitter.com/OlympicStaking

# Platform

... In which network will your contract be deployed? (EOS/TRX/ETC/ETH/CLO/UBQ/something else ) ...
BSC

**Comment by yuriy77k** [comment]
@ray1999880301 The audit fee is 574 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 3 days after payment.
