### ISSUE TITLE
Dragonary

### ISSUE THREAD

**Issue by yograterol** [EthereumCommonwealth/Auditing#538]
# Audit request

We have been working on an NFT-based game called Dragonary. Dragonary has ERC-20 and ERC-721 tokens, and the team will need an ERC20-Vesting wallet. All code is in the gist.

You can check the tokens deployed at:

DragonsERC721: https://testnet-explorer.callisto.network/address/0x8D969f2674300E8B5C67DA2d058deC40f990B999/contracts

TokenVesting: https://testnet-explorer.callisto.network/address/0x0C330E8bd1484BC117546B11c4a854B2aC37C0EA/contracts

Coinary Token has received changes last time, so there is only the source code.

I only trust in Callisto auditing :) @Dexaran and @yuriy77k 

# Source code

https://gist.github.com/yograterol/4c7f03e7fc411e279c52b4be1e033b79

# Disclosure policy

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

yograterol@coinary.com or yograterol@callisto.network
@yograterol at Twitter

# Platform

CLO

**Comment by yuriy77k** [comment]
# Dragonary Security Audit Report

# 1. Summary

[Dragonary](https://gist.github.com/yograterol/4c7f03e7fc411e279c52b4be1e033b79) smart contract security audit report performed by [Callisto Security Audit Department](https://github.com/EthereumCommonwealth/Auditing)

# 2. In scope

https://gist.github.com/yograterol/4c7f03e7fc411e279c52b4be1e033b79

# 3. Findings

In total, **1 issues** were reported, including:

- 0 high severity issues.

- 0 medium severity issues.

- 1 low severity issues.

In total, **5 notes** were reported, including:

- 3 notes.

- 2 owner privileges.

No critical security issues were found.

## 3.1. Known vulnerabilities of ERC-20 token

### Severity: low

### Description

Lack of transaction handling mechanism issue. [WARNING!](https://gist.github.com/Dexaran/ddb3e89fe64bf2e06ed15fbd5679bd20)  This is a very common issue, and it already caused millions of dollars in losses for lots of token users! More details [here](https://docs.google.com/document/d/1Feh5sP6oQL1-1NHi-X1dbgT3ch2WdhbXRevDN681Jv4/edit).

### Recommendation

Add the following code to the [_beforeTokenTransfer(...)](https://gist.github.com/yograterol/4c7f03e7fc411e279c52b4be1e033b79#file-erc20capped-sol-L38-L48) function:

```Solidity
require( to != address(this) );

```

## 3.2. Dragons NFT may be transferred or sold after softBurnDragon

### Severity: note/medium

### Description

The function [softBurnDragon(uint256 dragonId)](https://gist.github.com/yograterol/4c7f03e7fc411e279c52b4be1e033b79#file-dragonserc721-sol-L61) mark token as burned in the `DragonsERC721` contract, but user may use standard ERC721 functions to transfer token to another owner or sell it on NFT market place.

### Recommendation

Store current owner of token in `mapping(uint256 => address) private _ownerBurned;`
and burn using standard ERC721 `_burn(uint256 tokenId)` function. To restore token you have to call `_mint(_ownerBurned[dragonId], dragonId);`

## 3.3. Function `restoreDragon()` also may "soft burn" token without emitting event `Burn`

### Severity: note

### Description

According name of function [restoreDragon()](https://gist.github.com/yograterol/4c7f03e7fc411e279c52b4be1e033b79#file-dragonserc721-sol-L83-L85) it should restore "soft burned" token. But if parameter `burnStatus` is `false` the token will be "soft burned" but `Restore` event will be emitted. 

### Recommendation
Change the function name to a more appropriate one (for example `setDragonStatus`).

Replace https://gist.github.com/yograterol/4c7f03e7fc411e279c52b4be1e033b79#file-dragonserc721-sol-L85 with:

```Solidity
if(burnStatus) 
    emit Burn(_msgSender(), dragonId);
else
    emit Restore(_msgSender(), dragonId, burnStatus);
```

## 3.4. Unnecessary function

### Severity: note

### Description

The function [_beforeTokenTransfer()](https://gist.github.com/yograterol/4c7f03e7fc411e279c52b4be1e033b79#file-coinarytoken-sol-L98-L104) is unnecessary and may be removed.

## 3.5. Owner privileges.

### Severity: owner privileges.

### Description

1. `CoinaryToken` contract owner (`DEFAULT_ADMIN_ROLE`) has right to assign `MINTER_ROLE` to any address to mint tokens.

2. `DragonsERC721` contract owner (`DEFAULT_ADMIN_ROLE`) has right to assign `MINTER_ROLE` to any address to mint tokens and assign `BURNER_ROLE` to any address to burn tokens.

# 4. Security practices

- [x] **Open-source contact**.
- [ ] **The contract should pass a bug bounty after the completion of the security audit.**
- [ ] **Public testing.**
- [ ] **Automated anomaly detection systems.** - NOT IMPLEMENTED. A simple anomaly detection algorithm is recommended to be implemented to detect behavior that is atypical compared to normal for this contract. For instance, the contract must halt deposits in case a large amount is being withdrawn in a short period of time until the owner or the community of the contract approves further operations.
- [ ] **Multisig owner account.**
- [ ] **Standard ERC20-related issues.** - NOT IMPLEMENTED. It is known that every contract can potentially receive an unintended ERC20-token deposit without the ability to reject it even if the contract is not intended to receive or hold tokens. As a result, it is recommended to implement a function that will allow extracting any arbitrary number of tokens from the contract.
- [ ] **Crosschain address collisions.** ETH, ETC, CLO, etc. It is possible that a transaction can be sent to the address of your contract at another chain (as a result of a user mistake or some software fault). It is recommended that you deploy a "mock contract" that would allow you to withdraw any tokens from that address or prevent any funds deposits. Note that you can reject transactions of native token deposited, but you can not reject the deposits of ERC20 tokens. You can use this source code as a mock contract: [extractor contract source code](https://github.com/EthereumCommonwealth/GNT-emergency-extractor-contract/blob/master/extractor.sol). The address of a new contract deployed using `CREATE (0xf0)` opcode is assigned following this scheme `keccak256(rlp([sender, nonce]))`. Therefore you need to use the same address that was originally used at the main chain to deploy the mock contract at a transaction with the `nonce` that matches that on the original chain. _Example: If you have deployed your main contract with address 0x010101 at your 2021th transaction then you need to increase your nonce of 0x010101 address to 2020 at the chain where your mock contract will be deployed. Then you can deploy your mock contract with your 2021th transaction, and it will receive the same address as your mainnet contract._

# 5. Conclusion

The audited smart contract can be deployed. Only low severity issues were found during the audit.

It is recommended to adhere to the security practices described in pt. 4 of this report to ensure the contract's operability and prevent any issues that are not directly related to the code of this smart contract.
