### ISSUE TITLE
i want to audit my SC

### ISSUE THREAD

**Issue by quantumauditofficial** [EthereumCommonwealth/Auditing#539]
https://bscscan.com/token/0xb5cfc7b83c020109e466589ae18941f12ae22d44

How much about audit my SC?

**Comment by yuriy77k** [comment]
@quantumauditofficial  The audit fee is 857 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 7 days after payment.
