### ISSUE TITLE
Mermaid Finance

### ISSUE THREAD

**Issue by MermaidFinance** [EthereumCommonwealth/Auditing#540]
# Audit request
We would like to request an audit of our smart contract audit($MMD).

# Source code
https://github.com/MermaidFinance/MermaidToken/blob/main/contracts.sol

# Disclosure policy
Please notify us privately in case of finding critical mistakes. Otherwise, publish the report publicly.
[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md)

# Contact information (optional)
admin@mermaid.finance
admin@mermaid.exchange

https://mermaid.finance/
https://twitter.com/mermaid_finance

# Platform
BSC

We want to complete the audit before our smart contract is deployed
If possible, we are willing to pay a certain amount of expedite fee, thx

**Comment by MermaidFinance** [comment]
We want to complete the audit before our smart contract is deployed
If possible  we are willing to pay a certain amount of expedite fee  thx

**Comment by yuriy77k** [comment]
@MermaidFinance The Standard Priority Audit cost 1134 USDT. The estimated auditing time - 10 days after payment.
If you want to expedite, you may order Highest Priority Audit (it will cost 100% more) 2268 USDT, auditing time - 3 days after payment.

You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

**Comment by MermaidFinance** [comment]
OK thx, I ve send 1134U(ERC20), please check

**Comment by yuriy77k** [comment]
Thank you. Received

**Comment by yuriy77k** [comment]
The report was sent by email.

**Comment by MermaidFinance** [comment]
Thx for your hard work.We revised the contract as suggested, and explained some of them.How can we submit the updated smart-contract for re-audit?Thx.

**Comment by yuriy77k** [comment]
The re-audit cost 50% of initial audit (567 USDT).

**Comment by MermaidFinance** [comment]
> The re-audit cost 50% of initial audit (567 USDT).
Done, plz check, Hash:0x1ac212f92b0890d5a66eecc0985d28e2a95c0579619f90ed7653d9e544e61c73

**Comment by yuriy77k** [comment]
The report was sent by email.

**Comment by MermaidFinance** [comment]
> The report was sent by email.

sry, there was something wrong with our hosting, can you pls send us again? thx very much.

**Comment by yuriy77k** [comment]
> sry, there was something wrong with our hosting, can you pls send us again ? thx very much.

Sent again

**Comment by yuriy77k** [comment]
@MermaidFinance did you receive the report? May I publish it here?

**Comment by MermaidFinance** [comment]
> @MermaidFinance did you receive the report? May I publish it here?

hello sir, thank you very much for your many times of help, we are solving these issues now, plz give us sometime and we will send back our new contract, sry for the inconvenience.

**Comment by MermaidFinance** [comment]
> @MermaidFinance did you receive the report? May I publish it here?

Hello sir, we have just finished the revisoin, thx for your help X100, so sorry it took so long.

**Comment by yuriy77k** [comment]
The report was sent by email.

**Comment by MermaidFinance** [comment]
> The report was sent by email.

Thank you sir, we' ve fixed the issue, plz check.
With best regards.

**Comment by yuriy77k** [comment]
# Mermaid Finance v4 Security Audit Report

# 1. Summary

[Mermaid Finance](https://github.com/MermaidFinance/MermaidToken/blob/main/contracts.sol) smart contract security audit report performed by [Callisto Security Audit Department](https://github.com/EthereumCommonwealth/Auditing)

- https://mermaid.finance/
- https://twitter.com/mermaid_finance

# 2. In scope

Commit `70e16cc345b7c8f309746686b7e0eef212d86189`

[contracts.sol]https://github.com/MermaidFinance/MermaidToken/blob/70e16cc345b7c8f309746686b7e0eef212d86189/contracts.sol)

# 3. Findings

In total, **0 issues** were reported, including:

- 0 high severity issues.

- 0 medium severity issues.

- 0 low severity issues.

In total, **5 notes** were reported, including:

- 0 notes.

- 5 owner privileges.


## 3.1. Owner privileges

### Severity: owner privileges

### Description

Contract's owner has right to:

1. Exclude/include any account from/in fee, using functions [excludeFromFee](https://github.com/MermaidFinance/MermaidToken/blob/70e16cc345b7c8f309746686b7e0eef212d86189/contracts.sol#L914) and [includeInFee](https://github.com/MermaidFinance/MermaidToken/blob/70e16cc345b7c8f309746686b7e0eef212d86189/contracts.sol#L918).
2. Exclude/include any account from/in rewards, using functions [excludeFromReward](https://github.com/MermaidFinance/MermaidToken/blob/70e16cc345b7c8f309746686b7e0eef212d86189/contracts.sol#L891) and [includeFromReward](https://github.com/MermaidFinance/MermaidToken/blob/70e16cc345b7c8f309746686b7e0eef212d86189/contracts.sol#L901).
3. Change fees percentage without limitation, using functions [setBurnFeePercent](https://github.com/MermaidFinance/MermaidToken/blob/70e16cc345b7c8f309746686b7e0eef212d86189/contracts.sol#L922), [setTaxFeePercent](https://github.com/MermaidFinance/MermaidToken/blob/70e16cc345b7c8f309746686b7e0eef212d86189/contracts.sol#L926), [setLiquidityFeePercent](https://github.com/MermaidFinance/MermaidToken/blob/70e16cc345b7c8f309746686b7e0eef212d86189/contracts.sol#L930).
4. Change maximal amount per transaction (in percentage of `totalSupply`), using function [setMaxTxPercent](https://github.com/MermaidFinance/MermaidToken/blob/70e16cc345b7c8f309746686b7e0eef212d86189/contracts.sol#L934).
5. Enable or disable adding liquidity to pool, using function [setSwapAndLiquifyEnabled](https://github.com/MermaidFinance/MermaidToken/blob/70e16cc345b7c8f309746686b7e0eef212d86189/contracts.sol#L940).


# 4. Security practices

- [x] **Open-source contact**.
- [ ] **The contract should pass a bug bounty after the completion of the security audit.**
- [ ] **Public testing.**
- [ ] **Automated anomaly detection systems.** - NOT IMPLEMENTED. A simple anomaly detection algorithm is recommended to be implemented to detect behavior that is atypical compared to normal for this contract. For instance, the contract must halt deposits in case a large amount is being withdrawn in a short period of time until the owner or the community of the contract approves further operations.
- [ ] **Multisig owner account.**
- [ ] **Standard ERC20-related issues.** - NOT IMPLEMENTED. It is known that every contract can potentially receive an unintended ERC20-token deposit without the ability to reject it even if the contract is not intended to receive or hold tokens. As a result, it is recommended to implement a function that will allow extracting any arbitrary number of tokens from the contract.
- [ ] **Crosschain address collisions.** ETH, ETC, CLO, etc. It is possible that a transaction can be sent to the address of your contract at another chain (as a result of a user mistake or some software fault). It is recommended that you deploy a "mock contract" that would allow you to withdraw any tokens from that address or prevent any funds deposits. Note that you can reject transactions of native token deposited, but you can not reject the deposits of ERC20 tokens. You can use this source code as a mock contract: [extractor contract source code](https://github.com/EthereumCommonwealth/GNT-emergency-extractor-contract/blob/master/extractor.sol). The address of a new contract deployed using `CREATE (0xf0)` opcode is assigned following this scheme `keccak256(rlp([sender, nonce]))`. Therefore you need to use the same address that was originally used at the main chain to deploy the mock contract at a transaction with the `nonce` that matches that on the original chain. _Example: If you have deployed your main contract with address 0x010101 at your 2021th transaction then you need to increase your nonce of 0x010101 address to 2020 at the chain where your mock contract will be deployed. Then you can deploy your mock contract with your 2021th transaction, and it will receive the same address as your mainnet contract._

# 5. Conclusion

The audited smart contract can be deployed. No security issues were found during the audit. The notes about owner privileges were made.

It is recommended to adhere to the security practices described in pt. 4 of this report to ensure the contract's operability and prevent any issues that are not directly related to the code of this smart contract.

**Comment by yuriy77k** [comment]
Gist with report: https://gist.github.com/yuriy77k/ef3a66930980b0876cb788c2d1f1bd9e

**Comment by MermaidFinance** [comment]
> Gist with report: https://gist.github.com/yuriy77k/ef3a66930980b0876cb788c2d1f1bd9e

Thank you sir, how can we get a PDF or a blog link on the callisto.network website? Thx very much.

**Comment by yuriy77k** [comment]
https://callisto.network/mermaid-finance-token-security-audit/
