### ISSUE TITLE
I want to audit my contract

### ISSUE THREAD

**Issue by Pjb1994-1** [EthereumCommonwealth/Auditing#541]
# Audit request

Meadowbrown is a hyper-deflationary token,  
which rewards investors for holding  
tokens, while also incorporating the  
Buyback approach currently present in  
the stock market. 
Meadowbrown is to  
include automatic Buyback.

Bonus Holder Advantages 
● 2% rewards redistributed on every transaction 
● Join a trusted network of investors, who are confident in the BuyBack contract, and understand  
the potential for growth in implementing this concept.  
● Once the investors know that contract always buys after every sell, they feel confident about raise  
of the price and continue holding  
Tax Breakdown 
➔ 2% rewards to holders 
➔ 3% marketing tax 
➔ 6% Buy-Back tax 
➔ Slippage: 13%

Meadowbrown collects 6% Buyback tax on each transaction and maintains it under contract. 
Whenever a Sell happens, a fraction of the Buyback amount is used to automatically buy from  
the Liquidity Pool and burns those tokens accordingly. 
There are 3 advantages: 
1. Raise in Value 
○ After the tokens from the Liquidity pool are bought, the new BNB amount is added to the pool and  
the amount of the tokens are reduced, which results in an increase in price. 
2. Free BNB 
○ Once those tokens are burnt, it is like adding free BNB to the pool as there are no tokens to sell in the  
future. 
3. Trust & Reliability 
○ Investors can be relentlessly hesitant, and often get spooked by a bearish market. 
○ Because of the Buyback, Investors will never see more than 2 Sells at any time and 98% of the time,  
they will only see one Sell as there will always be a Buy from the contract.

Future Plans & meadowbrown Solutions
What happens if the owner maintaining the ownership of the contract? 
➔ Issue 1: If the owner has ill-will, he can make the contract non-tradeable. 
➔ Issue 2: Owner can always pull out the initial liquidity once the lock is over. 
➔ Issue 3: Because of Auto liquidity addition, Owner can always take out the new liquidity 
 whenever he wants, as it is not locked. 

Meadowbrown's vision
Our vision is to build an ecological system around MEADOWCOIN including spaces, working communities, real estate investment applications, eCommerce platforms, cryptocurrency exchanges that are suitable for everyone. This system will encourage the acceptance and utilization of MEADOWCOIN help promote demand and create value for sustainable development in the future.
A real estate investment application, eCommerce platform, the cryptocurrency exchange is designed to maximize the benefits of MEADOWCOIN. The long-term develop- ment-oriented MEADOWCOIN will become one of the used coins widely and replace existing coins.

# Source code

https://github.com/Pjb1994-1/Meadowcoin/blob/main/mdb.sol

# Disclosure policy

I want you to publish the report  to notify me privately in case of finding critical mistakes 
only standard disclosure policy link ...

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

... Provide information to contact you or the smart contract-developer in case high severity issues will be found ...

... Provide information about the media resources of the project you want us to audit (website/ twitter account/ reddit/ telegram channel/ etc.) ...

# Platform

My contract is deployed on BEP20

**Comment by yuriy77k** [comment]
@SNOSDEV The audit fee is 903 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 10 days after payment.
