### ISSUE TITLE
Token audit request

### ISSUE THREAD

**Issue by Nikiti4wzd** [EthereumCommonwealth/Auditing#544]
# Audit request

Token BEP20

# Source code

https://github.com/Nikiti4wzd/favor/blob/main/favor.sol

# Disclosure policy

Only standard disclosure policy link

# Contact information (optional)

Telegram: @picconuro
https://favor.capital

**Comment by yuriy77k** [comment]
@Nikiti4wzd The audit fee is 626 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 5 days after payment.
