### ISSUE TITLE
Audit request

### ISSUE THREAD

**Issue by freedom3316** [EthereumCommonwealth/Auditing#545]
# Audit request
DeCus is a high capital efficiency cross-chain custody system dedicated to bringing bitcoin to the DeFi ecosystem.

# Source code
https://github.com/decus-io/decus-auction-sol
https://github.com/decus-io/decus-core
# Disclosure policy

[Standard disclosure policy]

# Contact information (optional)
lynzhai@decus.io

# Platform
ETH

Want to know the price and timeline of audit first.
Looking forward to your reply.

**Comment by yuriy77k** [comment]
@freedom3316 The audit fee of https://github.com/decus-io/decus-auction-sol is 695 USDT.
The repository https://github.com/decus-io/decus-core can't be opened  (maybe it's private).

You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 5 days after payment.
