### ISSUE TITLE
Smart Contract Audit for Dogefather (BSC)

### ISSUE THREAD

**Issue by bcheeves** [EthereumCommonwealth/Auditing#546]
# Audit request

Dogefather is a frictionless yield-generating token deployed on the Binance Smart Chain.  The main purpose is to purchase and hold the token while it generates a yield. We have several products that we have been developing which will require the holder to have Dogefather tokens in order to utilize them.

# Source code

https://github.com/dogefatherBSC/dogefatherBSC/blob/main/dogefather.sol

# Disclosure policy

Notify us first

You may publish it, after notifying us and include the disclosure policy link

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)
emails:
bendogefatherbsc@gmail.com
info@dogefatherofficial.net
stephen@elementdelta.com

Telegram handles:
@into.311.benners
@StephenDogefather

Twitter:
https://twitter.com/Dogefatherbsc_
Youtube:
https://www.youtube.com/channel/UC8ozjoPsrwv3bdDHSYgsoCA
Instagram:
https://www.instagram.com/dogefatherbsc_/

# Platform
Binance Smart Chain (BSC)
BEP-20 token

**Comment by yuriy77k** [comment]
@bcheeves The audit fee is 995 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 10 days after payment.
