### ISSUE TITLE
wElcash audit

### ISSUE THREAD

**Issue by rucinpk** [EthereumCommonwealth/Auditing#547]
# Audit request

Dear Sir or Madam, We need to perform Smart Contract Audit of our new product which is wrapper for ElCash cryptocurrency. The deadline for audit is september 2021. wElCash represents ElCash on the Smart Chain Blockchain. Kind Regards, Patryk Rucinski Software Security Engineer.

We got no source code publicly available yet

# Disclosure policy

We don't want

... provide your conditions for publishing the report or leave only standard disclosure policy link ...

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

You can contact me.

... Provide information about the media resources of the project you want us to audit (website/ twitter account/ reddit/ telegram channel/ etc.) ...

# Platform

**Comment by yuriy77k** [comment]
@rucinpk to get audit quote send me, please, source code to yuri@callisto.network
