### ISSUE TITLE
Meso Finance audit

### ISSUE THREAD

**Issue by Takoyakiz2** [EthereumCommonwealth/Auditing#550]
# Audit request
We Auto-compound for users in farms 

# Source code

Please send me a dm in tele

# Disclosure policy

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)
https://www.meso.finance/
https://t.me/mesoF

# Platform
Polygon

**Comment by yuriy77k** [comment]
@Takoyakiz2 to get audit quote send me, please, source code to yuri@callisto.network
