### ISSUE TITLE
PolyShield

### ISSUE THREAD

**Issue by polyshield-finance** [EthereumCommonwealth/Auditing#551]
# Audit request

Yield farm + ERC20 + MasterChef + Burner Contract

# Source code
Verified Contracts:
Polyshield: https://polygonscan.com/address/0xf239e69ce434c7fb408b05a0da416b14917d934e
MasterChef: https://polygonscan.com/address/0x0Ec74989E6f0014D269132267cd7c5B901303306
Burner: https://polygonscan.com/address/0xfbb307fea8cdaf614b66f82d8d233c947b07c4f5

# Disclosure policy
Let us know first please.

# Contact information (optional)
team@polyshield.finance

https://t.me/polyshield

# Platform

... In which network will your contract be deployed? (EOS/TRX/ETC/ETH/CLO/UBQ/something else ) ...
Polygon (MATIC)

**Comment by yuriy77k** [comment]
@polyshield-finance The audit fee is 1103 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 10 days after payment.
