### ISSUE TITLE
Smart Contracts audit

### ISSUE THREAD

**Issue by braduf** [EthereumCommonwealth/Auditing#553]
# Audit request

The smart contracts include an ERC20 token with permit function as described in EIP2612. And a Relayer contract which role is to execute the permit and transferFrom so we can pay the fee for the transactions of our users. The deployment will be done in Polygon and the Matic bridge will be used to move tokens between Layer 2 and 1, so there is a Child token and a Root token with the respective interfaces needed for the Matic Bridge.

# Source code

... Give a link to the source code of contracts ...: In this zip you can find the source code: https://drive.google.com/file/d/1hZt8XE_-NWptiC94kMRwlH6g4k5WcrD-/view?usp=sharing

# Disclosure policy

... Do you want us to publish the report as it is or to notify you privately in case of finding critical mistakes? Please notify us privately

... provide your conditions for publishing the report or leave only standard disclosure policy link ...

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

... Provide information to contact you or the smart contract-developer in case high severity issues will be found: b.dufour@b4vtechnologies.nl

... Provide information about the media resources of the project you want us to audit (website/ twitter account/ reddit/ telegram channel/ etc.) ...

# Platform

... In which network will your contract be deployed? (EOS/TRX/ETC/ETH/CLO/UBQ/something else ): Polygon

**Comment by yuriy77k** [comment]
The contract code is not accessible. Please, provide a working link.
