### ISSUE TITLE
Quote for standard ERC20 token contract security audit?

### ISSUE THREAD

**Issue by ghost** [EthereumCommonwealth/Auditing#557]
# Audit request

Hello, we would like a quote please. 

We have deployed an standard ERC20 token and we want it to list it on Trust Wallet, for that we need a Security Audit, we used this service to create our token: https://tokenmint.io/, it creates a token based on a open souce open zepelin template: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/IERC20.sol 

# Source code

https://etherscan.io/address/0xa4f2fdb0a5842d62bbaa5b903f09687b85e4bf59#code

# Disclosure policy

Notify us first.

# Contact information (optional)

liga@tbotarmy.com
latroix@tbotarmy.com

website/DApp: https://tbotarmy.com/
discord: https://discord.com/invite/tbotarmy
rest of info in footer of main website.

# Platform

ETH

**Comment by yuriy77k** [comment]
@latroix The audit fee is 596 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 3 days after payment.
