### ISSUE TITLE
Token audit request

### ISSUE THREAD

**Issue by Nikiti4wzd** [EthereumCommonwealth/Auditing#558]
# Audit request

Token

# Source code

https://github.com/IndirectFavorCapital/FAVOR

# Disclosure policy

Notify in case of finding critical mistakes and publish after the fix.

Standard disclosure policy
https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md

# Contact information (optional)

Telegram: @picconuro
email: favor.capital@gmail.com

https://favor.capital
https://twitter.com/FavorCapital
https://www.reddit.com/user/FavorCapital

# Platform

BSC

**Comment by yuriy77k** [comment]
@Nikiti4wzd The audit fee is 510 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 3 days after payment.
