### ISSUE TITLE
Bitcoin Lottery - Security Audit

### ISSUE THREAD

**Issue by BTCLottery** [EthereumCommonwealth/Auditing#560]
# Audit request

We are looking to Audit our ERC677 Governance Token (BTCL TOKEN) and the Seed Round that uses ChainLink Price Feeds and has a built-in Vesting Schedule. We want to start with these contracts and then expand with all the rest of the Smart Contracts that we are now preparing to bring to the public.

Thank you very much in advance! 
Really looking forward to hear back from you with the Quote and the Audit Timelines.

# Source code
https://github.com/BTCLottery/BTCLToken-SeedRound-with-Vesting-and-Chainlink-PriceFeeds

# Disclosure policy

We are actively updating the Contracts and are preparing many more to be later Audited. We want to prioritize the Token and the Seed Round right now.

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

support@btclottery.io

# Platform

... In which network will your contract be deployed? (EOS/TRX/ETC/ETH/CLO/UBQ/something else ) ...

Ethereum Network

**Comment by yuriy77k** [comment]
@BTCLottery The audit fee is 956 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 8 days after payment.
