### ISSUE TITLE
# Audit request

### ISSUE THREAD

**Issue by Unive13** [EthereumCommonwealth/Auditing#562]
# Audit request

Token whose main functions are:

Total supply: 100M

10% TAX per transaction =

5% For holders

3% for charities

2% Auto Liquidity Pool 

Anti-dump mechanism to protect the community  (Limit of 500,000 tokens for trade, or 0.5% of the total supply).

# Source code

https://bscscan.com/address/0xf5c4ed0596c56872b6c210e623d4b5ade952f9c9

# Disclosure policy

I would like to be informed privately before publication.

[Standard Disclosure Policy] (https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

info@unive.space

Website: https://unive.space/

# Platform

BSC

**Comment by yuriy77k** [comment]
@Unive13 The audit fee is 880 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 8 days after payment.

**Comment by Unive13** [comment]
Hello,
I thought the audit was free?
Regards.

**Comment by yuriy77k** [comment]
Sorry, we do not provide free audits for now.
