### ISSUE TITLE
Audit XSP

### ISSUE THREAD

**Issue by XSwapProtocol** [EthereumCommonwealth/Auditing#568]
# Audit request

... Simple XRC20 contract 

# Source code

... https://github.com/XSwapProtocol/XSP/blob/main/Smart%20Contracts/XSP.sol

# Disclosure policy

... Do you want us to publish the report as it is or to notify you privately in case of finding critical mistakes? No PM

... provide your conditions for publishing the report or leave only standard disclosure policy link ...

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

... telegram : jay_xsp

... website : https://xinfin.uk
telegram group : https://t.me/XswapProtocol
telegram channel : https://t.me/XswapProtocolANN
twitter : https://twitter.com/XSwapProtocol
whitepaper : https://xinfin.uk/WhitepaperV1.pdf
medium : https://medium.com/@XSwapProtocol
github : https://github.com/XSwapProtocol
github swap : https://github.com/XRC20-Swap
email : support@xinfin.uk

# Platform

... In which network will your contract be deployed? (Xinfin ) ...

**Comment by yuriy77k** [comment]
The link https://github.com/XSwapProtocol/XSP/blob/main/Smart%20Contracts/XSP.sol can't be opened. Please, check permission.

**Comment by XSwapProtocol** [comment]
Yes sorry for modify link 
https://github.com/XSwapProtocol/XSP/blob/main/Smart%20Contracts/XSwapProtocol.sol

**Comment by yuriy77k** [comment]
The audit fee is 538 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 10 days after payment.
