### ISSUE TITLE
Sector Audit

### ISSUE THREAD

**Issue by sectorius** [EthereumCommonwealth/Auditing#569]
# Audit request

Smart contracts for sector investment platform

# Source code

https://github.com/sectorius/sector-contracts/tree/main/contracts

SECICO5.sol, SecToken4.sol

# Disclosure policy

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

Mail : vadimgolenkov@mail.ru

# Platform

BSC

**Comment by yuriy77k** [comment]
@sectorius the audit fee is 684 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 5 days after payment.

**Comment by sectorius** [comment]
Hello, Yuriy!
I'm ready to pay audit. 
Is address still correct? 
Regards, 
Vadim понедельник, 13 сентября 2021г., 12:19 +03:00 от Yuriy  ***@***.*** :

***@***.*** the audit fee is 684 USDT.

**Comment by sectorius** [comment]
I payed the audit.

**Comment by yuriy77k** [comment]
# Sector Token Security Audit Report

# 1. Summary

[Sector Token](https://github.com/sectorius/sector-contracts/tree/main/contracts) smart contract security audit report performed by [Callisto Security Audit Department](https://github.com/EthereumCommonwealth/Auditing)

> Smart contracts for sector investment platform

# 2. In scope

Commit [f7187e930d8442f942aa9186905c8330c1efdfa0](https://github.com/sectorius/sector-contracts/blob/f7187e930d8442f942aa9186905c8330c1efdfa0/contracts/)

- SecToken4.sol
- SECICO5.sol

# 3. Findings

In total, **1 issues** were reported, including:

- 0 high severity issues.

- 1 medium severity issues.

- 0 low severity issues.

In total, **0 notes** were reported, including:

- 0 notes.

- 0 owner privileges.


## 3.1. Loosing accuracy

### Severity: medium

### Description

Solidity does not support float point numbers. Therefore in the function [endICO](https://github.com/sectorius/sector-contracts/blob/f7187e930d8442f942aa9186905c8330c1efdfa0/contracts/SECICO5.sol#L133) if you pass in argument `_allocToken` 1000 tokens and `phase.totalDeposit` is 1001 tokens then `tokenPerWEI = _allocToken / phase.totalDeposit = 0`.

### Recommendation

In calculation [tokenPerWEI](https://github.com/sectorius/sector-contracts/blob/f7187e930d8442f942aa9186905c8330c1efdfa0/contracts/SECICO5.sol#L139) should be used nominator to avoid loosing accuracy. 

```Solidity 
        phase.tokenPerWEI = phase.allocToken.mul(1e18).div(phase.totalDeposit);
```

And when you use `phase.tokenPerWEI` in claim functions you have to use denominator:
```Solidity 
        uint256 reward = phase.tokenPerWEI.mul(user.amount).div(1e18);
```



# 4. Security practices

- [x] **Open-source contact**.
- [ ] **The contract should pass a bug bounty after the completion of the security audit.**
- [ ] **Public testing.**
- [ ] **Automated anomaly detection systems.** - NOT IMPLEMENTED. A simple anomaly detection algorithm is recommended to be implemented to detect behavior that is atypical compared to normal for this contract. For instance, the contract must halt deposits in case a large amount is being withdrawn in a short period of time until the owner or the community of the contract approves further operations.
- [ ] **Multisig owner account.**
- [x] **Standard ERC20-related issues.** - IMPLEMENTED. It is known that every contract can potentially receive an unintended ERC20-token deposit without the ability to reject it even if the contract is not intended to receive or hold tokens. As a result, it is recommended to implement a function that will allow extracting any arbitrary number of tokens from the contract.
- [ ] **Crosschain address collisions.** ETH, ETC, CLO, etc. It is possible that a transaction can be sent to the address of your contract at another chain (as a result of a user mistake or some software fault). It is recommended that you deploy a "mock contract" that would allow you to withdraw any tokens from that address or prevent any funds deposits. Note that you can reject transactions of native token deposited, but you can not reject the deposits of ERC20 tokens. You can use this source code as a mock contract: [extractor contract source code](https://github.com/EthereumCommonwealth/GNT-emergency-extractor-contract/blob/master/extractor.sol). The address of a new contract deployed using `CREATE (0xf0)` opcode is assigned following this scheme `keccak256(rlp([sender, nonce]))`. Therefore you need to use the same address that was originally used at the main chain to deploy the mock contract at a transaction with the `nonce` that matches that on the original chain. _Example: If you have deployed your main contract with address 0x010101 at your 2021th transaction then you need to increase your nonce of 0x010101 address to 2020 at the chain where your mock contract will be deployed. Then you can deploy your mock contract with your 2021th transaction, and it will receive the same address as your mainnet contract._

# 5. Conclusion

The audited smart contract must not be deployed. Reported issues must be fixed prior to the usage of this contract.

It is recommended to adhere to the security practices described in pt. 4 of this report to ensure the contract's operability and prevent any issues that are not directly related to the code of this smart contract.

**Comment by sectorius** [comment]
@yuriy77k we have updated our files with your remarks.
