### ISSUE TITLE
DAYSTAR COIN AUDIT

### ISSUE THREAD

**Issue by Daystarcoin** [EthereumCommonwealth/Auditing#571]
# Audit request

Be part of the world’s most valuable utility token on the polygon matic network

**Comment by yuriy77k** [comment]
@Daystarcoin the audit fee is 992 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 7 days after payment.
