### ISSUE TITLE
CFK Crypto for Kids

### ISSUE THREAD

**Issue by yonkopetkov** [EthereumCommonwealth/Auditing#573]
# Audit request

Creating a crypto community of people determined to change children's destinies. Every CFK token owner has the opportunity in an open forum to propose, create, vote, comment, control or participate personally in each project.

# Source code

https://bscscan.com/address/0xc22ef9f186ae6b57334cb5dc3af0e003a384b3ef#code#L1

# Disclosure policy

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

http://twitter.com/CFKproject

https://www.cryptoforkidsproject.com

# Platform

BSC

**Comment by yuriy77k** [comment]
@yonkopetkov the audit fee is 761 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 7 days after payment.
