### ISSUE TITLE
Smart Contract Audit Request

### ISSUE THREAD

**Issue by iamcrankin** [EthereumCommonwealth/Auditing#575]
# Audit request

Hi There!
 
I would like a smart contract audit for a generative NFT drop of up to 20,000 ERC 721 tokens.
 
We will have the code ready by October 4th for you to audit.
 
1. If I send you the code, how soon will you be able to 
    1. Determine scope?
    2. Determine when the audit will be complete?
2. How much is the audit?
3. What is your process?
4. What else do we need to know?
5. We need the code reviewed ASAP. We are launching October 11th and we need expedited review.
 
I am sure you can understand that we are moving at a lightning pace, given the tight deadline. Looking forward to your reply soon. Thank you so much for your help and hope we can work together.

connor@impacttheory.com

**Comment by yuriy77k** [comment]
The price and auditing time depends on the complexity of the smart contract.
Your smart contract will be reviewed by our auditors and you'll receive a report with found issues and recommendations on how to solve them.
If you will need a re-audit of the contract after fixing or adding new functions - you'll get a 50% discount.

**Comment by Dexaran** [comment]
>We will have the code ready by October 4th for you to audit.

If you will provide the source code on 4th October then we can evaluate how long the audit will take at the same day.
Basic token contract audit is not a hard task so it can be definitely completed before 11th.

This depends on the actual code however.
