### ISSUE TITLE
IGOCOIN/Auditing

### ISSUE THREAD

**Issue by ghost** [EthereumCommonwealth/Auditing#577]
# Audit request

IGOCOIN is token on Binance Smart Chain network can be used in the ecosystem for rewards, and other Defi features like staking and farming.

# Source code
https://bscscan.com/address/0x7f483b96cfcf0cc89d98e8215a36190eeeafa1cc#code

# Disclosure policy

... Do you want us to publish the report as it is or to notify you privately in case of finding critical mistakes? ...

support@igocoin.org

[Standard disclosure policy](https://github.com/Igocoin/Auditing).

# Contact information (optional)

... Provide information to contact you or the smart contract-developer in case high severity issues will be found ...
support@igocoin.org

... Provide information about the media resources of the project you want us to audit (website/ twitter account/ reddit/ telegram channel/ etc.) ...
www.igocoin.org, https://t.me/joinchat/hUhMQvf_9TY5Njcy
# Platform
BSC,

**Comment by yuriy77k** [comment]
@Igocoin  the audit fee is 594 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 7 days after payment.
