### ISSUE TITLE
SOY ERC223 token audit

### ISSUE THREAD

**Issue by Dexaran** [EthereumCommonwealth/Auditing#579]
# Audit request

SOY token contract.

Formal review of the SOY ERC223 token prior to mainnet deployment.

# Source code

https://github.com/SoyFinance/smart-contracts/blob/ed3043a984d84e918bda502b86938d15afa21624/SoyTokenERC223.sol

# Disclosure policy

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

dexaran@ethereumclassic.org

# Platform

CLO

**Comment by yuriy77k** [comment]
The report was sent to the developer.
