### ISSUE TITLE
CHOAM ERC223 token audit

### ISSUE THREAD

**Issue by Dexaran** [EthereumCommonwealth/Auditing#580]
# Audit request

CHOAM token contract.

Formal review of the CHOAM ERC223 token prior to mainnet deployment.

CHOAM token must have the following features in addition to the basic ERC20/ERC223 standard implementations:

- The token can only be transferred between "whitelisted" addresses
- Token must grant the rights to claim dividents to it's holder based on "payment date", when payment date occurs (which is indicated by the functin nextPaymentRoundSnapshot: https://github.com/EthereumCommonwealth/CHOAM_token/blob/37ac0a30129f298d401c9daef9f8394b48a5c778/ERC223ChoamToken.sol#L1004) users balances are recorded. After that a rigorous "calculation" on the side of the reward provider takes place off-chain and it takes a couple of days - then the reward is deposited and users become eligible to claim it https://github.com/EthereumCommonwealth/CHOAM_token/blob/37ac0a30129f298d401c9daef9f8394b48a5c778/ERC223ChoamToken.sol#L1011
- We don't care for how long the tokens were held. A user that acquired tokens 1 second before the snapshot will get a full amount of round reward for his quantity of tokens

# Source code

- CHOAM token contracat & revenue contract: https://github.com/EthereumCommonwealth/CHOAM_token/blob/37ac0a30129f298d401c9daef9f8394b48a5c778/ERC223ChoamToken.sol

- Whitelist contract: https://github.com/EthereumCommonwealth/CHOAM_token/blob/37ac0a30129f298d401c9daef9f8394b48a5c778/Whitelist.sol
- https://github.com/EthereumCommonwealth/CHOAM_token/blob/37ac0a30129f298d401c9daef9f8394b48a5c778/STO.sol

# Excluded

Whitelist.sol and STO.sol contracts are excluded from the scope of the audit and only provided as a reference of logic that CHOAM contract is intended to interact with.

# Disclosure policy

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

dexaran@ethereumclassic.org

# Platform

CLO

**Comment by yuriy77k** [comment]
The report was sent to the developer.
