### ISSUE TITLE
Eterland - Audit request

### ISSUE THREAD

**Issue by cgerabit** [EthereumCommonwealth/Auditing#592]
# Audit request

We have been working in a nft game called Eterland.  

We have the following contacts: 

- ERC20 Token called ETER
- ERC721 Token
- Vesting contract ( Here we based our contract in yograterol ERC20VestingWallet  [url](https://gist.githubusercontent.com/yograterol/4c7f03e7fc411e279c52b4be1e033b79/raw/ad0367819cd08524db25d206ff2310ab057ed56c/ERC20VestingWallet.sol) )
- Items Presell contract

we want to audit all those contracts including the ones inside of abstract folder

# Source code

https://github.com/Eterland/eterland-public-smart-contracts

# Disclosure policy

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

support@eterland.app or cristian@eterland.app

Websites: 
[Web](https://eterland.app/  )
[Whitepaper](https://whitepaper.eterland.app/)
Telegram:
[Telegram](https://t.me/joinchat/YfYVe_j4Uz1kMmQ5)
Twitter:
[Twitter](https://twitter.com/EterlandNft)
Discord:
[Discord](https://discord.com/invite/3eyHQWFZ4b)

# Platform

BSC

**Comment by cgerabit** [comment]
We had hurry, so we started the audit with other provider

**Comment by YormanDiLaurentiss** [comment]
Espero que el juego sea todo un éxito, felicidades.
