### ISSUE TITLE
Neku Finance 

### ISSUE THREAD

**Issue by Nekuio** [EthereumCommonwealth/Auditing#593]
# Audit request

... Briefly describe your smart-contract and its main purposes here ...

# Source code

... Give a link to the source code of contracts ...

# Disclosure policy

... Do you want us to publish the report as it is or to notify you privately in case of finding critical mistakes? ...

... provide your conditions for publishing the report or leave only standard disclosure policy link ...

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

... Provide information to contact you or the smart contract-developer in case high severity issues will be found ...

... Provide information about the media resources of the project you want us to audit (website/ twitter account/ reddit/ telegram channel/ etc.) ...

# Platform

... In which network will your contract be deployed? (EOS/TRX/ETC/ETH/CLO/UBQ/something else ) ...

**Comment by Nekuio** [comment]
Neku Finance is a decentralized and multi-chain lending protocol which was initially launched on Moonriver Network and Arbitrum. Neku allows depositors to provide liquidity to money markets to earn a passive interest income, while borrowers can borrow any assets available in Neku platform under the overcollateralized mortgage lending model. Neku Finance will expand to other chains, such as Celo, Klaytn, and BSC etc. in the near future.

Website: https://neku.io/
Community Links:
Twitter: https://twitter.com/NekuFinance
Medium: https://medium.com/@nekufinance
Telegram: https://t.me/nekufinance
Tech Links:
GitHub: https://github.com/nekufinanceio

Thanks for provide an audit service for us, please contact us with our telegram : @NeKuFinance1

We prefer to receive audit report privately before publishing to the public 

Best regards 

Neku Finance

**Comment by yuriy77k** [comment]
Hello @Nekuio.
Please, provide a link to the smart contract code to audit.

**Comment by Nekuio** [comment]
Hi Yuriy,
Thanks for helping us on auditing!
Here is the link for our github https://github.com/nekufinanceio.




________________________________

**Comment by Nekuio** [comment]
our contract link: https://github.com/nekufinanceio/nekufinanceio
[https://opengraph.githubassets.com/53a64188c893f50151ac83ec7da20ca23cee144d493d56ae5ab35710d0eef042/nekufinanceio/nekufinanceio]<https://github.com/nekufinanceio/nekufinanceio>
GitHub - nekufinanceio/nekufinanceio<https://github.com/nekufinanceio/nekufinanceio>
Contribute to nekufinanceio/nekufinanceio development by creating an account on GitHub.
github.com

________________________________

**Comment by yuriy77k** [comment]
@Nekuio  the audit fee is 2602 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 22 days after payment.
