### ISSUE TITLE
XAPP

### ISSUE THREAD

**Issue by xapptoken** [EthereumCommonwealth/Auditing#594]
# Audit request

...It is an automatic buyback and burn, auto-liquidity BEP20 smart contract. Tax is deducted in each transaction and stored in the contract. When swapandliquify function is enabled, the smart contract swaps the stored tax for BNB. The buyback function, when enabled utilizes these swapped BNB stored therein to perform automatic buybacks and burns the bought tokens instantly. The BNB used in the buyback purchase adds to the liquidity pool ...

# Source code

... https://bscscan.com/address/0x4c3a2556a2723a7852d711fe8e417f3ad2d03f56#code#L1 ...

# Disclosure policy

... Please notify me of any critical errors before publishing so that it can be fixed and as well protect the community from any FUD (fear, uncertainty or doubt)  ...

# Contact information (optional)

... support@xapptoken.com or https://t.me/XappYoshi ...

... https://xapptoken.com , https://twitter.com/xapptoken, https://t.me/xapptoken ...

# Platform

... BSC (Binance Smart Chain) ...

**Comment by yuriy77k** [comment]
@xapptoken the audit fee is 901 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 14 days after payment.
