### ISSUE TITLE
Tibetan mastiff audit request

### ISSUE THREAD

**Issue by Tokendev1224** [EthereumCommonwealth/Auditing#596]
# Audit request

It's named from my tibetan mastiff and no specify usage, it doesn't have any function and just for my own testing.

# Source code

https://bscscan.com/address/0x633353a8ae52e9fe26d6f0b615708de9be700d14#code

# Disclosure policy

Please only leave a standard disclosure policy link and mail to me, cryptocoin1224@gmail.com.

# Contact information (optional)

please send email to cryptocoin1224@gmail.com

# Platform

Binance Smart Chain

**Comment by yuriy77k** [comment]
@Tokendev1224 the audit fee is 627 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 7 days after payment.
