### ISSUE TITLE
Vitscoin _ Smart Contract Audit

### ISSUE THREAD

**Issue by vivekSm** [EthereumCommonwealth/Auditing#599]
# Audit request

... Briefly describe your smart-contract and its main purposes here ...

# Source code
https://bscscan.com/address/0x58992eb2743e738073c62f52b13b6919880baa43
... Give a link to the source code of contracts ...

# Disclosure policy

... Do you want us to publish the report as it is or to notify you privately in case of finding critical mistakes? ...

... provide your conditions for publishing the report or leave only standard disclosure policy link ...

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

... Provide information to contact you or the smart contract-developer in case high severity issues will be found ...

... Provide information about the media resources of the project you want us to audit (website/ twitter account/ reddit/ telegram channel/ etc.) ...

# Platform
BSC
... In which network will your contract be deployed? (EOS/TRX/ETC/ETH/CLO/UBQ/something else ) ...

**Comment by yuriy77k** [comment]
@vivekSm the audit fee is 699 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 7 days after payment.
