### ISSUE TITLE
PLS smart-contract-audit

### ISSUE THREAD

**Issue by vuongit21203** [EthereumCommonwealth/Auditing#605]
# Audit request

The BNBMATRIX smart contract provides the opportunity to invest any amount in BNB (from 0.01 BNB) in the contract and get 119% to 239% return on investment between 7 to 30 days if the contract balance has enough funds for payment.
The system used is called ROI and must be considered as HIGH-RISK. Do always invest with proper knowledge and investigation
Dividends are paid from deposits of users.
All dividends are calculated at the moment of request and available for withdrawal anytime
Each subsequent Deposit is kept separately in the contract, to maintain the payment amount for each Deposit.
# Source code

[... Give a link to the source code of contracts ...](https://testnet.bscscan.com/address/0x713d9321126913729106e3f56850214dbca507a8#code)

# Disclosure policy

yes

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

mail: vuongit2017@gmail.com
website: https://bnbx3.com/

# Platform
BSC

**Comment by yuriy77k** [comment]
@vuongit21203  the audit fee is 578 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 7 days after payment.
