### ISSUE TITLE
Lossless core protocol smart contracts audit request

### ISSUE THREAD

**Issue by losslesscash** [EthereumCommonwealth/Auditing#606]
# Audit request

We are first hack mitigation tool and we have developer our core Lossless protocol - WP is here https://lossless-cash.gitbook.io/lossless/.

# Source code

It is private repo, please let me know what to add there, I will ask our CTO to share repo with you. 

# Disclosure policy

... Do you want us to publish the report as it is or to notify you privately in case of finding critical mistakes? ...

Private audit report

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

domantas@lossless.cash @domantasp (telegram) - CTO
vygandas@lossless.cash @vygandas1 (telegram) - CEO (me)

# Platform

ETH, BSC, Polygon, Harmony

**Comment by yuriy77k** [comment]
@losslesscash please add me to the repository with reading right. My email: yuri@callisto.network
