### ISSUE TITLE
ERC20 Smart contract for 24Gold - Audit required as soon as possible.

### ISSUE THREAD

**Issue by mahmudsumi** [EthereumCommonwealth/Auditing#609]
# Audit request

... Briefly describe your smart contract and its main purposes here ...
-- Our smart contract is constructed to deploy tokens that are asset/utility 1:1 allocated coins for gold, silver, platinum, palladium. Our purpose is to provide our clients with a different payment service using crypto. This would allow them to deposit physical precious metals, and receive our tokens in return. They would then be able to transfer these tokens into our trading platform to hedge them against the market prices. Or just utilise these tokens as an investment, for withdrawal at a later stage. They will also be able to transfer amongst people to leverage their prices. 

# Source code

... Give a link to the source code of contracts ...
-- We are currently completing the compilation as well as automated testing for our cases. We will have this completed by Wednesday, 15/12. We would like to onboard the audit team and start discussions so that we can have this audited starting next week. If we could have a call to do a preliminary discussion that would be great. 

# Disclosure policy

... Do you want us to publish the report as it is or to notify you privately in case of finding critical mistakes? ...
We would like to receive feedback about the critical mistakes privately. We would like to publish the final report publically. 

... provide your conditions for publishing the report or leave only standard disclosure policy link ...
-- Standard disclosure policy has been reviewed and approved.

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)
--  Email - sumi@24gold.com
-- Phone - +971502080110
-- Website - 24gold.com

... Provide information to contact you or the smart contract-developer in case high severity issues will be found ...
axel@24gold.com 
sumanta.pramanick@kelltontech.com

... Provide information about the media resources of the project you want us to audit (website/ twitter account/ reddit/ telegram channel/ etc.) ...
-- Website - 24gold.com

# Platform
... In which network will your contract be deployed? (EOS/TRX/ETC/ETH/CLO/UBQ/something else ) ...
ETH - ERC20 contract

**Comment by yuriy77k** [comment]
@mahmudsumi, you need to provide a contract code to get a quote. 
If you have questions, you can contact me in telegram: @yuriy77k
