### ISSUE TITLE
ComBox

### ISSUE THREAD

**Issue by yuriy77k** [EthereumCommonwealth/Auditing#61]
# Audit request

ComBox Technology token sale goes through investors dashboard, funds are collecting on HD individual BTC and ETH addresses. That allows us working Bitcoin and Ethereum sent from any type of wallets, including crypto exchanges accounts, and that is why we have not implemented any crowd sale functions in our smart-contract.
Because of security reasons all collected funds are transferred to cold storage wallets on daily basis, meantime ERC20 tokens are transferred to investors.

# Source code

https://github.com/combox-io/smart-contracts/

# Disclosure policy

inform@combox.io

# Platform

ETH

# Complexity

Low

**Comment by MrCrambo** [comment]
Auditing time 1 day

**Comment by yuriy77k** [comment]
@MrCrambo assigned

**Comment by RideSolo** [comment]
Auditing time:  ~1 day

**Comment by yuriy77k** [comment]
@RideSolo assigned

**Comment by danbogd** [comment]
Auditing time: ~2 days.

**Comment by yuriy77k** [comment]
@danbogd assigned.

**Comment by danbogd** [comment]
My report is finished.

**Comment by yuriy77k** [comment]
@danbogd Notes about your report: https://gist.github.com/danbogd/27b79c570d63a57cf3576f508e0ed2dd

[3.1](https://gist.github.com/yuriy77k/c26f060c672b17d566e9aa9a99e9abab#31-newowner-is-no-checking-for-zero-address) and [3.4](https://gist.github.com/yuriy77k/c26f060c672b17d566e9aa9a99e9abab#34-function-acceptownership-does-not-work) in not issues. At first Owner set newOwner address, then new owner need to call  `acceptOwnership` from newOwner address.
