### ISSUE TITLE
I'm out of money, I'm throwing a tx hash, find a solution please

### ISSUE THREAD

**Issue by Muroo42** [EthereumCommonwealth/Auditing#622]
https://bscscan.com/tx/0xe7764a9a84900acb0b053e67f29c4db02eb2dbfa21b530e36bd13bb52f776dd7# Audit request

... Briefly describe your smart-contract and its main purposes here ...

# Source code

... Give a link to the source code of contracts ...

# Disclosure policy

... Do you want us to publish the report as it is or to notify you privately in case of finding critical mistakes? ...

... provide your conditions for publishing the report or leave only standard disclosure policy link ...

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

... Provide information to contact you or the smart contract-developer in case high severity issues will be found ...

... Provide information about the media resources of the project you want us to audit (website/ twitter account/ reddit/ telegram channel/ etc.) ...

# Platform

... In which network will your contract be deployed? (EOS/TRX/ETC/ETH/CLO/UBQ/something else ) ...

**Comment by Muroo42** [comment]
Callisto

**Comment by yuriy77k** [comment]
@Muroo42 I see on your account 10 CLO. It's more than enough to do a claim requests.
https://explorer.callisto.network/address/0xf33350b3778985A606468906908eb002644c2D59/transactions

**Comment by Muroo42** [comment]
I made a bridge transfer, but bnb did not come to the callisto network and I do not understand how I am making a claim.
