### ISSUE TITLE
Cold Staking v.2

### ISSUE THREAD

**Issue by yuriy77k** [EthereumCommonwealth/Auditing#63]
# Audit request

Cold Staking -  new formula.

# Source code

https://github.com/yuriy77k/Cold-staking

# Disclosure policy

public

# Platform

CLO

**Comment by gorbunovperm** [comment]
Estimated auditing time is 3 days.

**Comment by yuriy77k** [comment]
@gorbunovperm assigned

**Comment by RideSolo** [comment]
Auditing time: 2 days.

**Comment by yuriy77k** [comment]
@RideSolo assigned

**Comment by gorbunovperm** [comment]
@yuriy77k My report is finished.
