### ISSUE TITLE
0xdac17f958d2ee523a2206206994597c13d831ec7 这是一个真的合约地址吗？

### ISSUE THREAD

**Issue by 18673690248** [EthereumCommonwealth/Auditing#649]
# Audit request

... Briefly describe your smart-contract and its main purposes here ...

# Source code

... Give a link to the source code of contracts ...

# Disclosure policy

... Do you want us to publish the report as it is or to notify you privately in case of finding critical mistakes? ...

... provide your conditions for publishing the report or leave only standard disclosure policy link ...

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)   这是一个真的合约地址吗？在这个地址上我被骗去了6万人民币 希望能得到你们的帮助

... Provide information to contact you or the smart contract-developer in case high severity issues will be found ...

... Provide information about the media resources of the project you want us to audit (website/ twitter account/ reddit/ telegram channel/ etc.) ...

# Platform

... In which network will your contract be deployed? (EOS/TRX/ETC/ETH/CLO/UBQ/something else ) ...

**Comment by 18673690248** [comment]
[0xdac17f958d2ee523a2206206994597c13d831ec7 这是一个真正的合约地址吗？](https://github.com/EthereumCommonwealth/Auditing/issues/649#)。   就是这个合约地址骗去了我的血汗钱。6万人民币。哭哭😭。 希望能得到帮助。 🙏🙏

**Comment by HawaiiToastNo1** [comment]
0xdac17f958d2ee523a2206206994597c13d831ec7 - this smart contract has stolen my 50k USDT funds from Trust Wallet!

**Comment by HawaiiToastNo1** [comment]
And what is the result??????

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by yuriy77k** [comment]
> 0xdac17f958d2ee523a2206206994597c13d831ec7 - this smart contract has stolen my 50k USDT funds from Trust Wallet!

this is USDT token address on Ethereum chain: https://etherscan.io/address/0xdac17f958d2ee523a2206206994597c13d831ec7#code

We are not connected with the Tether company which is the owner of that contract.
