### ISSUE TITLE
Athena Crypto Bank Smart Contract Audit

### ISSUE THREAD

**Issue by snaptrck** [EthereumCommonwealth/Auditing#660]
# Audit request

can we request for a quote on our project that needs to be audited?

We made it public by now, you can find it here 

# Source code

(https://github.com/AthenaCryptoBank/smart-contracts.)

# Payment plan

... Write [x] at the checkbox of the payment plan that suits your needs ...

- [x] Standard (standard projects such as ICOs, ERC20, ERC223, ERC721, ERC721A tokens and NFTs fall in this category - 2 auditors. $500 + $1 per line of code / minimum $1000)
- [] Advanced (non-standard projects requiring more careful review - 3 auditors. $1000 + $1.25 per line / minimum $2000)
- [ ] Corporate (projects that require post-launch support - 3 auditors - Callisto Team will handle the bugbounty and provide a 1 month long period of technical support regarding the necessary security enhancement procedures and track/highlight any issues and potential threats - this plan allows to further apply for Callisto DAPP Insurance program)

# Disclosure policy

.Notify privately

standard disclosure policy

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

... Provide information to contact you or the smart contract-developer in case high severity issues will be found ...

... Provide information about the media resources of the project you want us to audit (Athenacryptobank.io)

# Platform

... In which network will your contract be deployed? Binance smart chain

**Comment by AtosDev** [comment]
Hi, @snaptrck 
I cannot see your public source code, could you provide them so that I can submit estimation for audit?

**Comment by yuriy77k** [comment]
@snaptrck Looks like https://github.com/AthenaCryptoBank/smart-contracts is "private". Please, make it public to get estimates time, and quotes.
