### ISSUE TITLE
TDAO JoDW gov smart contract

### ISSUE THREAD

**Issue by Floyd-Itter** [EthereumCommonwealth/Auditing#668]
# Audit request
Official governenace token of TalentDAO

# Source code
https://github.com/Talent-DAO/jodw-web/blob/develop/packages/hardhat/contracts/TalentDaoToken.sol 

# Payment plan
- [ ] Standard (standard projects such as ICOs, ERC20, ERC223, ERC721, ERC721A tokens and NFTs fall in this category - 2 auditors. $500 + $1 per line of code / minimum $1000)
- [x] Advanced (non-standard projects requiring more careful review - 3 auditors. $1000 + $1.25 per line / minimum $2000)
- [ ] Corporate (projects that require post-launch support - 3 auditors - Callisto Team will handle the bugbounty and provide a 1 month long period of technical support regarding the necessary security enhancement procedures and track/highlight any issues and potential threats - this plan allows to further apply for Callisto DAPP Insurance program)

# Disclosure policy
Notify us in private
[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)
floyd.itter@gmail.com 
https://www.talentdao.io/ 

# Platform
ETH

**Comment by Floyd-Itter** [comment]
Seeking for an audit of our governance token

**Comment by Dexaran** [comment]
cc @yuriy77k

**Comment by yuriy77k** [comment]
@Floyd-Itter  the audit fee is 2000 USDT.
You may send USDT (ERC20 or BEP20) to: 0x6317c6944bd1cD3932d062cce39d7Fd602119529

The estimated auditing time - is 7 days after payment.
