### ISSUE TITLE
Honeywood smart contract audit

### ISSUE THREAD

**Issue by Velmattur** [EthereumCommonwealth/Auditing#670]
# Audit request

We need to check security, liability and stability of a contract  for token listing on BitMart. The puropse of smart-contract is to provide utility tokens 

# Source code

https://github.com/MonetaToday/honeywood-blockchain

# Payment plan

... Write [x] at the checkbox of the payment plan that suits your needs ...

- [x] Standard (standard projects such as ICOs, ERC20, ERC223, ERC721, ERC721A tokens and NFTs fall in this category - 2 auditors. $500 + $1 per line of code / minimum $1000) 
- [ ] Advanced (non-standard projects requiring more careful review - 3 auditors. $1000 + $1.25 per line / minimum $2000)
- [ ] Corporate (projects that require post-launch support - 3 auditors - Callisto Team will handle the bugbounty and provide a 1 month long period of technical support regarding the necessary security enhancement procedures and track/highlight any issues and potential threats - this plan allows to further apply for Callisto DAPP Insurance program)

# Disclosure policy

... Do you want us to publish the report as it is or to notify you **privately** in case of finding critical mistakes? Privately

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

law@moneta.today
honeywood.io

# Platform

... In which network will your contract be deployed? ETH

**Comment by yuriy77k** [comment]
@Velmattur provided source code does not contain Solidity smart contracts.
