### ISSUE TITLE
iCrosschain Audit request

### ISSUE THREAD

**Issue by thanhpn** [EthereumCommonwealth/Auditing#675]
# Audit request

Main function 1: bridge and swap
- Our smart contract main task is to perform the token swap with liquidity pools, depending on the user's request, we will swap the user's token to another token.
In addition, the contract will also act as a bridge between different chains, for example, if a user wants to swap tokens from BSC to FANTOM, the contract on BSC will receive information and process swap transactions in exchange for USDT, then provide an event for the bridge to know to proceed with the steps on FANTOM. In the FANTOM chain, the contract will be called from the operators managed by us, the contract only allows the operators to call the swap token function with the USDT owned by the contract.

Main function 2: Stake pool
- Smart contracts allow users to stake tokens into the contract to liquidate the token rotation between chains. Users when staking tokens into the contract, the contract will save information about the token amount. At the same time, the contract also allows users to withdraw staked tokens and also share profits from staking. The decision of the user's profit and reward will be decided by the system based on the actual trading situation. When the user wants to withdraw the token from the contract, the user needs to ask the system to authenticate and create a request to submit to the contract, the contract will validate the information and verify the signature of the manager, validator, number of tokens available to the user to process the payment.
- In addition, the user also receives a reward from the system with the project's token, the calculation of the reward is also calculated and decided by the system, the user needs to create a request to receive the reward and send that information to the contract. PoolReward coin to verify the request.

Main function 3: Referral reward
- ReferralBonus this smart contract allows users to claim fee share from their referer. user need to create claim request to system to check how many bonus has created. Smart contract will validate the input generated by system

# Source code

Private source code

# Payment plan

... Write [x] at the checkbox of the payment plan that suits your needs ...

- [] Standard (standard projects such as ICOs, ERC20, ERC223, ERC721, ERC721A tokens and NFTs fall in this category - 2 auditors. $500 + $1 per line of code / minimum $1000)
- [x] Advanced (non-standard projects requiring more careful review - 3 auditors. $1000 + $1.25 per line / minimum $2000)
- [ ] Corporate (projects that require post-launch support - 3 auditors - Callisto Team will handle the bugbounty and provide a 1 month long period of technical support regarding the necessary security enhancement procedures and track/highlight any issues and potential threats - this plan allows to further apply for Callisto DAPP Insurance program)

# Disclosure policy

we prefer to Standard Disclosure Policy.

... provide your conditions for publishing the report or leave only standard disclosure policy link ...

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)
email: ngocthanh2207@gmail.com

... Provide information about the media resources of the project you want us to audit (website/ twitter account/ reddit/ telegram channel/ etc.) ...
- Website: https://icrosschain.io
- Twitter: https://twitter.com/iCrossChain
- Telegram: https://t.me/iCrosschainchannel

# Platform

... In which network will your contract be deployed? (EOS/TRX/ETC/ETH/CLO/UBQ/something else ) ...
- ETH
- BNB
- FANTOM
- POLYGON
- AVALANCHE
- HECO
- OKX
- Optimism
- Cronos

**Comment by yuriy77k** [comment]
@thanhpn to get quote and estimate audit time send me the source code to email yuriy@callistoenterprise.com

**Comment by yuriy77k** [comment]
@thanhpn I did not receive the source code of the contracts. Did you send it?

**Comment by yuriy77k** [comment]
@thanhpn, are you interested in the audit?
