### ISSUE TITLE
foodnation

### ISSUE THREAD

**Issue by yuriy77k** [EthereumCommonwealth/Auditing#68]
# Audit request

Pre-Sale SmartContract
We create a smart contract to hold our pre sale. The pre-sale consists of 3 milestones:
1 - 21 sep 2018 - 21 oct 2018
2 - 21 oct 2018 - 21 nov 2018
3 - 21 nov 2018 - 21 dec 2018
There is an escrow that holds the funds until the end of the presale, once the soft cap is reached, the funds are forward to a wallet. If we do not reach the soft cap, every buyer can claim refund.

# Source code

https://github.com/foodnation/contracts/blob/master/PreSale.sol

# Disclosure policy

nikola.wyatt@foodnation.io

# Platform

ETH

# Complexity

Low

**Comment by yuriy77k** [comment]
You could follow the audit queue there: https://github.com/EthereumCommonwealth/Auditing/blob/master/queue.md

**Comment by MrCrambo** [comment]
Auditing time 1 day

**Comment by RideSolo** [comment]
Auditing time: ~ 1 day

**Comment by yuriy77k** [comment]
@RideSolo assigned

**Comment by yuriy77k** [comment]
@MrCrambo assigned

**Comment by danbogd** [comment]
Аuditing time: ~3 days.

**Comment by yuriy77k** [comment]
@danbogd assigned

**Comment by danbogd** [comment]
My report is finished.
