### ISSUE TITLE
Auction demo contract audit report

### ISSUE THREAD

**Issue by Kunalmishra1999** [EthereumCommonwealth/Auditing#710]
Summary: This is the audit report from a security audit performed on testAuction.sol by Kunal Mishra. This contracts is based on auction of tokens and openzeppelin libararies are used.
The audit focused primarily on the security of testAuction.sol contract

InScope: TestAuction.sol

Note: I did not mention the severity here.

LOC - 56 : No check for what transFrom() returns 

LOC - 120 : Whether USDT contract has a transFrom() function + no check for what the transferFrom() returns.

LOC - 87 : Since, userDepositedUSD is always less than totalRaisedUSD, amontOfTokens will always be 0. Consider multiplication with supplyToDistribute before division with totalRaisedUSD.

LOC - 88 : No checks for what the transfer() function returns.

LOC - 112: In function depositAuction(), there is no check if the user really deposited BNB. For eg, a user would send _amount = 100, _isUSDT = false, and call depositAuction(). This would set the user.bnbAmount to 100. This all would happen without the user sending a single BNB token. Finally, after the auction ends, the user would call the claimTokens() to claim offeringToken, without paying a single BNB token.

**Comment by yuriy77k** [comment]
This repository is for audit requests only. DON'T SPAM HERE!

**Comment by Kunalmishra1999** [comment]
yes I have reported the bugs in the contract which you give me in total  6 bugs I have reported till now.
