### ISSUE TITLE
BitUnits

### ISSUE THREAD

**Issue by yuriy77k** [EthereumCommonwealth/Auditing#72]
# Audit request

BitUnits is a ERC223 smart contract token.Our goal is to first educate people on the various applications of blockchain and the best way to develop familiarity is to use cryptocurrency first hand. 

# Source code

https://gist.github.com/yuriy77k/d0d28a553000ddc1a64f63b0fb4d4b05

the same as: 
http://etherhub.io/addr/0xd1c10d433c888e6d1841ff924d0ce45157f0d5cd#tab_addr_3

# Disclosure policy

iabcdigitals@BitUnits.Club

# Platform

ETC

# Complexity

Low

**Comment by yuriy77k** [comment]
You could follow the audit queue there: https://github.com/EthereumCommonwealth/Auditing/blob/master/queue.md

**Comment by danbogd** [comment]
Auditing time: ~3 days.

**Comment by pro100skm** [comment]
Auditing time: 1 day

**Comment by danbogd** [comment]
My report is finished.

**Comment by yuriy77k** [comment]
@pro100skm assgined

**Comment by yuriy77k** [comment]
@danbogd assigned

**Comment by RideSolo** [comment]
Auditing time: 1 day.

**Comment by yuriy77k** [comment]
@danbogd 
Note about your report:
* [3.1. ERC223 Standard Compliance](https://gist.github.com/danbogd/be07b78812be8fb0635a2af8e0795865#31-erc223-standard-compliance). The reviewed token contract is ERC223 fully compliant, transferToContract function member of ERC223Token contract call tokenFallback external function on the receiver contract [AFTER](https://gist.github.com/yuriy77k/d0d28a553000ddc1a64f63b0fb4d4b05#file-bitunits-sol-L102-L104) adding the value to balances[_to].
