### ISSUE TITLE
DAO Crowdsale

### ISSUE THREAD

**Issue by himgajria** [EthereumCommonwealth/Auditing#75]
# Audit request

I would like to get an audit of my contracts. This is a package of 4 contracts for a DAO Crowdsale with an ERC20 Token. It uses the following contracts - DAO, DAOToken, DAOTokenCrowdsale, Vault.

# Source code

https://pastebin.com/nBC8MCKL
https://pastebin.com/bNeCpVHE
https://pastebin.com/3QK8YBDr
https://pastebin.com/RgU1Vh7T

# Disclosure policy

Permission to Publish Publicly
beachman1997@gmail.com

# Platform

ETH Mainnet

**Comment by himgajria** [comment]
@yuriy77k How do I get this audited ? Have i done something wrong ?

**Comment by yuriy77k** [comment]
@himgajria we provide free audit for contract developer. Can you prove that you are developer? The prove may be project web site were you are a team member.
