### ISSUE TITLE
 BCT

### ISSUE THREAD

**Issue by yuriy77k** [EthereumCommonwealth/Auditing#81]
# Audit request

The first mineable ERC-223 token. Same economics as Bitcoin, on ETC.

https://classicbitcoin.org/

# Source code

https://gist.github.com/yuriy77k/341c72bb372a30a98df9ebd7797ecac1

# Disclosure policy

https://twitter.com/BitcoinClassicT

# Platform

ETC

# Complexity

Low

**Comment by danbogd** [comment]
Auditing time: ~2 days.

**Comment by yuriy77k** [comment]
@danbogd assigned

**Comment by danbogd** [comment]
My report is finished.

**Comment by alexo18** [comment]
auditing time : 2 days

**Comment by yuriy77k** [comment]
@alexo18 assigned

**Comment by pro100skm** [comment]
Auditing time: 1 day

**Comment by yuriy77k** [comment]
@pro100skm assigned

**Comment by yuriy77k** [comment]
# 1. Summary

[BCT](http://etherhub.io/addr/0x1be6d61b1103d91f7f86d47e6ca0429259a15ff0#tab_addr_3) security audit report performed by [Callisto Security Audit Department](https://github.com/EthereumCommonwealth/Auditing)

# 2. In scope

# 3. Findings

In total, **1 issues** were reported including:

- 1 low severity issues.

No critical security issues were found.

## 3.1.

### Severity: low

### Description

There are possibility of accidentally sending tokens to zero address in [`transfer`](https://gist.github.com/yuriy77k/341c72bb372a30a98df9ebd7797ecac1#file-bct-sol-L239-L254) functions.

# 4. Conclusion

No critical vulnerabilities were detected.This contract can be considered safe to be deployed.

# 5. Revealing audit reports

https://gist.github.com/yuriy77k/1732c02ee4d146142a670a4438c65a9d

https://gist.github.com/yuriy77k/5490d082d862bed8021595112786fcde

https://gist.github.com/yuriy77k/4312bfddd72e018a011a0c10023694a2
