### ISSUE TITLE
Wallie

### ISSUE THREAD

**Issue by yuriy77k** [EthereumCommonwealth/Auditing#83]
# Audit request

WALLIE - distribution contract

# Source code

https://gist.github.com/yuriy77k/ed24d1dcdfceb7a41b0690667157ecbf

# Disclosure policy

wallieme.project@gmail.com

# Platform

ETH

# Complexity

Low

**Comment by yuriy77k** [comment]
You could follow the audit queue there: https://github.com/EthereumCommonwealth/Auditing/blob/master/queue.md

**Comment by alexo18** [comment]
auditing time : 2 days

**Comment by yuriy77k** [comment]
@alexo18 assigned

**Comment by yuriy77k** [comment]
@alexo18 assigned

**Comment by pro100skm** [comment]
Auditing time : 2 days

**Comment by danbogd** [comment]
Auditing time: ~ 3 day.

**Comment by yuriy77k** [comment]
@pro100skm @danbogd  assigned.

**Comment by danbogd** [comment]
My report is finished.

**Comment by yuriy77k** [comment]
# 1. Summary

[Wallie](https://etherscan.io/address/0xC0B52b76055C392D67392622AE7737cdb6D42133#code) security audit report performed by [Callisto Security Audit Department](https://github.com/EthereumCommonwealth/Auditing)

The audited contract based on the Ponzi scheme. New players will send the ether that will pay the profits and affiliate commissions of other users.

# 2. In scope



# 3. Findings

In total, **1 issues** were reported including:

- 1 low severity issues.

No critical security issues were found.

## 3.1. Wrong stats

### Severity: low

### Description

Wrong calculating of stats [118-137](https://gist.github.com/yuriy77k/ed24d1dcdfceb7a41b0690667157ecbf#file-wallie-sol-L118-L137). For example: [`all_cash_back_payments`](https://gist.github.com/yuriy77k/ed24d1dcdfceb7a41b0690667157ecbf#file-wallie-sol-L136) may be increased till of triple value of current [`amount`](https://gist.github.com/yuriy77k/ed24d1dcdfceb7a41b0690667157ecbf#file-wallie-sol-L112).

# 4. Conclusion

Investing into financial schemes can represent a significant high risk when a Ponzi scheme is identified. No critical vulnerabilities were detected.

# 5. Revealing audit reports

https://gist.github.com/yuriy77k/853848e95b1c6b116383d0dab29209b9

https://gist.github.com/yuriy77k/ac941958ed0c48e91f6f5351daae8a5c

https://gist.github.com/yuriy77k/7453342a36ac13dadae32381aea0db9c

**Comment by yuriy77k** [comment]
Investors can lose their money if they don’t pick it up on time - this is a common situation for Ponzi schemes. This cannot be considered a smart contract security issue.
