### ISSUE TITLE
Natmin v2

### ISSUE THREAD

**Issue by yuriy77k** [EthereumCommonwealth/Auditing#92]
# Audit request

This is an ERC20/ERC223 token contract

# Source code

https://github.com/natminpureescrow/token

# Disclosure policy

jaco@natmin.io

# Platform

ETH

# Complexity

Low

**Comment by MrCrambo** [comment]
Auditing time 1 day

**Comment by yuriy77k** [comment]
@MrCrambo assigned

**Comment by RideSolo** [comment]
Auditing time: 1 day

**Comment by yuriy77k** [comment]
@RideSolo assigned

**Comment by danbogd** [comment]
Auditing time: 2 days.

**Comment by danbogd** [comment]
My report is finished.

**Comment by yuriy77k** [comment]
@danbogd assigned
