### ISSUE TITLE
HyipProfit

### ISSUE THREAD

**Issue by yuriy77k** [EthereumCommonwealth/Auditing#94]
# Audit request

Я думаю вас контракт заинтересует своей необычностью.
Контракт токена ERC-20
трекер HYIP
кол-во 4500000

4 стадии продаж токенов:
пресейл: 0,0008 ETH софткэп 250 ETH
1 этап 0,0016 ETH
2 этап 0,0024 ETH
3 этап 0,0032 ETH

В контракте реализована система защиты средств пользователей в виде эскроу.
В случае если инвестор заподозрит, что его средства тратятся не на продвижение проекта или просто не грамотно, или просто захочет вывести свои средства с контракта, то он на каждом из этапов может вывести свои средства с контракта  просто вернув токены на него.
Подробнее: 
После того как будет собрана полная сумма Presale, команда запускает проект и получает возможность израсходовать первую часть средств –30% от собранных инвестиций. 
На каждый следующий этап с повышением цены токена команда может перейти только собрав в два раза бОльшую сумму от той, которую выделит контракт на каждый этап, продавая токены, по сути тратя 1 эфир, а привлекая 2. - это есть обязательное условие и показатель грамотного расходования командой средств.
Если проще по эскроу, то: пользователь может вывести те средства, которые еще не были выделены на траты команде. то есть, на первом этапе ползователь может вывести только 70% средств, если посчитает нужным. 
по окончании ICO контракт высчитает и распределит на кошельки команды 20% - доля команды проекта а так же резерв на баунти и т.п. 4% останется на контракте.

Я постарался как можно коротко описать его, но если появятся вопросы, то всегда готов на них ответить. телеграм: @angrytime или на почту.
Будет хорошо если на данном этапе вы найдете что-то критичное. Наш контракт уже в работе, но хотелось бы услышать ваше профессиональное заключение. Исходный код виден полностью, на нечего скрывать.
Кстати, совсем недавно разработчик стандарта ERC-20  Фабиан Фогельштеллар на форуме Devcoin4 говорил о том, что хочет внедрить похожую технологию.... пока он "хочет" мы еще пару месяцев назад ее придумали и внедрили.

# Source code

https://gist.github.com/yuriy77k/96fb54f0d8da5aa7ffa90e2b84c0b416

the same as: https://etherscan.io/address/0xdf1f0c982e6574c4b89ec49e2636abd9a25a3126#code

# Disclosure policy

support@hyippro.io

# Platform

ETH

# Complexity

Low

**Comment by danbogd** [comment]
Auditing time : ~3 days.

**Comment by RideSolo** [comment]
Auditing time: 2 day.

**Comment by yuriy77k** [comment]
@danbogd @RideSolo assigned.

**Comment by danbogd** [comment]
My report is finished.

**Comment by alexo18** [comment]
Auditing time: 2 days

**Comment by yuriy77k** [comment]
@alexo18 assigned

**Comment by yuriy77k** [comment]
The contract contains high severity security issue. The report was sent to the developer.

**Comment by danbogd** [comment]
Уважаемый Юрий!

Можно получить отчет RideSolo по контракту HyipProfit. Хочу сделать работу над ошибками.

С уважением,

Богданов Денис


>Воскресенье,  2 декабря 2018, 11:41 +02:00 от Yuriy <notifications@github.com>:
>
>The contract contains high severity security issue. The report was sent to the developer.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Денис Богданов

**Comment by yuriy77k** [comment]
Здрвсвуйте.


Вот рапорат: https://gist.github.com/yuriy77k/62062fe7b88eda1af886e2782d0ee349


02.12.2018 в 13:16, Denis Bogdanov <notifications@github.com> написал:
Уважаемый Юрий!

Можно получить отчет RideSolo по контракту HyipProfit. Хочу сделать работу над
ошибками.

С уважением,

Богданов Денис


>Воскресенье, 2 декабря 2018, 11:41 +02:00 от Yuriy
<notifications@github.com>:
>
>The contract contains high severity security issue. The report was sent to
the developer.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly, view it on GitHub , or mute the thread .

-- 
Денис Богданов

**Comment by danbogd** [comment]
Спасибо.


>Воскресенье,  2 декабря 2018, 14:49 +02:00 от Yuriy <notifications@github.com>:
>
>Здрвсвуйте.
>
>
>Вот рапорат:  https://gist.github.com/yuriy77k/62062fe7b88eda1af886e2782d0ee349
>
>
>02.12.2018 в 13:16, Denis Bogdanov < notifications@github.com > написал:
>Уважаемый Юрий!
>
>Можно получить отчет RideSolo по контракту HyipProfit. Хочу сделать работу над
>ошибками.
>
>С уважением,
>
>Богданов Денис
>
>
>>Воскресенье, 2 декабря 2018, 11:41 +02:00 от Yuriy
>< notifications@github.com >:
>>
>>The contract contains high severity security issue. The report was sent to
>the developer.
>>—
>>You are receiving this because you were mentioned.
>>Reply to this email directly, view it on GitHub , or mute the thread .
>
>-- 
>Денис Богданов
>
>—
>You are receiving this because you authored the thread.
>Reply to this email directly, view it on GitHub, or mute the thread.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Денис Богданов

**Comment by yuriy77k** [comment]
# 1. Summary

[HyipProfit](https://etherscan.io/address/0xdf1f0c982e6574c4b89ec49e2636abd9a25a3126#code) security audit report performed by [Callisto Security Audit Department](https://github.com/EthereumCommonwealth/Auditing)

# 2. In scope

- [HyipProfit.sol](https://gist.github.com/yuriy77k/96fb54f0d8da5aa7ffa90e2b84c0b416)

# 3. Findings

In total, **5 issues** were reported including:

- 1 high severity issues.

- 3 medium severity issues.

- 1 low severity issues.

## 3.1.Dividends Topup Logic

### Severity: medium

### Description

When the ico is finalized the same fallback function used to buy tokens is used by the team to topzup the dividends, if an investors send ether after the ico end if the amount is higher than 1 eth than it will be distributed to tokens holders.
Contract developers should use a different function or implement

### Code snippet

https://gist.github.com/RideSolo/9fc994080586be2d67e6ae34b8790b06#file-hyipprofit-sol-L195

## 3.2. Users Withdrawal

### Severity: medium

### Description

In stage 2 people who participated to the presale are allowed to withdraw up to 40 to their initial investment, since the team will vest on each stage a part of it.
in stage to as implemented on `getAvailableFundsForTheTeam` the team will get a total of 30% from stage one then half of the rest of the presale fund 35%, in total 65%, however as explained before the users are allow to withdraw up to 40% (check function `getPreSaleWeiToReturn`).

The same issue is also applicable for stage 5 with the `icoFund`.

### Code snippet

https://gist.github.com/RideSolo/9fc994080586be2d67e6ae34b8790b06#file-hyipprofit-sol-L337

https://gist.github.com/RideSolo/9fc994080586be2d67e6ae34b8790b06#file-hyipprofit-sol-L308

https://gist.github.com/RideSolo/9fc994080586be2d67e6ae34b8790b06#file-hyipprofit-sol-L315

## 3.3. Truncated Buy Token Value

### Severity: high

### Description

Any investor that send an amount of ether higher than `N x currentPrice` will have the token amount that he bought truncated, since `msg.value` is directly divided by the `currentPrice`.

### Code snippet

https://gist.github.com/RideSolo/9fc994080586be2d67e6ae34b8790b06#file-hyipprofit-sol-L173

### Recommendation

- Write the conversion as a fraction that equals 1.
- Multiply the value to be converted using the previous fraction.
- Solidity always truncate the value of X when divided by Y, developers should first multiply than divided to get the non-truncated value.

## 3.4. Contract Logic

### Severity: medium

### Description

As per the audit request description the ICO has 4 stages, after the 4th stage (0,1,2,3) the token price is set to zero (check `getCurrentSellPrice`):

- The fallback function used to buy tokens will throws since a division per zero will occur (user a require to avoid such practice).
- After the 4th stage (`currentStage == 4`) the `checkIfMissionCompleted` function check an external address balance to submit next ico stages that will allow the withdrawal of the ether by the team or by the investors, developers should explain the logic used for better understanding and possible avoidance of any possible issues.

### Code snippet

https://gist.github.com/RideSolo/9fc994080586be2d67e6ae34b8790b06#file-hyipprofit-sol-L315

https://gist.github.com/RideSolo/9fc994080586be2d67e6ae34b8790b06#file-hyipprofit-sol-L173

https://gist.github.com/RideSolo/9fc994080586be2d67e6ae34b8790b06#file-hyipprofit-sol-L358#L360

## 3.5. Known vulnerabilities of ERC-20 token

### Severity: low

### Description

1. It is possible to double withdrawal attack. More details [here](https://docs.google.com/document/d/1YLPtQxZu1UAvO9cZ1O2RPXBbT0mooh4DYKjA_jp-RLM/edit)
2. Lack of transaction handling mechanism issue. [WARNING!](https://gist.github.com/Dexaran/ddb3e89fe64bf2e06ed15fbd5679bd20) This is a very common issue and it already caused millions of dollars losses for lots of token users! More details [here](https://docs.google.com/document/d/1Feh5sP6oQL1-1NHi-X1dbgT3ch2WdhbXRevDN681Jv4/edit)

## 4. Conclusion

The highlighted issues should be fixed before deployment.


# 5. Revealing audit reports

https://gist.github.com/yuriy77k/ad17cafb5e9536bf55294d2c1ffacf96

https://gist.github.com/yuriy77k/c38289fc9a4a056b3c19700039650263

https://gist.github.com/yuriy77k/0a0f38160e1f4dda90ff5e20924ea78c
